<?php 
/*
usage:
$block = $this->getLayout()->createBlock("catalog/product")
	->setData('product', $_product)
	->setTemplate("catalog/product/available_sizes.phtml")
	->toHtml();
	
equiv to xml
<block type="catalog/product" name="available_sizes" template="catalog/product/available_sizes.phtml">	
*/ ?>
<div id="available-sizes">
	<?php
	$sizes0 = array();
	/*
	- set in calling template using code
	$block->setData('product', $_product);
	*/
	$_product = $this->getProduct();
	if ($_product->isConfigurable()) 
	{
		$allProducts = $_product->getTypeInstance(true)->getUsedProducts(null, $_product);
		foreach ($allProducts as $subproduct) 
		{
			if ($subproduct->isSaleable()) 
			{
				// size, mens_jacket_size, s_m_l_xl_sizes, phone_colour
				if ($subproduct->getAttributeText("size")) 
				{
					$sizes0[] = trim($subproduct->getAttributeText('size'));
				}
			}
		}
		if(count($sizes0) > 0) 
		{
			sort($sizes0);
			echo "Available sizes: <b>" . implode(", ", $sizes0) . "</b>";
		}
			
	}
	?>
</div>