<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php $productCollection = $this->getLoadedProductCollection()->addAttributeToSelect('image'); ?>        
<?php $_collectionSize = $productCollection->count() ?>        

	<?php
		/* Responsive Design : menu */
		/*
		$_helper = $this->helper('catalog/output');
		$subCategory = Mage::registry('current_category');		
		if ($subCategory != null && $subCategory->getLevel() == 3) {
			$parentCategory = Mage::getModel('catalog/category')->load($subCategory->getParentId()); 
		} else {
			$parentCategory = Mage::getModel('catalog/category')->load($subCategory->getId()); 	
		}
			
		$filter = new Mage_Widget_Model_Template_Filter();
		$_widget = $filter->filter('{{widget type="pronav/category_widget_subcategories_list" levels="1" columns="1" thumbnail_images="No" category_images="No" selected_cat="Yes" template="pronav/items/widget/link/subcategories/sortedlist.phtml" id_path="category/' . $parentCategory->getId() .'"}}');             
		
		echo '<div class="rsp-nav-group">';
			echo '<div class="rsp-nav-header">';				
				echo '<div class="rsp-nav-title rsp-nav-toggle">';
					echo '<img class="icon-menu" src="' . $this->getSkinUrl('images/core/menu-icon-grey.png') . '" alt="main menu">';				
					echo $parentCategory->getMetaTitle();
					//echo $parentCategory->getName();
				echo '</div>';
				
			echo '</div>';
		
			echo '<div class="rsp-nav-menu-toggle" style="display:none">';
				echo '<ul class="rsp-nav-menu">';
					echo $_widget;
				echo '</ul>';
			echo '</div>';
		echo '</div>';		
		*/
	?>

<h1><?php echo $this->getLayer()->getCurrentCategory()->getName() ?></h1>

<div class="row">
	<div id="collection-category2" class="span12">
		<div id="collection-carousel" class="carousels slides">
			<div class="carousel-inners">
				<div class="item">  
					<ul class="thumbnails">  
				<?php $i = 0; ?>
				<?php $group_count = 0; ?>
				<?php $item_group_count = 0; ?>
				<?php foreach ($productCollection as $_product): ?>
										
					<?php if ($item_group_count == 0) { ?>                     
<!--						<div class="item <?php if ($group_count == 0): ?>active<?php endif ?>">  
							<ul class="thumbnails">    -->
					<?php } ?>   
					
						<li style="list-style: none;">  
							<div class="product-item-group">
								<div class="product-image">
									<?php /*
								    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><div><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(235,539); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></div></a> 
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><div><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(235, 300); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></div></a>
									 */ ?>
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><div><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(235,300); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></div></a>
								</div>                                    
								<div class="product-name">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
								</div>
							</div>                               
						</li>    
						
					<?php $item_group_count++; ?>    
					<?php $i++; ?>    
					
					<?php if ($item_group_count == 4) { ?>
<!--							</ul>
						</div>          -->
						<?php
						$item_group_count = 0;
						$group_count++;
						?> 				
					<?php } elseif ($_collectionSize % 4 != 0 && $i == $_collectionSize) { ?>
<!--							</ul>
						</div>          -->
						<?php
						$item_group_count = 0;
						$i = 0;
						?> 										
					<?php } ?>					
				<?php endforeach ?>	
					</ul>
				</div> 			
			</div>
			
			<div class="controls">
				<a class="carousel-control left" href="#collection-carousel" data-slide="prev">&lsaquo;</a>
				<ol class="carousel-indicators">
					<?php for($i=0; $i <= $group_count; $i++) { ?>
					<li data-target="#collection-carousel" data-slide-to="<?php echo $i ?>" <?php if ($i == 0) { ?>class="active"<?php } ?>></li>
					<?php } ?>
				</ol>
				<a class="carousel-control right" href="#collection-carousel" data-slide="next">&rsaquo;</a>
			</div>	
		</div>		
	</div>
</div>