<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php $_productCollection = $this->getLoadedProductCollection() ?>        
<?php $_collectionSize = $_productCollection->count() ?>        

<div class="span12" id="featured-product">
	<?php /* desktop/tablet version, 4 products at a time */ ?>
	<div id="featured-product-carousel" class="carousel slide">       
        <div class="carousel-inner">
		<?php $products_per_slide = 4; ?>
        <?php $i = 0; ?>
        <?php $group_count = 0; ?>
        <?php $item_group_count = 0; ?>

        <?php foreach ($_productCollection as $_product): ?>
            <?php if ($item_group_count == 0) { ?>                     
				<div class="item <?php if ($group_count == 0): ?>active<?php endif ?>">  
					<div class="row">
						<ul class="thumbnails">    
            <?php } ?>                               
                            <li class="span3" style="list-style: none;">  
                            <div class="product-item-group">
                                <div class="product-image">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220, 280); ?>" width="220" height="280" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
                                </div>                                    
                                <div class="product-name">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
                                </div>
                            </div>                               
                            </li>    
                                         
			<?php $item_group_count++; ?>    
			<?php $i++; ?>    

			<?php if ($item_group_count == $products_per_slide) { ?>
						</ul>
					</div>
				</div>
			<?php
				$item_group_count = 0;
				$group_count++;
				?> 				
			<?php } elseif ($_collectionSize % $products_per_slide != 0 && $i == $_collectionSize) { ?>
						</ul>
					</div>
				</div>
			<?php
				$item_group_count = 0;
				$i = 0;
				?> 										
			<?php } ?>			           
        <?php endforeach ?>
            
        </div>
		
        <a class="carousel-control left" href="##featured-product-carousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="##featured-product-carousel" data-slide="next">&rsaquo;</a>
    </div>
	
	<?php /* mobile version 320 width, 2 products at a time */ ?>
    <div id="featured-product-carouselm320" class="carousel slide">       
        <div class="carousel-inner">
        <?php $mproducts_per_slide = 2; ?>
		<?php $i = 0; ?>
        <?php $group_count = 0; ?>
        <?php $item_group_count = 0; ?>

        <?php foreach ($_productCollection as $_product): ?>
            <?php if ($item_group_count == 0) { ?>                     
				<div class="item <?php if ($group_count == 0): ?>active<?php endif ?>">  
					<div class="row">
						<ul class="thumbnails">    
            <?php } ?>                               
                            <li class="span3" style="list-style: none;">  
                            <div class="product-item-group">
                                <div class="product-image">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(150, 200); ?>" width="220" height="280" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
                                </div>                                    
                                <div class="product-name">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
                                </div>
                            </div>                               
                            </li>    
                                         
			<?php $item_group_count++; ?>    
			<?php $i++; ?>    

			<?php if ($item_group_count == $mproducts_per_slide) { ?>
						</ul>
					</div>
				</div>
			<?php
				$item_group_count = 0;
				$group_count++;
				?> 				
			<?php } elseif ($_collectionSize % $mproducts_per_slide != 0 && $i == $_collectionSize) { ?>
						</ul>
					</div>
				</div>
			<?php
				$item_group_count = 0;
				$i = 0;
				?> 										
			<?php } ?>			           
        <?php endforeach ?>
            
        </div>
		
        <a class="carousel-control left" href="##featured-product-carouselm320" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="##featured-product-carouselm320" data-slide="next">&rsaquo;</a>
    </div>
	
	<?php /* mobile version 480 width, 3 products at a time */ ?>
    <div id="featured-product-carouselm480" class="carousel slide">       
        <div class="carousel-inner">
        <?php $mproducts_per_slide = 3; ?>
		<?php $i = 0; ?>
        <?php $group_count = 0; ?>
        <?php $item_group_count = 0; ?>

        <?php foreach ($_productCollection as $_product): ?>
            <?php if ($item_group_count == 0) { ?>                     
				<div class="item <?php if ($group_count == 0): ?>active<?php endif ?>">  
					<div class="row">
						<ul class="thumbnails">    
            <?php } ?>                               
                            <li class="span3" style="list-style: none;">  
                            <div class="product-item-group">
                                <div class="product-image">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(150, 200); ?>" width="220" height="280" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
                                </div>                                    
                                <div class="product-name">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
                                </div>
                            </div>                               
                            </li>    
                                         
			<?php $item_group_count++; ?>    
			<?php $i++; ?>    

			<?php if ($item_group_count == $mproducts_per_slide) { ?>
						</ul>
					</div>
				</div>
			<?php
				$item_group_count = 0;
				$group_count++;
				?> 				
			<?php } elseif ($_collectionSize % $mproducts_per_slide != 0 && $i == $_collectionSize) { ?>
						</ul>
					</div>
				</div>
			<?php
				$item_group_count = 0;
				$i = 0;
				?> 										
			<?php } ?>			           
        <?php endforeach ?>
            
        </div>
		
        <a class="carousel-control left" href="##featured-product-carouselm480" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="##featured-product-carouselm480" data-slide="next">&rsaquo;</a>
    </div>	
</div>