<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
 
$imageW = 220; //224    was 200
$imageH = '249px'; //254	was 226
?>
<?php $_product = $this->getProduct(); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php
	$subCategory = Mage::registry('current_category');
	$parentCategory = null;
	$isCollectionCategory = false;

	if ($subCategory != null) {
		$parentCategory = Mage::getModel('catalog/category')->load($subCategory->getParentId()); 
	}
	
	if ($parentCategory != null) {
		if (strtolower($parentCategory->getName()) == 'collections') {
			$isCollectionCategory = true;
		}
	}
?>
<?php $_productCollection=$this->getLoadedProductCollection(); ?>
<?php if($isCollectionCategory): ?>
	<?php $productCollection = $this->getLoadedProductCollection()->addAttributeToSelect('image'); ?>        
	<?php $_collectionSize = $productCollection->count() ?>        

		<?php
			/* Responsive Design : menu */
			/*
			$_helper = $this->helper('catalog/output');
			$subCategory = Mage::registry('current_category');		
			if ($subCategory != null && $subCategory->getLevel() == 3) {
				$parentCategory = Mage::getModel('catalog/category')->load($subCategory->getParentId()); 
			} else {
				$parentCategory = Mage::getModel('catalog/category')->load($subCategory->getId()); 	
			}
				
			$filter = new Mage_Widget_Model_Template_Filter();
			$_widget = $filter->filter('{{widget type="pronav/category_widget_subcategories_list" levels="1" columns="1" thumbnail_images="No" category_images="No" selected_cat="Yes" template="pronav/items/widget/link/subcategories/sortedlist.phtml" id_path="category/' . $parentCategory->getId() .'"}}');             
			
			echo '<div class="rsp-nav-group">';
				echo '<div class="rsp-nav-header">';				
					echo '<div class="rsp-nav-title rsp-nav-toggle">';
						echo '<img class="icon-menu" src="' . $this->getSkinUrl('images/core/menu-icon-grey.png') . '" alt="main menu">';				
						echo $parentCategory->getMetaTitle();
						//echo $parentCategory->getName();
					echo '</div>';
					
				echo '</div>';
			
				echo '<div class="rsp-nav-menu-toggle" style="display:none">';
					echo '<ul class="rsp-nav-menu">';
						echo $_widget;
					echo '</ul>';
				echo '</div>';
			echo '</div>';		
			*/
		?>

	<h1><?php echo $this->getLayer()->getCurrentCategory()->getName() ?></h1>

	<div class="row">
		<div id="collection-category2" class="span12">
			<div id="collection-carousel" class="carousels slides">
				<div class="carousel-inners">
					<div class="item">  
						<ul class="thumbnails">  
					<?php $i = 0; ?>
					<?php $group_count = 0; ?>
					<?php $item_group_count = 0; ?>
					<?php foreach ($productCollection as $_product): ?>
											
						<?php if ($item_group_count == 0) { ?>                     
	<!--						<div class="item <?php if ($group_count == 0): ?>active<?php endif ?>">  
								<ul class="thumbnails">    -->
						<?php } ?>   
						
							<li style="list-style: none;">  
								<div class="product-item-group">
									<div class="product-image">
										<?php /*
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><div><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(235,539); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></div></a> 
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><div><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(235, 300); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></div></a>
										 */ ?>
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><div><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(235,300); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></div></a>
									</div>                                    
									<div class="product-name">
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
									</div>
								</div>                               
							</li>    
							
						<?php $item_group_count++; ?>    
						<?php $i++; ?>    
						
						<?php if ($item_group_count == 4) { ?>
	<!--							</ul>
							</div>          -->
							<?php
							$item_group_count = 0;
							$group_count++;
							?> 				
						<?php } elseif ($_collectionSize % 4 != 0 && $i == $_collectionSize) { ?>
	<!--							</ul>
							</div>          -->
							<?php
							$item_group_count = 0;
							$i = 0;
							?> 										
						<?php } ?>					
					<?php endforeach ?>	
						</ul>
					</div> 			
				</div>
				
				<div class="controls">
					<a class="carousel-control left" href="#collection-carousel" data-slide="prev">&lsaquo;</a>
					<ol class="carousel-indicators">
						<?php for($i=0; $i <= $group_count; $i++) { ?>
						<li data-target="#collection-carousel" data-slide-to="<?php echo $i ?>" <?php if ($i == 0) { ?>class="active"<?php } ?>></li>
						<?php } ?>
					</ol>
					<a class="carousel-control right" href="#collection-carousel" data-slide="next">&rsaquo;</a>
				</div>	
			</div>		
		</div>
	</div>
<?php elseif(!$_productCollection->count()): ?>

<!-- Product Availability Requirements 
================================================== -->	
<?php
$message = $this->getMessagesBlock()->getGroupedHtml();
if (strlen($message) > 0) {
	echo "<div id='messages_product_view'>" . $message . "</div>";
}
?>

<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div>
	<p class="note-msg">
		<?php echo $this->__('There are no products matching the selection.') ?>
	</p>
</div>
<?php else: ?>

	<?php
		/* Responsive Design : menu */
		/*
		$_helper = $this->helper('catalog/output');
		$subCategory = Mage::registry('current_category');		
		if ($subCategory != null && $subCategory->getLevel() == 3) {
			$parentCategory = Mage::getModel('catalog/category')->load($subCategory->getParentId()); 
		} else {
			$parentCategory = Mage::getModel('catalog/category')->load($subCategory->getId()); 	
		}
			
		$filter = new Mage_Widget_Model_Template_Filter();
		$_widget = $filter->filter('{{widget type="pronav/category_widget_subcategories_list" levels="1" columns="1" thumbnail_images="No" category_images="No" selected_cat="Yes" template="pronav/items/widget/link/subcategories/sortedlist.phtml" id_path="category/' . $parentCategory->getId() .'"}}');             
		
		echo '<div class="rsp-nav-group">';
			echo '<div class="rsp-nav-header">';				
				echo '<div class="rsp-nav-title rsp-nav-toggle">';
					echo '<img class="icon-menu" src="' . $this->getSkinUrl('images/core/menu-icon-grey.png') . '" alt="main menu">';				
					echo $parentCategory->getMetaTitle();
					//echo $parentCategory->getName();
				echo '</div>';
				
			echo '</div>';
		
			echo '<div class="rsp-nav-menu-toggle" style="display:none">';
				echo '<ul class="rsp-nav-menu">';
					echo $_widget;
				echo '</ul>';
			echo '</div>';
		echo '</div>';		 
		*/
	?>

<div class="category-products">
    
	<?php /*--- Begin: Custom Pagination ---*/ ?>	
    <?php
        /* @var $toolbar Mage_Catalog_Block_Product_List_Toolbar */
        // get toolbars limits - overrides default pager limit
        $toolbar = Mage::getBlockSingleton('catalog/product_list_toolbar')->getAvailableLimit();

        /* @var $pager Mage_Page_Block_Html_Pager */
        $pager = $this->getLayout()->createBlock('page/html_pager', 'bootstrapped.standalone.pager');

        // set limit - uses category's instead of default pager's (10-20-50)
        $pager->setAvailableLimit($toolbar);
        // need to set collection
        $pager->setCollection($_productCollection);
        //set custom template
        $pager->setTemplate('catalog/product/list/pager.phtml');
        echo $pager->toHtml();
    ?>
    <?php /*--- End: Custom Pagination ---*/ ?>	

    
    <div class="toolbar-div">
	<?php /*--- Begin: Custom Pagination for mobile ---*/ ?>	
    <?php
        /* @var $toolbar Mage_Catalog_Block_Product_List_Toolbar */
        // get toolbars limits - overrides default pager limit
        $toolbar = Mage::getBlockSingleton('catalog/product_list_toolbar')->getAvailableLimit();

        /* @var $pager Mage_Page_Block_Html_Pager */
        $pager = $this->getLayout()->createBlock('page/html_pager', 'bootstrapped.standalone.pager');

        // set limit - uses category's instead of default pager's (10-20-50)
        $pager->setAvailableLimit($toolbar);
        // need to set collection
        $pager->setCollection($_productCollection);
        //set custom template
        $pager->setTemplate('catalog/product/list/pager.phtml');
        echo $pager->toHtml();
    ?>
    <?php /*--- End: Custom Pagination ---*/ ?>	

    <!-- Filter Draft
    ================================================== -->				
    <?php echo $this->getToolbarHtml() ?>
	
        <div class="row filteroptions-placeholder ">
            
            <div id="filteroptions" name="filteroptions" class="span12">   
                <div class="filteroptions-box">
                    <?php echo $this->getChildHtml('filters'); ?>

                </div>
            </div>
        </div>
        <script>
            jQuery(document).ready(function(){
                jQuery('.btn-filter-options').click(function(){    
                  
                    if (jQuery('#filteroptions').is(':visible')){
                        jQuery(this).find('span').removeClass('icon-caret-up').addClass('icon-caret-down');
                    }else{                        
                        jQuery(this).find('span').removeClass('icon-caret-down').addClass('icon-caret-up');
                    }
                    jQuery('#filteroptions').slideToggle();
                });
            });
        </script>           
<!-- End: Filter Draft
================================================== -->	        
       
    </div>
    
    
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <?php if ($_product->getTypeId() != "panel"): ?>
            <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                <?php // Product Image ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <?php // Product description ?>
                <div class="product-shop">
                    <div class="f-fix">
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>

                        <?php if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product) ?>
                        <?php endif; ?>

                        <?php if ($_product->getComingSoon() && preg_match("/^yes$/i", $_product->getAttributeText('coming_soon'))): ?>
                            <div class="price-box"><b><?php echo $this->__('Coming Soon') ?></b></div>
                        <?php else: ?>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                        <?php endif; ?>

                        <?php if ($_product->getTypeId() == "ugiftcert" || stripos($_product->getName(),"gift voucher")>0): ?>
                            <script type="text/javascript">
								jQuery('#product-price-<?php echo $_product->getId(); ?> .price').prepend("From ");
							</script>
                        <?php endif ?>

                        <?php
                        if ($_product->getResource()->getAttribute('in_store_only') != null)
                        {
                            $onlyInStore = $_product->getAttributeText('in_store_only');
                        }
                        ?>
                        <?php if (isset($onlyInStore) && $onlyInStore == "Yes"): ?>
                            <p class="add-to-cart"><b><?php echo $this->__('Only Available in Stores') ?></b></p>
                        <?php elseif($_product->isSaleable()): ?>
                            <p class="add-to-cart"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>

                        <div class="desc std">
                            <?php echo $_product->getDescription(); ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                        </div>

                        <?php if ($_product->getShowAvailableUnits()):?>
                            <?php
                                $qtyStock = 0;
                                if ($_product->getTypeId() == "configurable")
                                {
                                    $associatedProducts = $_product->getTypeInstance()->getUsedProducts();
                                    // Fetch the associated products
                                    foreach($associatedProducts as $child)
                                    {
                                        $qtyStock += Mage::getModel('cataloginventory/stock_item')->loadByProduct($child)->getQty();
                                    }
                                }
                                else
                                {
                                    $qtyStock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty();
                                }
                            ?>
                            <?php $qtyStockShowLimit = Mage::getStoreConfig('cataloginventory/options/show_products_left_limit'); ?>
                            <?php if ($qtyStockShowLimit && $qtyStockShowLimit >= $qtyStock): ?>
                                <div><b><?php echo $this->__('Only %s left', $qtyStock) ?></b></div>
                            <?php endif; ?>
                        <?php endif;?>

                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php
    $_collectionSize = $_productCollection->count();
    $_columnCount = $this->getColumnCount();
	$item_group_count = 0;
    $i=0;
	//$_columnCount = 4;
    ?>
    
	<div class="products-grid-container">
		<ul class="products-grid">
			<?php foreach ($_productCollection as $_product): ?>

			<?php /*					
					 <?php if ($i%$_columnCount==0): ?>					
						<div class="products-grid-container">
							<ul class="products-grid">					
					<?php endif ?>  					
			 */ ?> 

					<?php 
						$productAvailability = false;
						if ($_product->getResource()->getAttribute('available_date') != null) {
								$adate = strtotime($_product->getAvailableDate());
								$today = Mage::getModel('core/date')->timestamp(time());
								// can be ordered yet?
								if ($today < $adate) {
										$productAvailability = sprintf("%s", date("M Y", $adate) );
								}
						}
						else if ($_product->getResource()->getAttribute('in_store_only') != null) {
								$onlyInStore = $_product->getAttributeText('in_store_only');
						}
					?>        

					<?php /* <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>"> */ ?>
					<li class="item">
						<div class="grid-img-container <?php if ($productAvailability) { ?>availability-magic-toolbox-selectors<?php } ?>">
							<?php if($_product->isSaleable()): ?>
								<?php if ($_product->getTypeId() == "panel"): ?>
									<div class="clickable">
										<?php if (Mage::helper('advertpanels')->isValidUrl($_product->getDescription())): ?>
											<?php $link = $_product->getDescription(); ?>
										<?php else: ?>
											<?php $link = "javascript:void(0);"; ?>
										<?php endif; ?>
										<a href="<?php echo $link ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
											<img alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" width="<?php echo $imageW; ?>" height="<?php echo $imageH; ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imageW, $imageH); ?>" />
										</a>
									</div>
								<?php else: ?>
									<div class="clickable">
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
											<img  style="height:<?php echo $imageH; ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imageW, $imageH); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
										</a>
									</div>
								<?php endif; ?>
							<?php else: ?>
								<div class="clickable">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
										<img width="<?php echo $imageW; ?>" height="<?php echo $imageH; ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imageW, $imageH); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
									</a>
								   <?php /* html comment tag causes issue with html display MUST use PHP comment
										<p class="availability out-of-stock" style="background-color:#fff; border-top:1px solid #FF1658; border-bottom:1px solid #FF1658">
											<span><?php //echo $this->__('Out of stock') ?></span>
										</p> */
								   ?>								
								</div>
							<?php endif; ?>		
							</div>					

						<div class="details" style="text-align:center">
							<?php /*
									$productAvailability = false;
									if ($_product->getResource()->getAttribute('available_date') != null) {
											$adate = strtotime($_product->getAvailableDate());
											$today = Mage::getModel('core/date')->timestamp(time());
											// can be ordered yet?
											if ($today < $adate) {
													$productAvailability = sprintf("%s", date("M Y", $adate) );
											}
									}
									else if ($_product->getResource()->getAttribute('in_store_only') != null) {
											$onlyInStore = $_product->getAttributeText('in_store_only');
									} */
									if ($productAvailability) {
											echo sprintf("<div class='onlystores'>Arrives %s Pre-Order NOW!</div>", $productAvailability);
									}
									else if (isset($onlyInStore) && $onlyInStore == "Yes") {
											echo "<div class='onlystores'>Only Available in Stores</div>";
									}
							?>

							<?php if ($_product->getShowAvailableUnits()):?>
								<?php 	
									$qtyStock = 0;
									if ($_product->getTypeId() == "configurable")
									{
										$associatedProducts = $_product->getTypeInstance()->getUsedProducts();
										// Fetch the associated products
										foreach($associatedProducts as $child)
										{
											$qtyStock += Mage::getModel('cataloginventory/stock_item')->loadByProduct($child)->getQty();
										}
									}
									else 
									{
										$qtyStock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty();
									}
								?>
								<?php $qtyStockShowLimit = Mage::getStoreConfig('cataloginventory/options/show_products_left_limit'); ?>
								<?php if ($qtyStockShowLimit && $qtyStockShowLimit >= $qtyStock): ?>
									<div class="product-units-left"><?php echo $this->__('Only %s left', $qtyStock) ?></div>
								<?php endif; ?>
							<?php endif;?>
							<?php if ($_product->getTypeId() != "panel"): ?>
								<span class="product-name">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
										<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
									</a>
								</span>
							<?php endif;?>
							<?php
								/*
								$block = $this->getLayout()->createBlock("catalog/product");
								$block->setData('product', $_product);
								$block->setTemplate("catalog/product/available_sizes.phtml");
								echo $block->toHtml();
								*/
								// echo $_product->getComingsoon() . ",commingsoon=[" . $_product->getAttributeText('comingsoon');
								if ($_product->getComingsoon() && preg_match("/^yes$/i", $_product->getAttributeText('comingsoon'))) 
								{
									echo "<div class=\"coming-soon\">coming soon</div>";
								}
								elseif ($_product->getTypeId() != "panel")
								{
									echo $this->getPriceHtml($_product, true);
								}
							?>
							<?php if ($_product->getTypeId() == "ugiftcert" || stripos($_product->getName(),"gift voucher")>0): ?>
								<script type="text/javascript">
									jQuery('#product-price-<?php echo $_product->getId(); ?> .price').prepend("From ");
								</script>
							<?php endif; ?>
						</div>

						<!-- Add Quickshop Modal Here -->	
						<div class="quick-view-link-nav">
							<i class="icon-external-link"></i> <a href="#quickshop-modal" role="button" data-toggle="modal" class="quick-view-link" data-url="<?php echo Mage::getBaseUrl(), 'extcatalog/product/view/id/', $_product->getId() ?>"><?php echo $this->__('quickshop') ?></a>
						<div>
					</li>

				<?php $item_group_count++; ?>   
				<?php $i++; ?>    

				<?php /*			
						<?php if ($i >= $_columnCount) { ?>
								</ul>
							</div>						 
							<?php $group_count++; ?>
							<?php $i=0; ?>		
						<?php } elseif ($_collectionSize % $_columnCount != 0 && $item_group_count == $_collectionSize) { ?>
								</ul>
							</div>
							<?php $group_count++; ?> 								
							<?php $i=0; ?>  
						<?php }  ?>	
				*/ ?>                   

			<?php endforeach ?>
		</ul>
	</div>
	
	<?php /* Quickshop Modal */ ?>
	<div id="quickshop-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			</div>
			<div class="modal-body">
				<div class="throbber"></div>
			</div>
			<?php /* <div class="modal-footer"> </div> */ ?>		
		</div>
	</div>

	<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
	<script type="text/javascript">
	// Javascript to call 

	//<![CDATA[
	var productAddToCartForm = new VarienForm('product_addtocart_form');
	productAddToCartForm.submit = function(){
			if (this.validator.validate()) {
					this.form.submit();
			}
	}.bind(productAddToCartForm);
	// CONFIGURABLE SELECTOR FUNCTIONS (used in magiczoom/configurable.phtml)
	function colorSelected(id, value, product_image_src, product_big_image_src, color_div_id, product_id)
	{
		// Disable all the size
		jQuery("#size-container").children().not("#size-chart").each(
			function()
			{
				jQuery(this).addClass('size-disabled');
			}
		);
		// Update the product image
		jQuery(".MagicZoom img").attr("src", product_image_src);
		// Update the big zoomed image
		jQuery(".MagicZoomBigImageCont img").attr("src", product_big_image_src);
		// Set the value of the attribute in the hidden field
		document.getElementById(id).value = value;
		// Unselect the previous swatch (CSS)
		if (jQuery('.swatch-selected')) 
		{
			jQuery('.swatch-selected').removeClass('swatch-selected');
		}
		// Remove the previous available div
		if (jQuery("#available"))
		{
			jQuery("#available").remove();
		}
		// Apply CSS selection on the swatch
		jQuery("#"+color_div_id).addClass('swatch-selected');
		// Add the name of the color to the label
		if (jQuery('#selected-color')) 
		{
			jQuery('#selected-color').remove();
		}
		var newColorLabelDiv = "<span id='selected-color'> "+color_div_id+"</span>";
		jQuery('#color-selector-label').append(newColorLabelDiv);
		// Refresh sizes and price through the ProductRefresh module
		jQuery.ajax( {
			url : "/productrefresh/index",
			dataType : 'json',
			type : 'get',
			data : "product_id="+product_id+"&color="+value,
			success : function(data) {
				// If everything has worked
				if (data.status == "SUCCESS")
				{
					jQuery("#unavailable").remove();
					// We go through every size box
					jQuery("#size-container").children().not("#size-chart").each(
						function()
						{
							// Removing all the existing disabled class
							if (jQuery(this).hasClass('size-disabled')) jQuery(this).removeClass('size-disabled');
							// Adding the disabled class if this one is not available
							if (jQuery.inArray(jQuery(this).attr("id"),data.sizes) == -1) 
							{
								jQuery("#attribute131").val("");
								jQuery(this).addClass('size-disabled');
								if (jQuery(this).hasClass('size-selected')) 
								{
									jQuery(this).removeClass('size-selected');
								}
							}
						}
					);

					if (data.sizes.length == 0) 
					{
						jQuery("#size-container").append("<div id='unavailable' style='margin-bottom:10px'>Sorry, this color is currently out of stock.</div>");
						// Unselect the previous size (CSS)
						if (jQuery('.size-selected')) 
						{
							jQuery('.size-selected').removeClass('size-selected');
						}
					}

					// We calculate the new price
					var totalPrice = 0.00;
					totalPrice += parseFloat(jsonConf.basePrice);
					// Based on the returned values
					if (data.prices[value]>0) {
						totalPrice += parseFloat(data.prices[value]);
					}

					// We are changing the price if the new price is different
					// Or the special price if there is one							
					if (jQuery(".special-price #product-price-"+product_id+"_clone").html() != "$"+totalPrice.toFixed(2) && jQuery(".special-price #product-price-"+product_id+"_clone").html() != null)
					{
						jQuery(".special-price #product-price-"+product_id+"_clone").replaceWith("<span id='product-price-"+product_id+"_clone' class='price'>$"+totalPrice.toFixed(2)+"</span>");
						jQuery(".special-price #product-price-"+product_id+"_clone").effect("pulsate", {times:3}, 700);
					}
					else if (jQuery("#product-price-"+product_id+"_clone .price").html() != "$"+totalPrice.toFixed(2)) 
					{
						jQuery("#product-price-"+product_id+"_clone .price").replaceWith("<span class='price'>$"+totalPrice.toFixed(2)+"</span>");
						jQuery("#product-price-"+product_id+"_clone .price").effect("pulsate", {times:3}, 700);
					}
				}
			}
		});
	}

	// Corresponding function for the size
	function sizeSelected(id, value, size_div_id)
	{
		// We check if the div chosen is available or not
		if (jQuery("#"+size_div_id).hasClass('size-disabled')) return;
		// Set the value of the attribute in the hidden field
		document.getElementById(id).value = value;
		// Unselect the previous size (CSS)
		if (jQuery('.size-selected')) 
		{
			jQuery('.size-selected').removeClass('size-selected');
		}
		// Apply CSS selection on the size
		jQuery("#"+size_div_id).addClass('size-selected');
		
		<?php if ($_product->getShowAvailableUnits()): ?>
		// Base URL in case we're using a subfolder
		var base_url = '';
		// Handle the HTTPS protocol
		if (location.protocol == 'https:')
		{
			base_url="<?php echo Mage::getUrl('',array('_secure'=>true));?>";
		}
		else
		{
			base_url='<?php echo Mage::getBaseUrl()?>';
		}
		jQuery.ajax( {
			url : base_url+"productrefresh/index/unitsPerSize",
			dataType : 'json',
			type : 'get',
			data : "product_id="+<?php echo $_product->getId() ?>+"&size="+size_div_id,
			success : function(data) {
				// If everything has worked
				if (data.status == "SUCCESS")
				{
					if (jQuery("#available"))
					{
						jQuery("#available").remove();
					}
					if (data.units) 
					{
						var qtyStockShowLimit = <?php echo Mage::getStoreConfig('cataloginventory/options/show_products_left_limit');?>;
						if (data.units <= qtyStockShowLimit)
						{
							jQuery("#size-container").append("<div id='available'>Only "+data.units+" left in this size.</div>");
						}
					}
				}
			}
		});
		<?php endif; ?>
	}
	//]]>
	</script>

	<script type="text/javascript">

		function showQuickView(link, e) {
			var quickUrl = jQuery(link).data('url');
			//jQuery('#quickshop-modal').modal('show');

			jQuery.get(quickUrl, function(data) {
					//jQuery('#quickview-dialog-content').html(data);
					jQuery('.modal-body').html(data);
			});
		}


		jQuery(document).ready(function() {
			jQuery('.quick-view-link').on('click', function(e) {				   			
				showQuickView(this, e);
				//jQuery(this).click(function() { return false; });
				//e.preventDefault();
			});

			// empty quickview modal content body
			jQuery('#quickshop-modal').on('hide',function(e){
				//e.preventDefault();
				jQuery('.modal-body').html('<div class="throbber"></div>');
			});


		});                
	</script>     
	<?php endif; ?>
                
</div>
<?php endif; ?>
