<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>
<?php if(!$_productCollection->count()): ?>
<div class="alert fade in">
  <a class="close" data-dismiss="alert">×</a>
  <?php echo $this->__('There are no products matching the selection.') ?>
</div>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
<?php
/**
 * Product List Mode
 *
 */
?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list unstyled row-fluid" id="products-list">
        <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?> row-fluid">
            <?php // Product Image ?>
            <div class="span4"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image thumbnail"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(225); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a></div>
            <?php // Product description ?>
            <div class="span8">
                <div class="thumbnail data">
                    <div class="caption">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <div class="row-fluid">
                        <span class="pull-right">
                            <?php if($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-danger" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                        </span>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <p class="add-to-links unstyled">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist label label-info"><?php echo $this->__('Add to Wishlist') ?></a>
                        <?php endif; ?>
                        
                        <!-- 20130724 - @BEN_NICOLL We do not require Add To Compare functionality
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare label label-info"><?php echo $this->__('Add to Compare') ?></a>
                        <?php endif; ?>
                        -->
                        
                    </p>
                    </div>
                </div>
            </div>
        </li><hr>
        <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

<?php
/**
 * Product Grid Mode
 *
 */
?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
            <ul class="products-grid unstyled thubmnails row-fluid">
            <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> span">
                <div class="thumbnail">
	                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image thumbnail"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
	
	                <div class="product">
	                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
	                           
   
	                    <!--20130721 - Remove Reviews System from product catalog
	                    <?php if($_product->getRatingSummary()): ?>
	                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
	                    <?php endif; ?>
	                    -->
	                    
	                    <?php echo $this->getPriceHtml($_product, true) ?>
	                    
	                    <!-- 20130721 - Remove Add to cart in favour of a quick look
	                    <?php if($_product->isSaleable()): ?>
	                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-danger btn-mini" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
	                    <?php else: ?>
	                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
	                    <?php endif; ?>
	                    -->
	                    
	                    <!-- 20130721 - Remove Add Compare and Add to Wishlist for now
	                    <p class="add-to-links unstyled">
	                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
	                        <a href="<?php echo $_compareUrl ?>" class="link-compare label label-info pull-right"><?php echo $this->__('Add to Compare') ?></a>
	                        <?php endif; ?>
	                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
	                            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist label label-info"><?php echo $this->__('Add to Wishlist') ?></a>
	                        <?php endif; ?>
	
	                    </p>
	                    -->
	                    
						<?php 
						$_product = Mage::getModel('catalog/product')->load($_product->getId());
						$_productCollection = $_category->getProductCollection()
							->addAttributeToSelect('color');
						echo $_product->getColor();
						?>
				


						<!-- Product Image Box
						================================================== -->			
	                    <div id="quickshopModal">

		                    <!-- Button to trigger modal -->
		                    <div id="quickshop">
		                    	<a href="#myModal<?php echo $_product->getId() ?>" role="button" data-toggle="modal"><i class="icon-external-link"></i> Quick Shop</a>
		                    	
		                    </div>
	
							<!-- Modal -->
							<div id="myModal<?php echo $_product->getId() ?>" class="span8 modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

									<!-- Close Modal Row
									================================================== -->			
									<div class="row">
										<div class="span8 modal-header">
											<button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove-sign"></i></button>
										</div>										
									
									</div>

									<!-- End: Close Modal Row
									================================================== -->			

									
									
									<!-- Product Body Row
									================================================== -->			
									<div class="row">


											<!-- Product Image Box
											================================================== -->			
											<div class="span4" id="modal-media">
										        <div>
											        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
										        </div>
										        
										        <?php $product = Mage::getModel('catalog/product')->load($_product->getId());
									                foreach ($product->getMediaGalleryImages() as $image) {
									                     echo var_export($image->getUrl());
									                     
									                }  ?>

									        									        
										        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"><i class="icon-search"></i>View full details and reviews</a>

										    </div>
							
											<!-- End: Product Image Box
											================================================== -->			



											<!-- Product Details
											================================================== -->					        
									        <div class="span4" id="modal-shop">
							
													<!-- Product Title
													================================================== -->					        
								                    <div class="row">
								                    	<div class="span4" id="modal-name">
												        	<h1 id="myModalLabel"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
					
												        </div>
												    </div>
								
													<!-- End: Product Title
													================================================== -->					        
								
								
													<!-- Price SQU and Social Block
													================================================== -->					        
								                    <div class="row">
										
															<!-- Price and SQU
															================================================== -->					        
										                    <div class="span2" id="modalprice">
											                	<?php echo $this->getPriceHtml($_product, true) ?>
																	  	
													        </div>					
											
															<!-- End: Price and SQU
															================================================== -->					        					
									
															<!-- Social Block
															================================================== -->					        
										                    <div class="span2">
																<div class="searchsocial align-right">
													            	<ul>
													                    <li class="pinterest"><a href="#" title=""><i class="icon-pinterest"></i></a></li>
													                    <li class="facebook"><a href="#" title=""><i class="icon-facebook"></i></a></li>
													                    <li class="instagram"><a href="#" title=""><i class="icon-instagram"></i></a></li>
													                    <li class="youtube"><a href="#" title=""><i class="icon-youtube"></i></a></li>
												                    </ul>
											
																</div>
													        </div>		
															
															<!-- End: Social Block
															================================================== -->					        
													
								                    </div>
								                    				
													<!-- End: Price SQU and Social Block
													================================================== -->					        
								
								
													<!-- Descriptions and Dimentions Tabs Block Row
													================================================== -->					        
								                    <div class="row">
								
									                    <div class="span4" id="producttabs">
										                    <div class="tabbable">
															    
															    <!-- Tabs List
																================================================== -->					        							    
															    <ul id="myTab<?php echo $_product->getId() ?>" class="nav nav-tabs">
															      <li class="active"><a href="#description<?php echo $_product->getId() ?>" data-toggle="tab">Description</a></li>
															      <li><a href="#short<?php echo $_product->getId() ?>" data-toggle="tab">Fabric &amp; Care</a></li>
															      <li><a href="#dimensions<?php echo $_product->getId() ?>" data-toggle="tab">Dimensions</a></li>
															    </ul>
								
															    <!-- End: Tabs List
																================================================== -->					        							    
															    
															    
															    <!-- Tabs Content
																================================================== -->					        							    							    
															    <div class="tab-content">
																    
																    <!-- Description
																	================================================== -->					        
																	<div class="tab-pane active" id="description<?php echo $_product->getId() ?>">
																	  	<?php if ($_product->getDescription()):?>
																		  	<div class="description">
																			  	<!--<h2><?php echo $this->__('Description') ?></h2>-->
																		  		<div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?></div>
																			</div>
																		<?php endif;?>
																    </div>
								
																    <!-- End: Description
																	================================================== -->					        
								
								
																    <!-- Fabric and Care
																	================================================== -->					        
																	<div class="tab-pane" id="short<?php echo $_product->getId() ?>">
																	  	<?php if ($_product->getShortDescription()):?>
																		  	<div class="short-description">
																			  	<!--<h2><?php echo $this->__('Short Description') ?></h2>-->
																		  		<div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
																			</div>
																		<?php endif;?>
																    </div>
								
																    <!-- End: Fabric and Care
																	================================================== -->					        
										
								  
								
																	<!-- Dimensions
																	================================================== -->					        
																    <div class="tab-pane " id="dimensions<?php echo $_product->getId() ?>">
																		 <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getsize_and_fit()), 'size_and_fit') ?></div>
								
																    </div>
								
																    <!-- Emd: Dimensions
																	================================================== -->					        
															    
															    </div>
															</div>		        		              						 									
												        </div>					
													    <!-- End: Tabs Content
														================================================== -->					        							    							    
														
														
														<script>
														$(function () {
														    $('#myTab<?php echo $_product->getId() ?> a:last').tab('show');
														  });
														
														
														$('a[data-toggle="tab"]').on('shown', function (e) {
														  e.target // activated tab
														  e.relatedTarget // previous tab
														});
														</script>
								
								                    </div>
								                    				
													<!-- End: Descriptions and Dimentions Tabs Block Row
													================================================== -->					        


													<!-- Purchase Product Options
													================================================== -->					        
								                    <div class="row">
								
									                    <div class="span4" id="purchaseoptions">
										                    <?php if($_product->isSaleable()): ?>
						

		         
																	<!-- Purchase Product Options
																	================================================== -->					        
																	<p>Try and insert Colour option here.</p>

																	<!-- Purchase Product Options
																	================================================== -->					        
																	<p>Try and insert Size option here.</p>

			            
															<!-- Add to Bag
															================================================== -->					        
										                    <div class="row">

																<!-- Add to Bag
																================================================== -->					        
											                    <div class="span2">
					            									<button type="button" title="<?php echo $this->__('Add to Bag') ?>" class="btn addtobag" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Bag') ?></span></span></button>
												                    <?php else: ?>
												                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
												                    <?php endif; ?>
		
											                    </div>

																<!-- Free Shipping Advert
																================================================== -->					        
											                    <div class="span2" id="freeshipping">
					            									<a href="#" title=""><i class="icon-plane"></i>Free Shipping!</a>
		
											                    </div>
											                
											                </div>
								                    
								                    </div>

													<!-- End: Purchase Product Options
													================================================== -->					        



			    													            
									        </div>
							
											<!-- End: Product Details
											================================================== -->					        
							



						
									</div>

									<!-- End: Product Body Row
									================================================== -->			

							   	
	
		                    </div>
							
							<!-- End: QuickShop Modal
							================================================== -->					        
						</div> 

            </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </ul>
        <?php endif ?>
        <?php endforeach ?>
 
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php
        /* @var $toolbar Mage_Catalog_Block_Product_List_Toolbar */
        // get toolbars limits - overrides default pager limit
        $toolbar = Mage::getBlockSingleton('catalog/product_list_toolbar')->getAvailableLimit();

        /* @var $pager Mage_Page_Block_Html_Pager */
        $pager = $this->getLayout()->createBlock('page/html_pager', 'bootstrapped.standalone.pager');

        // set limit - uses category's instead of default pager's (10-20-50)
        $pager->setAvailableLimit($toolbar);
        // need to set collection
        $pager->setCollection($_productCollection);
        //set custom template
        $pager->setTemplate('catalog/product/list/pager.phtml');
        echo $pager->toHtml();
        ?>
    </div>
</div>
<?php endif; ?>