<style>

	.surveyTable {
		padding:7px 9px;
	}

</style>

<div class="block block-compare">
    <div class="block-title">
        <strong><span>Customer Surveys</span></strong>
    </div>
    <div class="block-content">
        
        <table class="surveyTable">
        	
            <thead>
            	<th><h6>#</h6></th><th><h6>Survey Name</h6></th><th><h6>Number of Questions</h6></th><th><h6>Promotional</h6></th>
            </thead>
            
            <?php $counter = 1; ?>

            <?php foreach($this->getSurveys() as $survey) { ?>
            
                <tr width="100%">
                        
                    <?php if($survey->enabled == 1) { ?>
                       
                          <td width="10%"><?php echo $counter; ?>.</td><td width="45%"><a href="<?php echo $this->getUrl('*/*/view/'); ?>id/<?php echo $survey->customersurvey_id; ?>"><?php echo $survey->title; ?></a></td><td width="45%">  Questions: <?php echo $this->questionsForSurvey($survey->customersurvey_id);?></td><td><?php if($survey->code == "") { echo "No"; } else { echo "Yes"; } ?></td>
                        
                    <?php } ?>
                        
                 </tr>
                     
                <?php $counter++; ?>
            <?php } ?>

        </table>
        
    </div>
</div>
