<?php $_wishlistItem = $this->getWishlistItem(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getUpdateUrl($_wishlistItem); ?>
<div class="addto-controls">
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <div class="addtowishlist">
		<a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-compare"><?php echo $this->__('Update Wishlist') ?></a>
	</div>
<?php endif; ?>
<?php $_product = $this->getProduct(); ?>
<?php //$_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product); ?>
<?php /*if ($_compareUrl) : ?>
    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
<?php endif;*/ ?>
</ul>