<?php
	// Set images
	$this->getChild('left')->setData('image', $this->getLeft());
	$this->getChild('middle1')->setData('image', $this->getMiddle1());
	$this->getChild('middle2')->setData('image', $this->getMiddle2());
	$this->getChild('right')->setData('image', $this->getRight());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('left', false) // LEFT ?></td>
		<td><?php echo $this->getChildHtml('middle1', false) // MIDDLE1 ?></td>
		<td><?php echo $this->getChildHtml('middle2', false) // MIDDLE2 ?></td>
		<td><?php echo $this->getChildHtml('right', false) // RIGHT ?></td>
	</tr>
</table>