<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('bottom')->setData('image', $this->getBottom());
	$this->getChild('bottomright1')->setData('image', $this->getBottomRight1());
	$this->getChild('bottomright2')->setData('image', $this->getBottomRight2());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td colspan="2"><?php echo $this->getChildHtml('top', false) // TOP ?></td>
	</tr>
	<tr>
		<td rowspan="2"><?php echo $this->getChildHtml('bottom', false) // BOTTOM ?></td>
		<td><?php echo $this->getChildHtml('bottomright1', false) // BOTTOMRIGHT1 ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('bottomright2', false) // BOTTOMRIGHT2 ?></td>
	</tr>
</table>