<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('bottom1')->setData('image', $this->getBottom1());
	$this->getChild('bottom2')->setData('image', $this->getBottom2());
	$this->getChild('bottom3')->setData('image', $this->getBottom3());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td colspan="3"><?php echo $this->getChildHtml('top', false) // TOP ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('bottom1', false) // BOTTOM1 ?></td>
		<td><?php echo $this->getChildHtml('bottom2', false) // BOTTOM2 ?></td>
		<td><?php echo $this->getChildHtml('bottom3', false) // BOTTOM3 ?></td>
	</tr>
</table>