<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('top')->setData('over', $this->getOverTop());
	$this->getChild('middle1')->setData('image', $this->getMiddle1());
	$this->getChild('middle1')->setData('over', $this->getOverMiddle1());
	$this->getChild('middle2')->setData('image', $this->getMiddle2());
	$this->getChild('middle2')->setData('over', $this->getOverMiddle2());
	$this->getChild('bottom')->setData('image', $this->getBottom());
	$this->getChild('bottom')->setData('over', $this->getOverBottom());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('top', false) // TOP ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('middle1', false) // MIDDLE1 ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('middle2', false) // MIDDLE2 ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('bottom', false) // BOTTOM ?></td>
	</tr>
</table>