<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('middleleft')->setData('image', $this->getMiddleleft());
	$this->getChild('middleright')->setData('image', $this->getMiddleright());
	$this->getChild('bottom')->setData('image', $this->getBottom());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td colspan="2"><?php echo $this->getChildHtml('top', false) // TOP ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('middleleft', false) // MIDDLELEFT ?></td>
		<td><?php echo $this->getChildHtml('middleright', false) // MIDDLERIGHT ?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->getChildHtml('bottom', false) // BOTTOM ?></td>
	</tr>
</table>