<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('top')->setData('over', $this->getOverTop());
	$this->getChild('bottom')->setData('image', $this->getBottom());
	$this->getChild('bottom')->setData('over', $this->getOverBottom());
	$this->getChild('topleft1')->setData('image', $this->getTopLeft1());
	$this->getChild('topleft1')->setData('over', $this->getOverTopLeft1());
	$this->getChild('topleft2')->setData('image', $this->getTopLeft2());
	$this->getChild('topleft2')->setData('over', $this->getOverTopLeft2());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('topleft1', false) // TOPLEFT1 ?></td>
		<td rowspan="2"><?php echo $this->getChildHtml('top', false) // TOP ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('topleft2', false) // TOPLEFT2 ?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->getChildHtml('bottom', false) // BOTTOM ?></td>
	</tr>
</table>