<?php
	// Set images
	$this->getChild('left')->setData('image', $this->getLeft());
	$this->getChild('left')->setData('over', $this->getOverLeft());
	$this->getChild('middle')->setData('image', $this->getMiddle());
	$this->getChild('middle')->setData('over', $this->getOverMiddle());
	$this->getChild('middleleft')->setData('image', $this->getMiddleleft());
	$this->getChild('middleleft')->setData('over', $this->getOverMiddleleft());
	$this->getChild('middleright')->setData('image', $this->getMiddleright());
	$this->getChild('middleright')->setData('over', $this->getOverMiddleright());
	$this->getChild('right')->setData('image', $this->getRight());
	$this->getChild('right')->setData('over', $this->getOverRight());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('left', false) // LEFT ?></td>
		<td><?php echo $this->getChildHtml('middleleft', false) // MIDDLELEFT ?></td>
		<td><?php echo $this->getChildHtml('middle', false) // MIDDLE ?></td>
		<td><?php echo $this->getChildHtml('middleright', false) // MIDDLERIGHT ?></td>
		<td><?php echo $this->getChildHtml('right', false) // RIGHT ?></td>
	</tr>
</table>