<?php
	// Set images
	$this->getChild('left')->setData('image', $this->getLeft());
	$this->getChild('middle')->setData('image', $this->getMiddle());
	$this->getChild('righttop')->setData('image', $this->getRighttop());
	$this->getChild('rightmiddle')->setData('image', $this->getRightmiddle());
	$this->getChild('rightbottom')->setData('image', $this->getRightbottom());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td rowspan="3"><?php echo $this->getChildHtml('left', false) // LEFT ?></td>
		<td rowspan="3"><?php echo $this->getChildHtml('middle', false) // MIDDLE ?></td>
		<td><?php echo $this->getChildHtml('righttop', false) // RIGHTTOP ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('rightmiddle', false) // RIGHTMIDDLE ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('rightbottom', false) // RIGHTBOTTOM ?></td>
	</tr>
</table>