<?php
	// Set images
	$this->getChild('left')->setData('image', $this->getLeft());
	$this->getChild('right1')->setData('image', $this->getRight1());
	$this->getChild('right2')->setData('image', $this->getRight2());
	$this->getChild('right3')->setData('image', $this->getRight3());
	$this->getChild('right4')->setData('image', $this->getRight4());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td rowspan="4"><?php echo $this->getChildHtml('left', false) // LEFT ?></td>
		<td><?php echo $this->getChildHtml('right1', false) // RIGHT1 ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('right2', false) // RIGHT2 ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('right3', false) // RIGHT3 ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('right4', false) // RIGHT4 ?></td>
	</tr>
</table>