<?php
	// Set images
	$this->getChild('bottom')->setData('image', $this->getBottom());
	$this->getChild('bottom')->setData('over', $this->getOverBottom());
	$this->getChild('middle')->setData('image', $this->getMiddle());
	$this->getChild('middle')->setData('over', $this->getOverMiddle());
	$this->getChild('topleft')->setData('image', $this->getTopleft());
	$this->getChild('topleft')->setData('over', $this->getOverTopleft());
	$this->getChild('topmiddle')->setData('image', $this->getTopmiddle());
	$this->getChild('topmiddle')->setData('over', $this->getOverTopmiddle());
	$this->getChild('topright')->setData('image', $this->getTopright());
	$this->getChild('topright')->setData('over', $this->getOverTopright());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('topleft', false) // TOPLEFT ?></td>
		<td><?php echo $this->getChildHtml('topmiddle', false) // TOPMIDDLE ?></td>
		<td><?php echo $this->getChildHtml('topright', false) // TOPRIGHT ?></td>
	</tr>
	<tr>
		<td colspan="3"><?php echo $this->getChildHtml('middle', false) // MIDDLE ?></td>
	</tr>
	<tr>
		<td colspan="3"><?php echo $this->getChildHtml('bottom', false) // BOTTOM ?></td>
	</tr>
</table>