<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('middle1')->setData('image', $this->getMiddle1());
	$this->getChild('middle2')->setData('image', $this->getMiddle2());
	$this->getChild('bottomleft')->setData('image', $this->getBottomleft());
	$this->getChild('bottomright')->setData('image', $this->getBottomright());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td colspan="2"><?php echo $this->getChildHtml('top', false) // TOP ?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->getChildHtml('middle1', false) // MIDDLE1 ?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->getChildHtml('middle2', false) // MIDDLE2 ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('bottomleft', false) // BOTTOMLEFT ?></td>
		<td><?php echo $this->getChildHtml('bottomright', false) // BOTTOMRIGHT ?></td>
	</tr>
</table>