<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('top')->setData('over', $this->getOverTop());
	$this->getChild('bottom1')->setData('image', $this->getBottom1());
	$this->getChild('bottom1')->setData('over', $this->getOverBottom1());
	$this->getChild('bottom2')->setData('image', $this->getBottom2());
	$this->getChild('bottom2')->setData('over', $this->getOverBottom2());
	$this->getChild('bottom3')->setData('image', $this->getBottom3());
	$this->getChild('bottom3')->setData('over', $this->getOverBottom3());
	$this->getChild('bottom4')->setData('image', $this->getBottom4());
	$this->getChild('bottom4')->setData('over', $this->getOverBottom4());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td colspan="4"><?php echo $this->getChildHtml('top', false) // TOP ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('bottom1', false) // BOTTOM1 ?></td>
		<td><?php echo $this->getChildHtml('bottom2', false) // BOTTOM2 ?></td>
		<td><?php echo $this->getChildHtml('bottom3', false) // BOTTOM3 ?></td>
		<td><?php echo $this->getChildHtml('bottom4', false) // BOTTOM4 ?></td>
	</tr>
</table>