<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('middle')->setData('image', $this->getMiddle());
	$this->getChild('bottomleft')->setData('image', $this->getBottomleft());
	$this->getChild('bottommiddle')->setData('image', $this->getBottommiddle());
	$this->getChild('bottomright')->setData('image', $this->getBottomright());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td colspan="3"><?php echo $this->getChildHtml('top', false) // TOP ?></td>
	</tr>
	<tr>
		<td colspan="3"><?php echo $this->getChildHtml('middle', false) // MIDDLE ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('bottomleft', false) // BOTTOMLEFT ?></td>
		<td><?php echo $this->getChildHtml('bottommiddle', false) // BOTTOMMIDDLE ?></td>
		<td><?php echo $this->getChildHtml('bottomright', false) // BOTTOMRIGHT ?></td>
	</tr>
</table>