<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('top')->setData('over', $this->getOverTop());
	$this->getChild('slider')->setData('slides', $this->getSlides());
	$this->getChild('slider')->setData('nav', $this->getSliderNav());
	$this->getChild('slider')->setData('pag', $this->getSliderPag());
	$this->getChild('slider')->setData('dir', $this->getSliderOrientation());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<?php echo $this->getChildHtml('top', false) // TOP ?>
<?php echo $this->getChildHtml('slider', false) // SLIDER ?>