<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('middletop')->setData('image', $this->getMiddletop());
	$this->getChild('middle')->setData('image', $this->getMiddle());
	$this->getChild('middlebottom')->setData('image', $this->getMiddlebottom());
	$this->getChild('bottom')->setData('image', $this->getBottom());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('top', false) // TOP ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('middletop', false) // MIDDLETOP ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('middle', false) // MIDDLE ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('middlebottom', false) // MIDDLEBOTTOM ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('bottom', false) // BOTTOM ?></td>
	</tr>
</table>