<?php
	// Set images
	$this->getChild('left1')->setData('image', $this->getLeft1());
	$this->getChild('left1')->setData('over', $this->getOverLeft1());
	$this->getChild('left2')->setData('image', $this->getLeft2());
	$this->getChild('left2')->setData('over', $this->getOverLeft2());
	$this->getChild('middle')->setData('image', $this->getMiddle());
	$this->getChild('middle')->setData('over', $this->getOverMiddle());
	$this->getChild('right1')->setData('image', $this->getRight1());
	$this->getChild('right1')->setData('over', $this->getOverRight1());
	$this->getChild('right2')->setData('image', $this->getRight2());
	$this->getChild('right2')->setData('over', $this->getOverRight2());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('left1', false) // LEFT1 ?></td>
		<td rowspan="2"><?php echo $this->getChildHtml('middle', false) // MIDDLE ?></td>
		<td><?php echo $this->getChildHtml('right1', false) // RIGHT1 ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('left2', false) // LEFT2 ?></td>
		<td><?php echo $this->getChildHtml('right2', false) // RIGHT2 ?></td>
	</tr>
</table>