<?php
	// Set images
	$this->getChild('top1')->setData('image', $this->getTop1());
	$this->getChild('top1')->setData('over', $this->getOverTop1());
	$this->getChild('top2')->setData('image', $this->getTop2());
	$this->getChild('top2')->setData('over', $this->getOverTop2());
	$this->getChild('slider')->setData('slides', $this->getSlides());
	$this->getChild('bottom')->setData('image', $this->getBottom());
	$this->getChild('bottom')->setData('over', $this->getOverBottom());
	// Set slider speed
	$this->getChild('slider')->setData('speed', $this->getSliderSpeed());
	$this->getChild('slider')->setData('nav', $this->getSliderNav());
	$this->getChild('slider')->setData('pag', $this->getSliderPag());
    $this->getChild('slider')->setData('dir', $this->getSliderOrientation());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('top1', false) // TOP1 ?></td>
		<td><?php echo $this->getChildHtml('top2', false) // TOP2 ?></td>
	</tr>
</table>
<?php echo $this->getChildHtml('slider', false) // SLIDER ?>
<?php echo $this->getChildHtml('bottom', false) // BOTTOM ?>
