<?php
	// Set images
	$this->getChild('top1')->setData('image', $this->getTop1());
	$this->getChild('top2')->setData('image', $this->getTop2());
	$this->getChild('bottom')->setData('image', $this->getBottom());
	$this->getChild('middle1')->setData('image', $this->getMiddle1());
	$this->getChild('middle2')->setData('image', $this->getMiddle2());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('top1', false) // TOP1 ?></td>
		<td><?php echo $this->getChildHtml('top2', false) // TOP2 ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('middle1', false) // MIDDLE1 ?></td>
		<td><?php echo $this->getChildHtml('middle2', false) // MIDDLE2 ?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->getChildHtml('bottom', false) // BOTTOM ?></td>
	</tr>
</table>