<?php
	// Set images
	$this->getChild('top1')->setData('image', $this->getTop1());
	$this->getChild('top2')->setData('image', $this->getTop2());
	$this->getChild('top3')->setData('image', $this->getTop3());
	$this->getChild('top4')->setData('image', $this->getTop4());
	$this->getChild('bottom')->setData('image', $this->getBottom());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('top1', false) // TOP1 ?></td>
		<td><?php echo $this->getChildHtml('top2', false) // TOP2 ?></td>
		<td><?php echo $this->getChildHtml('top3', false) // TOP3 ?></td>
		<td><?php echo $this->getChildHtml('top4', false) // TOP4 ?></td>
	</tr>
	<tr>
		<td colspan="4"><?php echo $this->getChildHtml('bottom', false) // BOTTOM ?></td>
	</tr>
</table>