<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html>
	<head>
	    <?php echo $this->getChildHtml('head') ?>
	</head>
	<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
		<?php echo $this->getChildHtml('after_body_start') ?>
		<?php echo $this->getChildHtml('global_notices') ?>
		<header class="main_header">
			<?php echo $this->getChildHtml('header') ?>
		</header>
			
		<section id="maincontent">
			<div class="container-full">
			    <div class="row main">
					<?php echo $this->getChildHtml('breadcrumbs') ?>
					<?php echo $this->getChildHtml('before_content') ?>
					<div class="col-md-12 col-lg-12 col-xs-12 col-sm-12">
						<?php echo $this->getChildHtml('global_messages') ?>
						<?php echo $this->getChildHtml('content') ?>
					</div>
			    </div>
			</div>
		</section>
		<footer class="main_footer">
		    <div class="container">
				<?php echo $this->getChildHtml('footer') ?>
			</div>
		</footer>
		<footer class="responsive_footer">
			<?php echo $this->getChildHtml('mobile_footer') ?>
		</footer>
		<?php echo $this->getChildHtml('before_body_end') ?>
		<?php echo $this->getAbsoluteFooter() ?>
	</body>
</html>
