<?php
/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 */
/** @var $this Mage_Customer_Block_Form_Register */
?>

<div class="main_wrapper checkout_wrapper">
    <div class="container">
        <?php echo $this->getChildHtml('form_fields_before')?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <header class="page_title">
            <h2><?php echo $this->__('create an account');?></h2>
        </header>
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <?php if (version_compare(Mage::getVersion(),"1.9.2.2",">=")): ?>
                <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <?php endif; ?>
            <!--<legend><?php echo $this->__('personal information') ?></legend>-->
            <div class="checkout_right">
                <div class="row">
                    <!-- render from customer/widget/name.phtml-->
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </div>
                
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <label class="chk_label"><?php echo $this->__('email address')?> <span>*</span></label>
                        <input type="text" name="email" id="email_address"
                        value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>"
                        title="<?php echo $this->__('Email Address') ?>"
                        class="input-text validate-email required-entry login_input" />
                    </div>
                </div>
                <!-- render from customer/widget/dob.phtml -->
                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                <?php if ($_dob->isEnabled()): ?>
                <div class="row">
                     <?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
                </div>
                <?php endif;?>
                
                <div class="row">
                    <!-- render from customer/widget/dob.phtml -->
                    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                    <?php if ($_taxvat->isEnabled()): ?>
                        <div class="col-md-6 col-sm-6">
                            <?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
                        </div>
                    <?php endif;?>
                    
                    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                    <?php if ($_gender->isEnabled()): ?>
                        <div class="col-md-6 col-sm-6">
                            <?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?>
                        </div>    
                    <?php endif ?>
                </div>
                
                <div class="row">
                    <div class="col-md-6 col-sm-6">
                        <label class="chk_label"><?php echo $this->__('password')?> <span>*</span></label>
                        <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password login_input" />
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <label class="chk_label"><?php echo $this->__('confirm password')?><span>*</span></label>
                        <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword login_input" />
                    </div>
                </div>
                
                
                <!-- address field -->
                 <?php if($this->getShowAddressFields()): ?>
                    <input type="hidden" name="create_address" value="1" />
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <label for="company" class="chk_label"><?php echo $this->__('company') ?></label>
                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->quoteEscape($this->__('Company')) ?>" class="login_input <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <label for="telephone" class="chk_label required">
                                <?php echo $this->__('telephone') ?>
                                <span>*</span>
                            </label>
                            <input type="tel" name="telephone" id="telephone"
                                   value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>"
                                   title="<?php echo $this->quoteEscape($this->__('Telephone')) ?>"
                                   class="login_input <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                        </div>
                    </div>
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <label for="street_1" class="chk_label required">
                                <?php echo $this->__('street address') ?>
                                <span>*</span>
                            </label>
                            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?php echo $this->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="login_input <?php echo $_streetValidationClass ?>" />
                        </div>
                    </div>
                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                    <div class="row">
                        <label for="billing:street<?php echo $_i ?>" class="chk_label"><?php echo $this->__('Street Address %s', $_i) ?></label>
                        <div class="col-md-12 col-sm-12">
                            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i - 1)) ?>" title="<?php echo $this->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="login_input <?php echo $_streetValidationClass ?>" />
                        </div>
                    </div>
                <?php endfor; ?>
                <div class="row">
                    <div class="col-md-6 col-sm-6">
                        <label for="city" class="chk_label required">
                            <?php echo $this->__('city') ?>
                            <span>*</span>
                        </label>
                        <input type="text" name="city"
                                   value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>"
                                   title="<?php echo $this->quoteEscape($this->__('City')) ?>"
                                   class="login_input <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <label for="region_id" class="chk_label required">
                            <?php echo $this->__('State/Province') ?>
                            <span>*</span>
                        </label>
                        <select id="region_id" name="region_id" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>"
                                class="selectpicker shiping_select validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="login_input <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-sm-6">
                        <label for="zip" class="required chk_label">
                            <?php echo $this->__('zip/postal code') ?>
                            <span>*</span>
                        </label>
                        <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <label for="country" class="required chk_label">
                            <?php echo $this->__('country') ?>
                            <span>*</span>
                        </label>
                        <?php echo $this->getCountryHtmlSelect() ?>
                    </div>
                </div>
                <input type="hidden" name="default_billing" value="1" />
                <input type="hidden" name="default_shipping" value="1" />
            <?php endif; ?>
                
                
                
                <?php if ($this->isNewsletterEnabled()): ?>
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="checkouter">
                                <div class="checkouter">
                                    <input type="checkbox"
                                           name="is_subscribed"
                                           title="<?php echo $this->__('Sign Up for Newsletter') ?>"
                                           value="1"
                                           <?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
                                           id="reg_post">
                                    <label for="reg_post">
                                        <span></span>
                                        <?php echo $this->__('Sign Up for Newsletter') ?>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                 <?php endif;?>
                 
                 <div class="row text-right btn_row">
                    <div class="col-md-12">
                        <button type="submit" title="<?php echo $this->__('register') ?>" class="login_btn">
                            <?php echo $this->__('register') ?>
                        </button>
                        <button type="button" onclick="javascript:window.location='<?php echo $this->helper('customer')->getLoginUrl() ?>'" class="back_btn">
                            <?php echo $this->__('back to login') ?>
                        </button>
                    </div>
                 </div>
                 
                 
        </form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    <?php if($this->getShowAddressFields()): ?>
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    <?php endif; ?>
//]]>
</script>
