<?php
// shipment not needed
//$_shipment = $this->getShipment();
$_order = $this->getOrder();
if (!$_order) return;  // for preview

$toCome = 0;
foreach ($_order->getItemsCollection() as $_item) {
    if (!$_item->isDeleted() && !$_item->getParentItemId()) {
        $toCome += $_item->getQtyOrdered() - $_item->getQtyShipped() - $_item->getQtyRefunded() - $_item->getQtyCanceled();
    }
}
//$this->addItemRender("default", "sales/order_email_items_order_default", "email/order/items/shipment/not_shipped.phtml");
//echo sprintf("toCome=%d", $toCome);
if ($toCome > 0):
    ?>
    <br>
    <h2 style="font-size:18px; font-weight:normal; margin:0;">Still To Come</h2>
    <p><?php
        echo $this->getLayout()->createBlock('cms/block')->setBlockId('shipping-message')->toHtml();
        ?></p>
    <table cellspacing="0" cellpadding="0" border="0" width="980" style="border:1px solid #EAEAEA;">
        <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Item') ?></th>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Sku') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Qty') ?></th>
        </tr>
        </thead>
        <?php
        $i=0;
        // Mage_Sales_Model_Order_Item
        //foreach($_order->getAllVisibleItems() as $_item) {
        foreach($_order->getAllItems() as $_item) {
            if ($_item->getParentItem()) {
                continue;
            }
            $toCome = $_item->getQtyOrdered() - $_item->getQtyShipped() - $_item->getQtyRefunded() - $_item->getQtyCanceled();
            if ($toCome <= 0) {
                continue;
            }
            $i++;
            ?>
            <tbody<?php echo $i%2 ? ' bgcolor="#F6F6F6"' : '' ?>>
            <?php echo $this->getItemHtml($_item); ?>
            </tbody>
            <?php
        }
        ?>
    </table>
<?php endif; ?>
