<?php if (Mage::getStoreConfigFlag('gua/general/enable')): ?>
	<!-- Google Universal Analytics Section start -->
	<script type="text/javascript">
		<?php if(Mage::getStoreConfigFlag('gua/ecommerce/enableec')): ?>
			function onPaymentComplete(formId)
			{
				var joForm = document.getElementById(formId);
				var i;
				var paymentOption = "";

				ga('require', 'ec');
				<?php try{
					$_products = Mage::getModel('core/session')->getGuaCheckout();
					foreach ($_products as $_product): ?>
						ga('ec:addProduct', {
						  'id': '<?php echo $_product->getSku() ?>',
						  'name': '<?php echo str_replace('\'','', $_product->getName()) ?>',
						  'category': '<?php echo $_product->getCategory() ?>',
						  'brand': '',
						  'variant': '',
						  'price': '<?php echo $_product->getPrice() ?>',
						  'quantity': <?php echo (int) $_product->getQty() ?>
						});
				<?php endforeach; ?>

				for (i = 0; i < joForm.elements.length; i++) {
					if (joForm.elements[i].checked)
					{
						switch (joForm.elements[i].value)
						{
							case 'paypal_express':
								paymentOption = "PayPal";
								break;
							case 'verisign':
								paymentOption = "Credit Card";
								break;
							case 'ugiftcert':
								paymentOption = "Gift Card";
								break;
							case 'free':
								paymentOption = "No Payment Option Required";
								break;
							default:
								paymentOption = joForm.elements[i].value;
								break;
						}
						break;
					}
				}
				
				ga('ec:setAction', 'checkout', {
					'step': 2,
					'option': paymentOption
				});
				ga('send', 'pageview');
				ga('send', 'event', 'Checkout', 'Payment');
				<?php
				}catch (Exception $e){
					Mage::helper('factoryx_gua')->log($e->getMessage());
				}
				?>
			}
		<?php endif; ?>
	</script>
<?php endif; ?>