<div id="myCarousel" class="carousel slide">
	<ol class="carousel-indicators">
		<?php for ($i=0;$i<count($this->getSlides());$i++): ?>
			<li data-target="#myCarousel" data-slide-to="<?php echo $i ?>" <?php if ($i==0): ?>class="active"<?php endif; ?>></li>
		<?php endfor; ?>
	</ol>
	<div class="carousel-inner">
		<?php 
		$relMediaPath = substr(Mage::getBaseDir('media'), strlen(Mage::getBaseDir()) );
		$slideHeight = "";
		$i = 0;
		// Loop through images
		foreach($this->getSlides() as $slide)
		{
			// Generate URL
			$imagePath = sprintf("%s/homepage%s", Mage::getBaseDir('media'), $slide->getUrl());
			$imageUrl = sprintf("%s/homepage%s", $relMediaPath, $slide->getUrl());
			// Test if image exists
			if (is_file($imagePath)) {
				// List its attribute
				list($width, $height, $type, $attr) = getimagesize($imagePath); 
				// If the slide height is not set we set it
				if ($slideHeight == "") $slideHeight = $height; ?>
				<div class="<?php if ($i==0): ?>active<?php endif;?> item">
					<?php if ($link = $slide->getLink()): ?>
						<a <?php if ($slide->getPopup()): ?>target="_blank" <?php endif; ?>href="<?php echo $link ?>">
					<?php endif; ?>
						<img <?php echo $attr; ?> src="<?php echo $imageUrl ?>" alt="<?php echo $slide->getAlt(); ?>" /> 
					<?php if ($link): ?>
						</a>
					<?php endif; ?> 
				</div>
				<?php } // endif
				$i++;
				?>
		<?php } // endforeach ?>
	</div>
</div>