<?php
	// Set images
	$this->getChild('left')->setData('image', $this->getLeft());
	$this->getChild('left')->setData('over', $this->getOverLeft());
	$this->getChild('middle')->setData('image', $this->getMiddle());
	$this->getChild('middle')->setData('over', $this->getOverMiddle());
	$this->getChild('righttop')->setData('image', $this->getRighttop());
	$this->getChild('righttop')->setData('over', $this->getOverRighttop());
	$this->getChild('rightmiddle')->setData('image', $this->getRightmiddle());
	$this->getChild('rightmiddle')->setData('over', $this->getOverRightmiddle());
	$this->getChild('rightbottom')->setData('image', $this->getRightbottom());
	$this->getChild('rightbottom')->setData('over', $this->getOverRightbottom());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('left', false) // LEFT ?>
</div>
<div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('middle', false) // MIDDLE ?>
</div>
<div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
    <div class="rowspan3"><?php echo $this->getChildHtml('righttop', false) // RIGHTTOP ?></div>
	<div class="rowspan3"><?php echo $this->getChildHtml('rightmiddle', false) // RIGHTMIDDLE ?></div>
	<div class="rowspan3"><?php echo $this->getChildHtml('rightbottom', false) // RIGHTBOTTOM ?></div>
</div>