<?php
	// Set images
	$this->getChild('bottom')->setData('image', $this->getBottom());
	$this->getChild('bottom')->setData('over', $this->getOverBottom());
	$this->getChild('middle')->setData('image', $this->getMiddle());
	$this->getChild('middle')->setData('over', $this->getOverMiddle());
	$this->getChild('topleft')->setData('image', $this->getTopleft());
	$this->getChild('topleft')->setData('over', $this->getOverTopleft());
	$this->getChild('topmiddle')->setData('image', $this->getTopmiddle());
	$this->getChild('topmiddle')->setData('over', $this->getOverTopmiddle());
	$this->getChild('topright')->setData('image', $this->getTopright());
	$this->getChild('topright')->setData('over', $this->getOverTopright());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('topleft', false) // TOPLEFT ?>
</div>
<div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('topmiddle', false) // TOPMIDDLE ?>
</div>
<div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('topright', false) // TOPRIGHT ?>
</div>
<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('middle', false) // MIDDLE ?>
</div>
<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('bottom', false) // BOTTOM ?>
</div>