<?php
	// Set images
	$this->getChild('left1')->setData('image', $this->getLeft1());
	$this->getChild('left1')->setData('over', $this->getOverLeft1());
	$this->getChild('left2')->setData('image', $this->getLeft2());
	$this->getChild('left2')->setData('over', $this->getOverLeft2());
	$this->getChild('middle')->setData('image', $this->getMiddle());
	$this->getChild('middle')->setData('over', $this->getOverMiddle());
	$this->getChild('right1')->setData('image', $this->getRight1());
	$this->getChild('right1')->setData('over', $this->getOverRight1());
	$this->getChild('right2')->setData('image', $this->getRight2());
	$this->getChild('right2')->setData('over', $this->getOverRight2());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
    <div><?php echo $this->getChildHtml('left1', false) // LEFT1 ?></div>
    <div><?php echo $this->getChildHtml('left2', false) // LEFT2 ?></div>
</div>
<div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('middle', false) // MIDDLE ?>
</div>
<div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
    <div class="rowspan2"><?php echo $this->getChildHtml('right1', false) // RIGHT1 ?></div>
	<div class="rowspan2"><?php echo $this->getChildHtml('right2', false) // RIGHT2 ?></div>
</div>