<?php
	// Set images
	$this->getChild('top1')->setData('image', $this->getTop1());
	$this->getChild('top1')->setData('over', $this->getOverTop1());
	$this->getChild('top2')->setData('image', $this->getTop2());
	$this->getChild('top2')->setData('over', $this->getOverTop2());
	$this->getChild('slider')->setData('slides', $this->getSlides());
	// Set slider speed
	$this->getChild('slider')->setData('speed', $this->getSliderSpeed());
	$this->getChild('slider')->setData('nav', $this->getSliderNav());
	$this->getChild('slider')->setData('pag', $this->getSliderPag());
    $this->getChild('slider')->setData('dir', $this->getSliderOrientation());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('top1', false) // TOP1 ?>
</div>
<div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('top2', false) // TOP2 ?>
</div>
<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('slider', false) // SLIDER ?>
</div>