<?php
	//echo 'arijit 1<pre>'; print_r($this->getTop()); echo '</pre>';
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('top')->setData('over', $this->getOverTop());
	$this->getChild('bottom1')->setData('image', $this->getBottom1());
	$this->getChild('bottom1')->setData('over', $this->getOverBottom1());
	$this->getChild('bottom2')->setData('image', $this->getBottom2());
	$this->getChild('bottom2')->setData('over', $this->getOverBottom2());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<div class="banner">
	<?php echo $this->getChildHtml('top', true) // TOP ?>
</div>
<div class="container">
	<div class="featured_home_product">
		<div class="featured_prudct_col">
			<?php echo $this->getChildHtml('bottom1', false) // BOTTOM1 ?>
		</div>
		<div class="featured_prudct_col">
			<?php echo $this->getChildHtml('bottom1', false) // BOTTOM1 ?>
		</div>
	</div>
</div>	