<?php
	// Set images
	$this->getChild('left1')->setData('image', $this->getLeft1());
	$this->getChild('left1')->setData('over', $this->getOverLeft1());
	$this->getChild('left2')->setData('image', $this->getLeft2());
	$this->getChild('left2')->setData('over', $this->getOverLeft2());
	$this->getChild('right')->setData('image', $this->getRight());
	$this->getChild('right')->setData('over', $this->getOverRight());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
    <div class="rowspan2"><?php echo $this->getChildHtml('left1', false) // LEFT1 ?></div>
    <div class="rowspan2"><?php echo $this->getChildHtml('left2', false) // LEFT2 ?></div>
</div>
<div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('right', false) // RIGHT ?>
</div>