<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Update Bag'); ?>
<?php if ($_product->isSaleable()): ?>
	<div class="addtocart-qty">
		<span class="addtocart-qty-label">Quantity:</span>
		<span class="addtocart-qty-value">
			<input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
		</span>
	</div>
	<div class="addtocart-controls"> 
		<button type="button" title="<?php echo $this->__($buttonTitle) ?>" class="btn-update-cart" onclick="productAddToCartForm.submit(this)">
			
				<span>
					<?php echo $this->__($buttonTitle) ?>
				</span>
			
		</button>
    </div>
	<?php echo $this->getChildHtml('', true, true) ?>
<?php endif; ?>
