<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
/* @var $this Mage_Catalog_Block_Product_List_Toolbar */
?>

<?php if($this->getCollection()->getSize()): ?>

	<div id="FilterOptions" class="toolbar-item-group-layout filter-options">				
		<div id="btnShowFilterOptions" class="btn-filter-options">
			<label>Filter Options</label>
			<span class="icon-caret-down"></span>
			<img class="icon-filter" src="<?php echo $this->getSkinUrl('images/core/filter-icon.png'); ?>" alt="filter options" />
		</div>						
	</div>

	<div id="FilterSort" class="toolbar-item-group-layout">					
		<label>Sort by</label>
		<select class="select-sort" onchange="setLocation(this.value)">
		 <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
			<option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
				<?php echo $this->__($_order) ?>
			</option>
		<?php endforeach; ?>
		</select>
		<span class="icon-caret-down"></span>
		<?php if($this->getCurrentDirection() == 'desc'): ?>
			<a class="sort-order" href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>">							
				<img src="/skin/frontend/default/princess/images/core/icon-arrow-a-d.png" alt="ascending" title="ascending" width="20">
			</a>
		<?php else: ?>
			<a class="sort-order" href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>">														
				<img src="/skin/frontend/default/princess/images/core/icon-arrow-a-u.png" alt="descending" title="descending" width="20">
			</a>
		<?php endif; ?>
		
	</div>

	<div id="FilterView" class="toolbar-item-group-layout">					
		<label>View</label>                                                              
		<ul>
		<?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
			<li <?php if($this->isLimitCurrent($_key)): ?> class="active" <?php else: ?> class="" <?php endif ?>>
				<a href="<?php echo $this->getLimitUrl($_key) ?>" <?php if($this->isLimitCurrent($_key)): ?> <?php endif ?>><?php echo $_limit ?> 
					<?php /* echo $this->__('per page') */ ?>
				</a>                        
			</li>                            
		<?php endforeach; ?>
		</ul>
	</div>    
	
	<div id="FilterOptionsMobile" class="toolbar-item-group-layout filter-options">
		<div id="btnMobileShowFilterOptions" class="btn-filter-options">
			<label>Filter Options</label>
			<span class="icon-caret-down"></span>
			<img class="icon-filter" src="<?php echo $this->getSkinUrl('images/core/filter-icon.png'); ?>" alt="filter options" />
		</div>						
	</div>

	<div id="gridoptions">
		<i class="icon-th"></i>
	</div>
           
<?php endif ?>	

<script type="text/javascript">
    jQuery(document).ready(function() {   
        // Filter option panel
        jQuery('.btn-filter-options').on('click', function() {
            $FilterOptionClass = jQuery('.btn-filter-options span').attr('class');
        
            if ('icon-caret-down' == $FilterOptionClass) {
                jQuery('.filter-options').removeClass('filteroptions-background');
                jQuery('.filter-options').addClass('filteroptions-background-active');           
            } else {
                jQuery('.filter-options').removeClass('filteroptions-background-active');
                jQuery('.filter-options').addClass('filteroptions-background');                           
            }
        }); 

        // Sort by:
        jQuery(".dropdown-menu li a").click(function(){
            jQuery(".btn-dropdown-extra-long").text(jQuery(this).text());
            jQuery(".btn-dropdown-extra-long").val(jQuery(this).text());
        });
        function getUrlVar(key){
            var result = new RegExp(key + "=([^&]*)", "i").exec(window.location.search);
            if (result == null){
                return 'Select';
            } else {
                return result && unescape(result[1]) || "";
            }
        }
        jQuery(".btn-dropdown-extra-long").text(getUrlVar('order'));
        
    });
</script>