<?php if(count($this->getItemCollection()->getItems())): ?>


<!-- Upsell Products - princesshighway Wear It With
================================================== -->					        
    <!-- We are going to hide the title. -->
    <!-- <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2> -->

    <?php $this->setColumnCount(4); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
   	<?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
 
<!-- Setup for grid - set to only show four items. -->
				
		        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
		            <?php if($_link=$this->getIterableItem()): ?>
		            	<?php $imageW='140px'; ?>
                        <?php $imageH='200px'; ?>
		            	<div class="span2 item">
		            	<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image">
 							<?php /*  <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image') ?>" width="160px" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /> */ ?>
							  <img  src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize($imageW, $imageH); ?>" 
									alt="<?php echo $this->stripTags($_link->getName(), null, true) ?>" width="<?php echo $imageW; ?>" height="<?php echo $imageH; ?>" />							  
						</a>
		                <h3 class="product-name">
							<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a>
						</h3>
		                <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
		                
		                <!-- Disable Review Links underneath upsell products -->
		                <!--<?php echo $this->getReviewsSummaryHtml($_link) ?>-->
		            	</div>
	            
		            <?php else: ?>
		            <?php endif; ?>
		        <?php endfor; ?>

       



<!-- Setup for when get working with nav slider

		<div id="myCarousel" class="carousel slide">
		<div class="carousel-inner">
				<ul>
				<div class="item">		
		        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
		            <?php if($_link=$this->getIterableItem()): ?>
		            
		            	
		            	<li class="product-grid">
		            	<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image') ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
		                <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h3>
		                <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
		                <?php echo $this->getReviewsSummaryHtml($_link) ?>
		            	</li>
		            	
	            
		            <?php else: ?>
		            <?php endif; ?>
		        <?php endfor; ?>
		        </div>
		        </ul>
        </div>
        
        <!--  Carousel nav 
		<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>

		</div>
		<!-- Carousel nav --> 



    <?php endfor; ?>
<?php endif ?>


