<?php if(count($this->getItemCollection()->getItems())): ?>
    <?php $this->setColumnCount(4); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
   	<?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
				<!-- Setup for grid - set to only show four items. -->
				<?php $imageW='140'; ?>
				<?php $imageH='200'; ?>
		        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
		            <?php if($_link=$this->getIterableItem()): ?>
		            	<div class="span2 item">
		            	<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image">
							  <img  src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize($imageW, $imageH); ?>" 
									alt="<?php echo $this->stripTags($_link->getName(), null, true) ?>" width="<?php echo $imageW; ?>" height="<?php echo $imageH; ?>" />							  
						</a>
		                <h3 class="product-name">
							<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a>
						</h3>
		                <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
		            	</div>
	            
		            <?php else: ?>
		            <?php endif; ?>
		        <?php endfor; ?>
    <?php endfor; ?>
<?php endif ?>


