<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('reviewnotification')->__('Review Notification') ?></h4>
    </div>
    <fieldset>
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label><?php echo $this->__('Notified'); ?></label></td>
                <td class="value"><?php echo $this->__(($this->getOrder()->geteasyreview_notified() == 1 ? 'Yes' : 'No')); ?></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo $this->__('Notification date'); ?></label></td>
                <td class="value"><?php echo $this->getOrder()->geteasyreview_date(); ?></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo $this->__('Send email'); ?></label></td>
                <td class="value"><a href="<?php echo $this->getSendEmailUrl(); ?>"><?php echo $this->__('Send'); ?></a></td>
            </tr>
            <tr>
                <td class="label"><label><?php echo $this->__('Automatic link'); ?></label></td>
                <td class="value"><a href="<?php echo $this->getDirectUrl($this->getOrder()->getId()); ?>" target="_blank" rel="noopener noreferrer"><?php echo $this->__('Test link'); ?></a></td>
            </tr>
        </table>
    </fieldset>
</div>