    <div class="main_wrapper cateer_wrapper">
        <div class="container">
            <div class="subscribe_pop_table">
                <div class="subscribe_pop_tr">
                    <div class="subscribe_left_img">
                        <!-- render from static blocks[subscribe_left_img] in amdin -->
                        <?php echo ($this->getLayout()->createBlock('cms/block')->setBlockId('subscribe_popup_left_image')->toHtml()); ?>
                    </div>
                    <div class="subscribe_right">
                        <!-- render from static blocks[newsletter_popup] in amdin  subs_input -->
                        <?php echo ($this->getLayout()->createBlock('cms/block')->setBlockId('newsletter_popup_content')->toHtml()); ?>
                        <form action="<?php echo $this->getUrl('*/*/new') ?>" method="post" id="newsletter-validate-detail">
                            <div class="subscribe_form">                                        
                                <input type="text" name="email" id="email_address"
                                       value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>"
                                       title="<?php echo $this->__('Email Address') ?>"
                                       class="input-text validate-email required-entry subs_input" />
                                <button type="submit" title="<?php echo $this->__('Subscribe') ?>"
                                        class="subs_button" name="newsletter_submit">
                                    <?php echo $this->__('subscribe') ?>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<script type="text/javascript">
   var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
</script>