<?php
/** @var FactoryX_NotificationBoard_Block_Notification $this */
/** @var FactoryX_NotificationBoard_Model_Resource_Notification_Collection $notifications */
$notifications = $this->getNotifications();
/** @var FactoryX_NotificationBoard_Model_Notification $notification */
foreach($notifications as $notification): ?>
    <?php echo $this->escapeHtml($notification->getMessage()) ?>
<?php endforeach; ?>