<h2><?php echo $this->__('Write your reviews for order #%s', $this->getOrder()->getincrement_id()) ?></h2>

<script type="text/javascript">
    var notesCount = 5;
    var notesIds = new Array();
    <?php foreach ($this->getRatings() as $_rating): ?>
        notesIds[notesIds.length] = <?php echo $_rating->getId() ?>;
    <?php endforeach; ?>
    var productIds = new Array();
    <?php foreach ($this->getProducts() as $product): ?>
        productIds[productIds.length] = <?php echo $product->getId() ?>;
    <?php endforeach; ?>

    var fillFieldsMessage = '<?php echo $this->__('Please fill all fields'); ?>';
    var fillNotesMessage = '<?php echo $this->__('Please fill all notes'); ?>';

</script>

<form action="<?php echo $this->getAction() ?>" method="post" id="review-form">
    <input type="hidden" name="order_id" id="order_id" value="<?php echo $this->getOrder()->getId(); ?>" />
    <fieldset>
        <?php foreach ($this->getProducts() as $product): ?>
            <div class="col-md-4 col-lg-4 col-sm-4 col-xs-12 text-center">
                <img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image'); ?>" class="img-responsive center-block" />
                <p><?php echo $product->getName(); ?></p>
            </div>
            <div class="col-md-8 col-lg-8 col-sm-8 col-xs-12">
                <span id="input-message-box"></span>
                <div class="table-responsive">
                    <table class="table table-hover data-table" id="product-review-table">
                        <thead>
                            <tr>
                                <th>&nbsp;</th>
                                <?php if (Mage::helper('framework')->isFaEnabled()):?>
                                    <th class="text-center"><div><i class="fa fa-star"></i></div></th>
                                    <th class="text-center"><div><i class="fa fa-star"></i><i class="fa fa-star"></i></div></th>
                                    <th class="text-center"><div><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div></th>
                                    <th class="text-center"><div><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div></th>
                                    <th class="text-center"><div><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div></th>
                                <?php else: ?>
                                    <th><span class="nobr"><?php echo $this->__('1 star') ?></span></th>
                                    <th><span class="nobr"><?php echo $this->__('2 stars') ?></span></th>
                                    <th><span class="nobr"><?php echo $this->__('3 stars') ?></span></th>
                                    <th><span class="nobr"><?php echo $this->__('4 stars') ?></span></th>
                                    <th><span class="nobr"><?php echo $this->__('5 stars') ?></span></th>
                                <?php endif; ?>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->getRatings() as $_rating): ?>
                            <tr>
                                <th><?php echo $this->escapeHtml($_rating->getRatingCode()) ?></th>
                            <?php foreach ($_rating->getOptions() as $_option): ?>
                                <td class="text-center vakye"><div class="radio"><label><input type="radio" name="ratings[<?php echo $product->getId(); ?>][notes][<?php echo $_rating->getId() ?>]" id="ratings[<?php echo $product->getId(); ?>][notes][<?php echo $_rating->getId() ?>][<?php echo $_option->getValue() ?>]" value="<?php echo $_option->getId() ?>" class="radio" /></label></div></td>
                            <?php endforeach; ?>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>

                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                <script type="text/javascript">decorateTable('product-review-table')</script>

                <div class="form-group">
                    <input type="text" name="ratings[<?php echo $product->getId(); ?>][title]" id="ratings[<?php echo $product->getId(); ?>][title]" class="form-control input-text required-entry" title="<?php echo $this->__('Summary of Your Review') ?>" placeholder="<?php echo $this->__('Summary of Your Review') ?>" value="" />
                </div>
                <div class="form-group">
                    <textarea placeholder="<?php echo $this->__('Review') ?>" title="<?php echo $this->__('Review') ?>" name="ratings[<?php echo $product->getId(); ?>][detail]" id="ratings[<?php echo $product->getId(); ?>][detail]" cols="5" rows="3" class="form-control required-entry"></textarea>
                </div>
            </div>
        <?php endforeach; ?>
    </fieldset>
    <div class="buttons-set">
        <button onclick="submitReviews();" type="button" title="<?php echo $this->__('Submit Review') ?>" class="btn btn-primary pull-right button"><span><span><?php echo $this->__('Submit Review') ?></span></span></button>
    </div>
</form>