<script type="text/javascript">
    //<![CDATA[
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    var lastPrice;
    //]]>
</script>
<form action="" id="co-payment-form">
    <fieldset>
        <?php echo $this->getChildHtml('methods') ?>
    </fieldset>
</form>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><button class="btn btn-primary" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-times"></i><?php else: echo $this->__('Close'); endif; ?></button></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>
<div>
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
</div>
<div class="buttons-set" id="payment-buttons-container">
    <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
    <div class="col-md-6 col-sm-6 col-lg-6 col-xs-12">
        <button type="button" class="btn btn-primary pull-right button" onclick="<?php if(Mage::getStoreConfigFlag('gua/ecommerce/enableec')): ?>onPaymentComplete('co-payment-form');<?php endif; ?>payment.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="payment-please-wait" style="display:none;">
            <?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-spinner fa-pulse"></i><?php else: ?><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /><?php endif; ?> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
    <?php echo $this->getChildHtml('factoryx_gua_event_checkout_onepage_payment'); ?>
</div>
<script type="text/javascript">
    //<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-560)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            });
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    //]]>
</script>
<script type="text/javascript">
    //<![CDATA[
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
    //]]>
</script>
