<form id="co-shipping-method-form" action="">
    <div id="checkout-shipping-method-load">
       <!-- Content loaded dynamically -->
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
    //]]>
    </script>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
    <div class="buttons-set" id="shipping-method-buttons-container">
        <div class="col-md-6 col-lg-6 col-sm-6 col-xs-12">
            <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        </div>
        <div class="col-md-6 col-lg-6 col-sm-6 col-xs-12">
            <button type="button" class="btn btn-primary pull-right button" onclick="<?php if(Mage::getStoreConfigFlag('gua/ecommerce/enableec')): ?>onShippingComplete('co-shipping-method-form');<?php endif; ?>shippingMethod.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
                <?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-spinner fa-pulse"></i><?php else: ?><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle img-responsive" /><?php endif; ?> <?php echo $this->__('Loading next step...') ?>
            </span>
        </div>
    </div>
	<?php echo $this->getChildHtml('factoryx_gua_event_checkout_onepage_shipping'); ?>
</form>
