<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('top')->setData('over', $this->getOverTop());
	$this->getChild('bottom')->setData('image', $this->getBottom());
	$this->getChild('bottom')->setData('over', $this->getOverBottom());
	$this->getChild('bottomright1')->setData('image', $this->getBottomRight1());
	$this->getChild('bottomright1')->setData('over', $this->getOverBottomRight1());
	$this->getChild('bottomright2')->setData('image', $this->getBottomRight2());
	$this->getChild('bottomright2')->setData('over', $this->getOverBottomRight2());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('top', false) // TOP ?>
</div>
<div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('bottom', false) // BOTTOM ?>
</div>
<div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
    <div class="rowspan2"><?php echo $this->getChildHtml('bottomright1', false) // BOTTOMRIGHT1 ?></div>
	<div class="rowspan2"><?php echo $this->getChildHtml('bottomright2', false) // BOTTOMRIGHT2 ?></div>
</div>