<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('top')->setData('over', $this->getOverTop());
	$this->getChild('bottom')->setData('image', $this->getBottom());
	$this->getChild('bottom')->setData('over', $this->getOverBottom());
	$this->getChild('topleft1')->setData('image', $this->getTopLeft1());
	$this->getChild('topleft1')->setData('over', $this->getOverTopLeft1());
	$this->getChild('topleft2')->setData('image', $this->getTopLeft2());
	$this->getChild('topleft2')->setData('over', $this->getOverTopLeft2());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
    <div class="rowspan2"><?php echo $this->getChildHtml('topleft1', false) // TOPLEFT1 ?></div>
    <div class="rowspan2"><?php echo $this->getChildHtml('topleft2', false) // TOPLEFT2 ?></div>
</div>
<div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('top', false) // TOP ?>
</div>
<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
    <?php echo $this->getChildHtml('bottom', false) // BOTTOM ?>
</div>