    <div class="discount">
        <h2><?php echo $this->__('Discount Codes') ?></h2>
    </div>
<form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post" class="form-inline">
            <p class="description"><?php echo $this->__('Enter your coupon code if you have one.') ?></p>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
			<fieldset>    
				<div class="control-group">
					<label class="control-label required" for="coupon_code"><?php echo $this->__('Coupon Code') ?></label>
					<div class="controls">
						<input  id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
					</div>
				</div>
			</fieldset>    
            <?php if(strlen($this->getCouponCode())): ?>
                <button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="btn couponbutton" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"><span><span><?php echo $this->__('Cancel Coupon') ?></span></span></button>
			<?php else: ?>
				<button type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="btn couponbutton" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
            <?php endif;?>

</form>
<script type="text/javascript">
//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>
</script>
