<?php
/**

 */
$user = Mage::getSingleton('admin/session');
$userId = $user->getUser()->getUserId();
$userName = $user->getUser()->getName();
$showAllStores = false;

if (Mage::helper('shippedfrom')->isShowAllStores()) {
    $showAllStores = true;
}
else {
    $userStoreId = $user->getUser()->getStore();
    // only show all stores is user has no store
    if (empty($userStoreId)) {
        $showAllStores = true;
    }
    else{
        $userStoreName = Mage::getModel('ustorelocator/location')->load($userStoreId)->getTitle();
    }
}
?>
<form id="edit_form" method="post" action="<?php echo $this->getSaveUrl() ?>">
    <?php echo $this->getBlockHtml('formkey')?>
    <?php  $_order = $this->getShipment()->getOrder() ?>
    <?php echo $this->getChildHtml('order_info') ?>

    <div class="box-left">
        <!--Billing Address-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Payment Information') ?></h4>
            </div>
            <fieldset>
                <div><?php echo $this->getPaymentHtml() ?></div>
                <div><?php echo Mage::helper('sales')->__('The order was placed using %s', $_order->getOrderCurrencyCode()) ?></div>
            </fieldset>
        </div>
    </div>
    <div class="box-right">
        <!--Shipping Address-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('sales')->__('Shipping Information') ?></h4>
            </div>
            <fieldset>
                <div>
                    <table cellspacing="0" class="form-list">
                    <colgroup class="label"></colgroup>
                    <colgroup class="value"></colgroup>
                    <tbody>
                    <tr id="row_shipment_customer">
                        <td class="label"><label for="shipment_shipped_from">Customer Selection</label></td>
                        <td class="value">
                            <strong><?php echo $_order->getShippingDescription() ?></strong>
                            <?php echo $this->helper('sales')->__('Total Shipping Charges'); ?>:

                            <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                                <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                            <?php else: ?>
                                <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                            <?php endif; ?>
                            <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>

                            <?php echo $_excl; ?>
                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr id="row_shipment_shipped_from">
                        <td class="label"><label for="shipment_shipped_from">Shipped From</label></td>
                        <td class="value">
                            <?php // echo sprintf("showAllStores=%d", $showAllStores); ?>
                            <select name="shipment[shipped_from]" id="shipment[shipped_from]" class="select">
                                <?php
                                if ($showAllStores) {
                                    $stores = Mage::helper('shippedfrom')->getStores($useShortTitle = true);
                                    foreach($stores as $storeId => $store) {
                                        //Mage::helper('shippedfrom')->log(sprintf("store=%s", print_r($store, true)));
                                        //$store = sprintf("%s - %s %s", $store['code'], $store['region'], $store['title']);
                                        echo sprintf("<option value='%d'%s>%s</option>", $storeId, (preg_match("/default/i", $store)?" selected":""), $store);
                                    }
                                }
                                else {
                                    echo sprintf("<option value='%d'%s>%s</option>", $userStoreId, " selected", $userStoreName);
                                }
                                ?>
                            </select>
                            <div style='float:right; text-align:right;'>
                                &nbsp;Send to Store <input id="send_store_email" type="checkbox" value="1" name="shipment[send_store_email]"
                                    <?php echo (Mage::helper('shippedfrom')->isCheckSendStoreEmail()) ? "checked" : ""; ?>>
                            </div>
                        </td>
                    </tr>
                    <tr id="row_shipment_shipped_by">
                        <td class="label"><label for="shipment_shipped_by">Shipped By</label></td>
                        <td class="value">
                            <select name="shipment[shipped_by]" id="shipment[shipped_by]" class="select">
                                <?php
                                $field = Mage::helper('shippedfrom')->getShippedByUserField();
                                $userValue = $userName;
                                if (preg_match("/user_id/i", $field)) {
                                    $userValue = $userId;
                                }
                                elseif (preg_match("/username/i", $field)) {
                                    $userValue = $user->getUser()->getUsername();
                                }
                                echo sprintf("<option value='%s'%s>%s</option>", $userValue, " selected", $userName);

                                /*
                                $currUserId = Mage::getSingleton('admin/session')->getUser()->getId();
                                // only show current users with privillages
                                $users = Mage::getModel('admin/roles')->getUsersCollection();
                                // Mage_Admin_Model_User
                                foreach($users as $user) {
                                    $userId = $user->getId();
                                    $userName = $user->getName();
                                    $roleData = Mage::getModel('admin/user')->load($userId)->getRole()->getData();
                                    //$userName = sprintf("%s (%s)", $userName, $roleData['role_name']);
                                    if (preg_match("/(manager|admin)/i", $roleData['role_name'])) {
                                        echo sprintf("<option value='%s'%s>%s</option>", $userName, ($userId == $currUserId?" selected":""), $userName);
                                    }
                                }

                                $users = Mage::helper('shippedfrom')->getUsers();
                                foreach($users as $userId => $userName) {
                                    echo sprintf("<option value='%s'%s>%s</option>", $userName, ($userId == $currUserId?" selected":""), $userName);
                                }
                                */
                                ?>
                            </select>
                        </td>
                    </tr>

                    <tr id="row_shipment_shipped_selected">
                        <td class="label" colspan="2">
                            <div><?php echo $this->getChildHtml('shipment_tracking') ?></div>
                        </td>
                    </tr>
                    </tbody></table>
                </div>
            </fieldset>
        </div>
    </div>
    <!--
    <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Assign To Store For Shipping') ?></h4>
            </div>
            <fieldset>
            <label>Store:</label>
            <select name="shipment[shipped_from]" id="shipment[shipped_from]" class="select carrier" style="width:110px;">
            <option value=""></option>
                <?php
                /*
                    $stores = Mage::getModel('ustorelocator/location')->getCollection();
                    foreach($stores as $store){
                ?>
                        <option value="<?php echo $store->getId();?>"> <?php echo $store->getTitle();?></option>
                <?php
                }
                */
                ?>
                </select>
            </fieldset>
        </div>
    </div>
    -->
    <div class="clear"></div>

    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Items to Ship') ?></h4>
        </div>
    </div>

    <div id="ship_items_container">
            <?php echo $this->getItemsHtml() ?>
    </div>
    </div>


</form>
<?php echo $this->getChildHtml('shipment_packaging') ?>
<script type="text/javascript">
//<![CDATA[
    document.observe("dom:loaded", function() {
        setTimeout(function(){
            packaging.setConfirmPackagingCallback(function(){
                packaging.setParamsCreateLabelRequest($('edit_form').serialize(true));
                packaging.sendCreateLabelRequest();
            });
            packaging.setLabelCreatedCallback(function(response){
                setLocation("<?php echo $this->getUrl(
                    '*/sales_order/view',
                    array('order_id' => $this->getShipment()->getOrderId())
                ); ?>");
            });
            packaging.setCancelCallback(function() {
                packaging.cleanPackages();
                $('create_shipping_label').checked = false;
                toggleCreateLabelCheckbox();
            });
            packaging.setItemQtyCallback(function(itemId){
                var item = $$('[name="shipment[items]['+itemId+']"]')[0];
                if (item && !isNaN(item.value)) {
                    return item.value;
                }
            });
        }, 500);
    });

    editForm = new varienForm('edit_form');
//]]>
</script>
