<?php
/**
 * @see Mage_Checkout_Block_Cart_Shipping
 */
?>
<div class="shipping">
    <h2><?php echo $this->__('Estimate Shipping and Tax') ?></h2>
    <div class="shipping-form">
       <form action="<?php echo $this->getUrl('checkout/cart/estimatePost') ?>" method="post" id="shipping-zip-form" class="form">
		   <p class="description"><?php echo $this->__('Enter your destination to get a shipping estimate.') ?></p>
           <fieldset>            
                <div class="control-group">
                    <label class="control-label required" for="country"><?php echo $this->__('Country') ?><em>*</em></label>
                    <div class="controls">
                        <span class="icon-caret-down"></span>
						<?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getEstimateCountryId()) ?>						
                    </div>
                </div>
            <?php if($this->getCityActive()): ?>
                <div class="control-group">
                    <label class="control-label" for="city"<?php if ($this->isCityRequired()) echo ' class="required"' ?>><?php if ($this->isCityRequired()) echo '<em>*</em>' ?><?php echo $this->__('City') ?></label>
                    <div class="controls">
                        <input class="input-text<?php if ($this->isCityRequired()):?> required-entry<?php endif;?>" id="city" type="text" name="estimate_city" value="<?php echo $this->htmlEscape($this->getEstimateCity()) ?>" />
                    </div>
                </div>
            <?php endif; ?>
                <div class="control-group">
                    <label class="control-label" for="postcode"<?php if ($this->isZipCodeRequired()) echo ' class="required"' ?>><?php if ($this->isZipCodeRequired()) echo '<em>*</em>' ?><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="controls">
                        <input class="input-text validate-postcode<?php if ($this->isZipCodeRequired()):?> required-entry<?php endif;?>" type="text" id="postcode" name="estimate_postcode" value="<?php echo $this->htmlEscape($this->getEstimatePostcode()) ?>" />
                    </div>
                </div>            
				<div class="control-group">
					<button type="button" title="<?php echo $this->__('Get a Quote') ?>" onclick="coShippingMethodForm.submit()" class="btn shippingbutton"><span><span><?php echo $this->__('Get a Quote') ?></span></span></button>
				</div>
            </fieldset>
		   <p class="help-block"><?php echo $this->__('* Required Fields') ?></p>
        </form>

        <?php if (($_shippingRateGroups = $this->getEstimateRates())): ?>
        <form id="co-shipping-method-form" action="<?php echo $this->getUrl('checkout/cart/estimateUpdatePost') ?>" class="form-horizontal">

            
                <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
					<fieldset class="shipping-results">
						<legend><?php echo $this->getCarrierName($code) ?></legend>                    
                        <?php foreach ($_rates as $_rate): ?>
                               <?php if ($_rate->getErrorMessage()): ?>
                                    <?php echo $_rate->getErrorMessage() ?>
                               <?php else: ?>
                                    
                                    <div for="s_method_<?php echo $_rate->getCode() ?>" class="radio">                                        
                                        <input name="estimate_method" type="radio" value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio" />
										<span><?php echo $_rate->getMethodTitle() ?></span>
                                        <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                        <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                        <?php echo $_excl; ?>
                                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                        <?php endif; ?>
                                    </div>
                                    
                               <?php endif ?>
                        <?php endforeach; ?>
                     </fieldset> 
                <?php endforeach; ?>
                                                      
            <div>
                <button type="submit" title="<?php echo $this->__('Update Total') ?>" class="btn shippingbutton" name="do" value="<?php echo $this->__('Update Total') ?>"><span><span><?php echo $this->__('Update Total') ?></span></span></button>
            </div>
                            
        </form>
        <?php endif; ?>
        <script type="text/javascript">
        //<![CDATA[
            var coShippingMethodForm = new VarienForm('shipping-zip-form');
            var countriesWithOptionalZip = <?php echo $this->helper('directory')->getCountriesWithOptionalZip(true) ?>;

            coShippingMethodForm.submit = function () {
                var country = $F('country');
                var optionalZip = false;

                for (i=0; i < countriesWithOptionalZip.length; i++) {
                    if (countriesWithOptionalZip[i] == country) {
                        optionalZip = true;
                    }
                }
                if (optionalZip) {
                    $('postcode').removeClassName('required-entry');
                }
                else {
                    $('postcode').addClassName('required-entry');
                }
                return VarienForm.prototype.submit.bind(coShippingMethodForm)();
            }
        //]]>
        </script>
    </div>
</div>
<script type="text/javascript">
//<[CDATA[    
var shipping_estimator_url = '<?php echo $this->getUrl('etemando/pcs/autocompletecart', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>';
var avs = new Avs(
	shipping_estimator_url,
	'postcode',
	'city',
	'country'
);
//]]>
</script>