<?php
/**
this may work in the layout
ifconfig="evlike/evlike_visibility/ev_like_visibility_cms_default"
*/
if (Mage::getConfig()->getModuleConfig('Evolved_Like')->is('active', 'true')):
?>
<!-- Facebook Script Requirement -->
<div id="fb-root"></div>
<script>
(function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id))
		return;
	js = d.createElement(s);
	js.id = id;
	js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=280177685359496";
	fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
<!-- End: Facebook Script Requirement -->   
<?php endif; ?>