<?php if (Mage::getStoreConfigFlag('aromicon_gua/general/enable')): ?>
	<!--Aromicon Google Universal Analytics Section start -->
	<script type="text/javascript">
		<?php if(Mage::getStoreConfigFlag('aromicon_gua/ecommerce/enableec')): ?>
			<?php try{
				$_product = $this->getProduct();
				$_prod_id   = $_product->getId();
				$_prod_name = str_replace('\'','',Mage::helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name'));
				$_prod_cat  = (is_object(Mage::registry('current_category'))&& !is_null(Mage::registry('current_category'))) ? Mage::registry('current_category')->getName() : "deleted";
			?>
				ga('require', 'ec');
				ga('ec:addProduct', {
				  'id': '<?php echo $_prod_id; ?>',
				  'name': '<?php echo $_prod_name; ?>',
				  'category': '<?php echo $_prod_cat; ?>',
				  'brand': '',
				  'variant': ''
				});

				ga('ec:setAction', 'detail');

				ga('send', 'pageview');
			<?php
			}catch (Exception $e){}
			?>
		<?php endif; ?>
	</script>
<?php endif; ?>