<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
    <head>
		<?php echo $this->getChildHtml('head') ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    </head>
	
    <body<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : '' ?>>

        <?php echo $this->getChildHtml('facebookScript') ?>

		<?php echo $this->getChildHtml('after_body_start') ?>

		<!-- Header Section	-->
		<header>
			<!-- Navbar -->	
			<section id="navbar">
				<div class="container">
					<div class="row">			
						<div class="span12">
							<?php echo $this->getChildHtml('header') ?>							
						</div>						
					</div>
				</div>				
			</section>						
			<!-- End: Navbar -->			
		</header>
		<!-- End: Header -->

		<!-- Brand Section -->				
		<section id="brand">
			<div class="container">
				<div class="row">
					<div class="span12">
						<?php echo $this->getChildHtml('phsocial') ?> 
					</div>
				</div>
			</div>
		</section>
		<!-- End: Brand Section -->				

		<!-- Navigation Section -->
		<section id="navigation">
			<div class="container">
				<div class="row">
					<div class="span12">
						<!-- Mobile Menu -->
						<a id="mobile-nav" class="menu-nav" data-toggle="collapse" data-target=".nav-collapse"><span class="menu-icon"></span></a>

						<!-- Standard Menu -->
						<nav id="menu">
							<?php echo $this->getChildHtml('phmenu') ?>
						</nav>
					</div>
				</div>
			</div>
		</section>
		<!-- End: Navigation Section -->

		<!-- Filters Section -->
		<section id="filters">
			<div class="container">
				<div class="row">
					<?php echo $this->getChildHtml('phfilters') ?>

				</div>
			</div>
		</section>
		<!-- End: Filters Section -->

		<!-- Main Section -->
		<section id="content">
			<div class="container">
				<div class="row">
					<div class="span12">
						
						<?php echo $this->getChildHtml('breadcrumbs') ?>
						

						<?php
							/* Responsive Design : menu */
							$_helper = $this->helper('catalog/output');
							$subCategory = Mage::registry('current_category');	
							$parentCategory	= null;
							if ($subCategory != null && $subCategory->getLevel() == 3) {
								$parentCategory = Mage::getModel('catalog/category')->load($subCategory->getParentId()); 
							} elseif ($subCategory != null)  {
								$parentCategory = Mage::getModel('catalog/category')->load($subCategory->getId()); 	
							}

							if ($parentCategory != null) {
								$filter = new Mage_Widget_Model_Template_Filter();
								$_widget = $filter->filter('{{widget type="pronav/category_widget_subcategories_list" levels="1" columns="1" thumbnail_images="No" category_images="No" selected_cat="Yes" template="pronav/items/widget/link/subcategories/sortedlist.phtml" id_path="category/' . $parentCategory->getId() .'"}}');             

								echo '<div class="rsp-nav-group">';
									echo '<div class="rsp-nav-header">';				
										echo '<div class="rsp-nav-title rsp-nav-toggle">';
											echo '<img class="icon-menu" src="' . $this->getSkinUrl('images/core/menu-icon-grey.png') . '" alt="main menu">';				
											echo $parentCategory->getMetaTitle();
											//echo $parentCategory->getName();
										echo '</div>';

									echo '</div>';

									echo '<div class="rsp-nav-menu-toggle" style="display:none">';
										echo '<ul class="rsp-nav-menu">';
											echo $_widget;
										echo '</ul>';
									echo '</div>';
								echo '</div>';
							}
						?>
						
						<!-- Middle Column -->
						<?php echo $this->getChildHtml('global_messages') ?>
						<?php echo $this->getChildHtml('content') ?>
						<!-- End: Middle Column -->
					</div>
				</div>
			</div>
		</section>
		<!-- End: Main Content -->

		<!-- Call To Actions -->
		<section id="calltoactions">
			<div class="container">
				<div class="row">
					
					<div class="span12" id="cta01">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cta-bottom')->toHtml(); ?>
					</div>			    

				</div>
			</div>
		</section>
		<!-- End: Call To Actions -->

		<!-- Footer
		================================================== -->
			<?php echo $this->getChildHtml('footer'); ?>
		<!-- End: Footer
		================================================== -->

		<!-- Javascript -->
		<!-- Placed at the end of the document so the pages load faster -->
		
		<script src="<?php echo $this->getSkinUrl('js/google-code-prettify/prettify.js'); ?>"></script>
		<script src="<?php echo $this->getSkinUrl('js/bootstrap.js'); ?>"></script>      
		<script src="//assets.pinterest.com/js/pinit.js" type="text/javascript"></script>
		<script src="<?php echo $this->getSkinUrl('js/account.js'); ?>"></script>
		<script src="<?php echo $this->getSkinUrl('js/responsive-navigation.js'); ?>"></script>

		<?php echo $this->getChildHtml('before_body_end') ?>
    </body>
</html>
