<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
	<head>
		<?php echo $this->getChildHtml('head') ?>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	</head>
	
	<body class="basic-layout">
		<?php echo $this->getChildHtml('after_body_start') ?>
		<div class="wrapper">
			<div class="super-container">
				<div class="main">
					<?php echo $this->getChildHtml('content') ?>
				</div>
			</div>
		</div>
		<?php echo $this->getChildHtml('before_body_end') ?>
	</body>
</html>
