<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
</head>
<body class="page-popup<?php echo $this->getBodyClass()?$this->getBodyClass() : ''?>">
<div>
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('content') ?>
</div>
        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->

        <script src="<?php echo $this->getSkinUrl('js/jquery/jquery-1.10.2.min.js'); ?>"></script>

        <script src="<?php echo $this->getSkinUrl('js/google-code-prettify/prettify.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/bootstrap-transition.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/bootstrap-alert.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/bootstrap-modal.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/bootstrap-dropdown.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/bootstrap-scrollspy.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/bootstrap-tab.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/bootstrap-tooltip.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/bootstrap-popover.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/bootstrap-button.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/bootstrap-collapse.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/bootstrap-carousel.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/bootstrap-typeahead.js'); ?>"></script>
        <script src="<?php echo $this->getSkinUrl('js/application.js'); ?>"></script>

        <?php echo $this->getChildHtml('before_body_end') ?>

</body>
</html>
