<div class="survey_block col-lg-12 col-md-12 col-xs-12 col-sm-12">
    <?php

    $survey = $this->getCurrentSurvey();

    if($survey->title == '') {
        echo 'invalid survey id';
    }
    else { ?>
        <div class="page-title">
            <strong><span>Survey: <?php echo $survey->title ?></span></strong>
        </div>
    <?php
    // check for cms block named customersurvey_N where N = customersurvey_id
    // TODO: make this part of survey model
    $cmsBlockId = sprintf("customersurvey_%d", $survey->customersurvey_id);
    $block  = Mage::getModel('cms/block')->setStoreId(Mage::app()->getStore()->getId())->load($cmsBlockId);
    if ($cmsBlockId == $block->getIdentifier()):
    $var = array('variable' => 'value', 'other_variable' => 'other value');
    /* This will be {{var variable}} and {{var other_variable}} in your CMS block */
    $filterModel = Mage::getModel('cms/template_filter');
    $filterModel->setVariables($var);
    ?>
        <div class="block-description">
            <p><?php echo  $filterModel->filter($block->getContent()); ?></p>
        </div>
    <?php endif; ?>
        <div>
            <form id="survey_form" method="POST" action="<?php echo $this->getSaveUrl(); ?>">
                <input type="hidden" name="survey_number" value="<?php echo $survey->customersurvey_id ?>" />

                <?php foreach($this->getMyQuestions() as $question) { ?>
                    <h6><?php echo $question->question ?></h6>

                    <?php switch($question->answer_type) {
                        case "bubbles1": ?>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="question<?php echo $question->question_id ?>_answer" onchange="ChangeHidden(<?php echo $question->question_id ?>, this);" value="Very satisfied">
                                    Very satisfied
                                </label>
                                <label>
                                    <input type="radio" name="question<?php echo $question->question_id ?>_answer" value="Satisfied" onchange="ChangeHidden(<?php echo $question->question_id ?>, this);">
                                    Satisfied
                                </label>
                                <label>
                                    <input type="radio" name="question<?php echo $question->question_id ?>_answer" value="Neutral" onchange="ChangeHidden(<?php echo $question->question_id ?>, this);">
                                    Neutral
                                </label>
                                <label>
                                    <input type="radio" name="question<?php echo $question->question_id ?>_answer" value="Dissatisfied" onchange="ChangeHidden(<?php echo $question->question_id ?>, this);">
                                    Dissatisfied
                                </label>
                                <label>
                                    <input type="radio" name="question<?php echo $question->question_id ?>_answer" value="Very dissatisfied" onchange="ChangeHidden(<?php echo $question->question_id ?>, this);">
                                    Very dissatisfied
                                </label>
                                <input type="hidden" class="input-text required-entry" name="question<?php echo $question->question_id ?>" id="question<?php echo $question->question_id ?>" />
                            </div>

                            <?php break; ?>
                        <?php case "bubbles2": ?>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="question<?php echo $question->question_id ?>_answer" value="excellent" onchange="ChangeHidden(<?php echo $question->question_id ?>, this);">
                                    Excellent
                                </label>
                                <label>
                                    <input type="radio" name="question<?php echo $question->question_id ?>_answer" value="good" onchange="ChangeHidden(<?php echo $question->question_id ?>, this);">
                                    Good
                                </label>
                                <label>
                                    <input type="radio" name="question<?php echo $question->question_id ?>_answer" value="fair" onchange="ChangeHidden(<?php echo $question->question_id ?>, this);">
                                    Fair
                                </label>
                                <label>
                                    <input type="radio" name="question<?php echo $question->question_id ?>_answer" value="poor" onchange="ChangeHidden(<?php echo $question->question_id ?>, this);">
                                    Poor
                                </label>
                                <input type="hidden" class="input-text required-entry" name="question<?php echo $question->question_id ?>" id="question<?php echo $question->question_id ?>" />
                            </div>

                            <?php break; ?>
                        <?php case "field": ?>
                            <div class="form-group">
                                <input type="text" name="question<?php echo $question->question_id ?>" class="form-control input-text required-entry" value="" />
                            </div>
                            <?php break; ?>
                        <?php case "area": ?>
                            <div class="form-group">
                                <textarea name="question<?php echo $question->question_id ?>" class="form-control required-entry required-entry textarea"></textarea>
                            </div>
                            <?php break; ?>
                        <?php case "star": ?>
                            <div class="star-container">
                                <?php if (Mage::helper('framework')->isBootstrapJsEnabled()): ?>
                                    <input type="number" name="question<?php echo $question->question_id ?>" id="question<?php echo $question->question_id ?>" class="rating" data-clearable="remove" <?php if (Mage::helper('framework')->isFaEnabled()): ?>data-icon-lib="fa" data-active-icon="fa-star fa-lg" data-inactive-icon="fa-star-o fa-lg" data-clearable-icon="fa-trash-o fa-lg"<?php endif; ?>/>
                                <?php else: ?>
                                    <img onmouseout="starLeave(<?php echo $question->question_id ?>);" onclick="starClick(1, <?php echo $question->question_id ?>);" onmouseover="StarHover(1, this, <?php echo $question->question_id ?>);" id="question<?php echo $question->question_id ?>_1" src="<?php echo $this->getSkinUrl('images/factoryx/customersurvey/star.png'); ?>" />

                                    <img onmouseout="starLeave(<?php echo $question->question_id ?>);" onclick="starClick(2, <?php echo $question->question_id ?>);" onmouseover="StarHover(2, this, <?php echo $question->question_id ?>);" id="question<?php echo $question->question_id ?>_2" src="<?php echo $this->getSkinUrl('images/factoryx/customersurvey/star.png'); ?>" />

                                    <img onmouseout="starLeave(<?php echo $question->question_id ?>);" onclick="starClick(3, <?php echo $question->question_id ?>);" onmouseover="StarHover(3, this, <?php echo $question->question_id ?>);" id="question<?php echo $question->question_id ?>_3" src="<?php echo $this->getSkinUrl('images/factoryx/customersurvey/star.png'); ?>" />

                                    <img onmouseout="starLeave(<?php echo $question->question_id ?>);" onclick="starClick(4, <?php echo $question->question_id ?>);" onmouseover="StarHover(4, this, <?php echo $question->question_id ?>);" id="question<?php echo $question->question_id ?>_4" src="<?php echo $this->getSkinUrl('images/factoryx/customersurvey/unstar.png'); ?>" />

                                    <img onmouseout="starLeave(<?php echo $question->question_id ?>);" onclick="starClick(5, <?php echo $question->question_id ?>);" onmouseover="StarHover(5, this, <?php echo $question->question_id ?>);" id="question<?php echo $question->question_id ?>_5" src="<?php echo $this->getSkinUrl('images/factoryx/customersurvey/unstar.png'); ?>" />

                                    <input type="hidden" name="question<?php echo $question->question_id ?>" id="question<?php echo $question->question_id ?>" value="3" />
                                <?php endif; ?>
                            </div>
                            <?php break; ?>
                        <?php case "yesno": ?>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="question<?php echo $question->question_id ?>_answer" value="Yes" onchange="ChangeHidden(<?php echo $question->question_id ?>, this);">
                                    Yes
                                </label>
                                <label>
                                    <input type="radio" name="question<?php echo $question->question_id ?>_answer" value="No" onchange="ChangeHidden(<?php echo $question->question_id ?>, this);">
                                    No
                                </label>
                                <input type="hidden" class="input-text required-entry" name="question<?php echo $question->question_id ?>" id="question<?php echo $question->question_id ?>" />
                            </div>
                            <?php break; ?>
                        <?php case "customradio": ?>
                            <div class="radio">

                                <?php

                                if($question->possible_answers) {
                                    $possibleAnswers = explode('|||', $question->possible_answers);
                                }
                                else {
                                    $possibleAnswers = array();
                                }
                                ?>

                                <?php foreach($possibleAnswers as $possibleAnswer) { ?>
                                    <label>
                                        <input type="radio" name="question<?php echo $question->question_id ?>_answer" value="<?php echo $possibleAnswer; ?>" onchange="ChangeHidden(<?php echo $question->question_id ?>, this);">
                                        <?php echo $possibleAnswer; ?>
                                    </label>
                                <?php } ?>

                                <input type="hidden" class="input-text required-entry" name="question<?php echo $question->question_id ?>" id="question<?php echo $question->question_id ?>" />
                            </div>
                            <?php break; ?>
                        <?php case "checkboxes": ?>
                            <div class="checkbox">

                                <?php

                                if($question->possible_answers) {
                                    $possibleAnswers = explode('|||', $question->possible_answers);
                                }
                                else {
                                    $possibleAnswers = array();
                                }
                                ?>

                                <?php $counterA = 0 ?>

                                <?php foreach($possibleAnswers as $possibleAnswer) { ?>
                                    <label>
                                        <input type="checkbox" name="question<?php echo $question->question_id ?>_answer" value="<?php echo $counterA; ?>" onchange="CheckBoxAction(<?php echo $question->question_id ?>, this);">
                                        <?php echo $possibleAnswer; ?>
                                    </label>

                                    <?php $counterA++ ?>
                                <?php } ?>

                                <input type="hidden" class="input-text required-entry" name="question<?php echo $question->question_id ?>" id="question<?php echo $question->question_id ?>" />
                            </div>
                            <?php break; ?>
                        <?php } ?>

                <?php } ?>

                <?php $x = rand(0,9); $y = rand(0,9); $_SESSION['rand']=$x+$y; ?>
                <div class="question-container form-group"><h6>What is the result of <?php echo $x; ?> + <?php echo $y; ?>?</h6><input name="rand" class="form-control required-entry validate-are-you-human" id="rand" /></div>

                <div class="actions">
                    <button class="btn btn-primary button" title="Submit" type="submit"><span><span>Submit</span></span></button>
                </div>

            </form>
        </div>

        <input type="hidden" value="<?php  echo $this->getSkinUrl('images/factoryx/customersurvey/star.png'); ?>" id="goodstar" />
        <input type="hidden" value="<?php  echo $this->getSkinUrl('images/factoryx/customersurvey/unstar.png'); ?>" id="badstar" />

        <script type="text/javascript">
            var customForm = new VarienForm('survey_form');

            // custom validation for 'What is the result of'
            Validation.add('validate-are-you-human', 'Are you a human?!', function(val) {
                return (val == '<?php echo ($x + $y); ?>');
            });
            // stop double clicks/submits
            jQuery("#survey_form .button").click(
                function() {
                    if (customForm.validator && customForm.validator.validate()) {
                        jQuery(this).attr('disabled', 'disabled');
                        jQuery("span > span", this).html("Submitting...");
                        customForm.submit();
                    }
                }
            );
        </script>

    <?php } ?>
</div>