<?php
$_bundledProduct = $this->getCurrentBundle();

// Get original image as their resolution is ready for lookbook
$img = (string)Mage::helper('catalog/image')->init($_bundledProduct, 'image');
?>
<div class="bundle-image">
    <img src="<?php echo $img; ?>" alt="<?php $_bundledProduct->getName(); ?>" />
</div>
<div class="bundle-items">
    <?php
    $desc = $_bundledProduct->getData('description');
    if (strlen($desc) > 10): ?>
    <div class="bundle-item-desc">
        <?php
        // echo sprintf("<h1 id='name'>%s</h1>", $_bundledProduct->getName());
        // if no brs then 
        if (!preg_match('/<br(\/?)>/', $desc)) {
            $desc = nl2br($desc);
        }
        echo sprintf("<p>%s</p>", $desc);
        ?>
    </div>
    <?php endif; ?>
    <div class="bundle-items-list">
    <?php
    $optionsIds = $_bundledProduct->getTypeInstance(true)->getOptionsIds($_bundledProduct);
    /*
    check if options exist (otherwise getSelectionsCollection will return all items!)
    if no options display tyhe description
    */
    if (count($optionsIds)):
        $selectionCollection = $_bundledProduct->getTypeInstance(true)->getSelectionsCollection($optionsIds, $_bundledProduct);
        //echo sprintf("count: %d", count($selectionCollection));

        $options = array();
        foreach($selectionCollection as $option) {
            if (array_key_exists($option->getOptionId(), $options)) {
                continue;
            }

            // Get the simple product ID
            $selectionId = $option->getId();
            // Get the parent configurable
            $parentIds = Mage::getResourceSingleton('catalog/product_type_configurable')->getParentIdsByChild($selectionId);

            if ($parentIds) {
                // Load the configurable
                $parent = Mage::getModel('catalog/product')->load($parentIds[0]);
                // Get the image of the parent configurable
                $img = (string)Mage::helper('catalog/image')->init($parent, 'small_image');
                // Add to the array
                $options[$option->getOptionId()]['image'] = $img;
                $options[$option->getOptionId()]['name'] = $parent->getName();
                $options[$option->getOptionId()]['url'] = $parent->getProductUrl();
                $options[$option->getOptionId()]['price'] = Mage::helper('core')->currency($parent->getPrice(), true, false);
            }
        }
        ?>
        <?php foreach ($options as $option): ?>
            <div class="bundle-item">
                <div class="bundle-item-image">
                    <?php echo startLink($option['url']); ?>
                        <img src="<?php echo $option['image']; ?>" alt="<?php echo $option['name']; ?>" />
                    <?php echo (($option['url']) ? "</a>" : ""); ?>
                </div>
                <div class="bundle-item-info">
                    <div class="bundle-item-info-desc">                    
                        <h2><?php echo sprintf("%s%s", startLink($option['url']), $option['name']); ?><?php echo (($option['url']) ? "</a>" : ""); ?></h2>
                        <p><?php echo $option['price']; ?></p>
                    </div>                        
                </div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <!-- do nothing -->
    <?php endif; ?>
    </div>
</div>
<?php
function startLink($url) {
    $a = "";
    if ($url) {
        $a = sprintf("<a target=\"_blank\" rel=\"noopener noreferrer\" href=\"%s\">", $url);
    }
    return $a;
}
?>
<script>
jQuery("bundle_content").on("touchmove", function(){
    dragging = true;
});
jQuery("bundle_content").on("touchstart", function(){
    dragging = false;
});
jQuery(document).on('touchend click', '.lookbook-product-item', function(event){
    if (typeof dragging !== 'undefined' && dragging) {
        return;
    }
});
</script>