<?php
// Retrieve the lookbook
$lookbook = $this->getCurrentLookbook();

// Get lookbook images
$_imageCollection = $lookbook->getGallery();

// Count lookbook images
$numOfSlides = count($_imageCollection);

// Lookbook dimensions
$dimensions = Mage::helper('lookbook')->calculateLookDimensions($lookbook);
?>

<div id="flipbook">
    <?php $count = 1; ?>
    <?php foreach ($_imageCollection as $_image): ?>
        <?php $img = (string)Mage::helper('lookbook/image')->init($lookbook, 'image', $_image['file']); ?>
        <div <?php if ($count == 1 || $count == 2 || $count == count($_imageCollection) || $count == (count($_imageCollection)-1)): ?>class="hard"<?php endif;?>>
            <img src="<?php echo $img ?>" alt="<?php echo $lookbook->getTitle() ?>" />
        </div>
        <?php $count++; ?>
    <?php endforeach; ?>
</div>


<script type="text/javascript">
    function adjustFlipbook(){
        var width = jQuery('.main-container').width();
        var height = Math.floor(width / <?php echo $dimensions['width'] ?> * <?php echo $dimensions['height'] ?> / 2);
        jQuery("#flipbook").turn("size",width,height);
        jQuery("#flipbook").turn("resize");
    }
    jQuery(document).ready(function(){
        jQuery("#flipbook").turn({
            width: <?php echo $dimensions['width']*2 ?>,
            height: <?php echo $dimensions['height'] ?>,
            display: 'double',
            autoCenter: true
        });
        adjustFlipbook();
    });
    jQuery(window).resize(function(){
        adjustFlipbook();
    });
</script>

<?php if ($lookbook->getPagePrompt()){ ?>

    <div id="hint">
        <div><i class="fa fa-info-circle"></i> Drag the corner to the left side to view next page</div>
    </div>
    <script>
        jQuery("#flipbook").bind("turning", function(event, page, view) {
            if (page == 1){
                jQuery('#hint').slideDown();
            }else{
                jQuery('#hint').slideUp();
            }
        });
    </script>

<?php } ?>


