<?php
/*
TODO
- move config to magento config e.g. Factory X -> Look Book
- move css & js to separate files

Page Layout = 1 column

Custom Layout Update
<remove name="breadcrumbs" />
<reference name="product_list">
    <action method="setTemplate">
        <template>factoryx/lookbook/lookbook_basic.phtml</template>
    </action>
    <action method="setData"><name>lookbook_width</name><value>960</value></action>
    <action method="setData"><name>looks_per_page</name><value>4</value></action>
    <action method="setData"><name>look_border</name><value>0</value></action>        
    <action method="setData"><name>look_width</name><value>240</value></action>            
    <action method="setData"><name>look_height</name><value>500</value></action>
    <action method="setData"><name>look_colour</name><value>white</value></action>
</reference>
*/

$lookbookWidth = 960;
$looksPerPage = 4;
$lookBorder = 0;
$lookWidth = 240;
$lookHeight = 550;

// not configurable via xml
$lookDescTopPadding = 5;
$lookDescMaxLines = 6;
$lookDescHeight = 90; // allows for 6 lines at 11px (truncated if >)
$lookScaleHeight = 45;
$lookDescBorderWidth = 0;
$lookDescSidePadding = 10;
$barWidth = 2;

$lookColour = "black"; // black | white

if ($this->getData('lookbook_width')) {
    $lookbookWidth = $this->getLookbookWidth();
}
if ($this->getData('looks_per_page')) {
    $looksPerPage = $this->getLooksPerPage();
}
if ($this->getData('look_border')) {
    $lookBorder = $this->getLookbookBorder();
}
if ($this->getData('look_width')) {
    $lookWidth = $this->getLookWidth();
}
if ($this->getData('look_height')) {
    $lookHeight = $this->getLookHeight();
}
if ($this->getData('look_colour')) {
    $lookColour = $this->getLookColour();
}

$mainBorder = "10px solid #000";
$mainPadding = "0";
$arrowLeft = $this->getSkinUrl('images/slider/arrow-prev.png');
$arrowRight = $this->getSkinUrl('images/slider/arrow-next.png');         
switch ($lookColour) {
    case "black":
        $arrowLeft = $this->getSkinUrl('images/slider/arrow-prev.png');
        $arrowRight = $this->getSkinUrl('images/slider/arrow-next.png');    
        break;
    case "white":
        $mainBorder = "1px solid #000";
        $mainPadding = "9px";
        $arrowLeft = $this->getSkinUrl('images/slider/arrow-prev.png');
        $arrowRight = $this->getSkinUrl('images/slider/arrow-next.png');          
        break;
    default:
        // see above
}

$lookbookWidth += ($lookBorder * 2 * $looksPerPage);

// load in category completely (e.g. bundled products with no products)
$category = Mage::registry('current_category');
$_productCollection = Mage::getResourceModel('catalog/product_collection')->addCategoryFilter($category)
 ->addAttributeToSort('position', 'asc');

//$_productCollection->clear()->addAttributeToFilter('type_id', 'bundled')->load();

// this method will apply implicit filters
//$_productCollection = $this->getLoadedProductCollection();

$sql = $_productCollection->getSelect()->__toString();
//echo sprintf("sql=%s", $sql);

$numOfLooks = count($_productCollection);
//echo sprintf("numOfLooks=%d", $numOfLooks);

if ($numOfLooks == 0) {
    $numOfLooks = $looksPerPage;
}
$scaleLeftPad = 30;
$scaleWidth = (($lookbookWidth - ($scaleLeftPad * 2)) / ceil($numOfLooks / $looksPerPage));

/*
echo sprintf("lookbookWidth=%d", $lookbookWidth);
echo sprintf("looksPerPage=%d", $looksPerPage);
echo sprintf("lookWidth=%d", $lookWidth);
echo sprintf("lookHeight=%d", $lookHeight);
echo sprintf("scaleWidth=%d", $scaleWidth);
*/
?>

<head>
<script type="text/javascript" src=<?php echo sprintf("\"%s\"", $this->getJsUrl('effects/bubbleup.js')); ?>></script>
<script type="text/javascript" src=<?php echo sprintf("\"%s\"", $this->getJsUrl('effects/scrolling-div.js')); ?>></script>
<script type="text/javascript">
// rename $ to j to avoid conflicts with prototype.js

//var j = jQuery.noConflict();
/*
jQuery(function() {
    jQuery("div#lookbook ul#menu li img").bubbleup({tooltip: false, scale:<?php echo $lookWidth; ?>+10});
});
*/
</script>

<script type="text/javascript">
/*
function rollOutDiv(objImg, i) {
    maxWidth = <? echo $lookWidth + 10; ?>;
    obj1 = document.getElementById("getTheLook");
    obj1.style.width = '5px';
    var leftPos = i * <? echo $lookWidth; ?> - document.getElementById('container').scrollLeft;
    if (leftPos > 0) {
        leftPos -= 10;  
    }
    else {
        maxWidth = <? echo $lookWidth; ?>;
    }       
    //alert(leftPos);
    obj1.style.left = leftPos + 'px';
    obj1.style.visibility = "visible";
    lastBlock = jQuery("#getTheLook");
    jQuery(lastBlock).animate({
        width: maxWidth+"px"
    }, {
        queue:false, duration:400
    });
}

function rollOffDiv(objImg) {
    obj1 = document.getElementById("getTheLook");
    obj1.style.visibility = "hidden";   
}
*/
</script>
    
<style type="text/css">   
.col1-layout .category-title {
    display:none;
}
#lookbook ul#menu li img {
    float: left;
    vertical-align: top;
}
#lookbook div.lookDesc {
    padding-top:10px;
    border: <?php echo $lookDescBorderWidth; ?>px solid  #000;
    display: inline-block;
    margin-top: <? echo $lookHeight + 2; ?>px;
    z-index: 999;
    /*
    displayed as img has replaced desc
    width: <? echo $lookWidth - (($lookDescSidePadding * 2) + ($lookDescBorderWidth * 2) + 2); ?>px;
    height: <? echo $lookDescHeight; ?>px;
    padding: <?php echo $lookDescTopPadding; ?>px <?php echo $lookDescSidePadding; ?>px;
    */
    font-size: 11px;
}
.whiteBar {
    position: absolute;
    top: 10px;
    width: <?php echo $barWidth ?>px;
    height:<?php echo ($lookHeight); ?>px;
    z-index: 9999;
    background-color:#fff;
}
div#lookbook {
    background-color:#fff !important;
    margin: 0px auto 0px auto;
    text-align: center;
}

div#lookbook ul#menu {
    margin: 0px 0px;
    list-style: none;
    display: inline-block;
}
    
div#lookbook ul#menu li {
    float: left;
    position: relative;
    width: <? echo $lookWidth + ($lookBorder * 2); ?>px;
    height:  <? echo ($lookHeight + $lookDescHeight + ($lookDescTopPadding * 2)); ?>px;
}
/* (lookWidth + 2) * 5 */
/*
div#lookbook ul#menu li a {
    position: absolute;
}
*/
div#lookbook ul#menu li img {
    position: absolute;
    width: <? echo $lookWidth; ?>px;
    top: 0px;
    left: 0px;
    padding: 0px;
    /*
    TODO: calc if required
    margin: 0 4px 0 0;
    */
    border: 0px solid #000;
    overflow: hidden;
}
div#lookbook ul#menu li a div.lookDesc img {
    position: relative;
    overflow: visible;
}
#main {
    margin-top:0px;
    padding-top:0px;
    position: relative;
}
.getTheLook {
    position:absolute;
    left:0px;
    top:0px;
    height:22px;
    width:10px;
    z-index:1;
    background-color:transparent;
    color:transparent;
    margin:0;
    padding:0px 0 0px 0px;
    font-size:13px;
    font-family:verdana;
    font-weight:bold;
    text-align:left;
    visibility:hidden;
}

#container {
    margin-top:0px;
    padding-top:10px;
    position: relative;
    width: <? echo $lookbookWidth; ?>px;
    height: <? echo ($lookHeight + $lookDescHeight + ($lookDescTopPadding * 2) + $lookScaleHeight); ?>px;
    overflow: hidden;
    border: 0px solid #000;
}

/* = width + margin left + margin right + padding*2 + border*2  from the content rule */
#scroller {
    /* numberOfLooks x lookWidth */
    width:<?php echo ($numOfLooks * ($lookWidth + ($lookBorder * 2) )); ?>px;
}
.scrollNav, .scrollNav a:link, .scrollNav a:visited  {
  font-size: 12px;
  font-family: verdana;
  color:#00009C;
  font-weight: bold;
}
.col-main {
    padding:0px;
}
/*
scale with = lookbookWidth / round(numOfLooks / looksPerPage)
e.g. 960 / round(16 / 4) = 240px
*/
#scaleContainer {
    position:absolute;    
    top:<?php echo ($lookHeight + $lookDescHeight + $lookScaleHeight); ?>px;
    height:5px;
    left:<?php echo $scaleLeftPad; ?>px;
    width:<?php echo $scaleWidth; ?>px;
    z-index: 0;
}
#scale {
    position:relative;
    width:<?php echo $scaleWidth; ?>px;
    height:5px;
    background-color:#4E4E4E;
    margin:0;
    padding:0;
    font-size:1px;    
    /**
    left & width are rendered dynamically
    */
}
.mainContainer {
    float:left;
    width: <?php echo ($looksPerPage * $lookWidth); ?>px;
    text-align: center;
    /*border: <?php echo $mainBorder; ?>;*/
    padding: <?php echo $mainPadding; ?>;
    background-color: #fff;
    height: <?php echo ($lookHeight + $lookDescHeight + ($lookDescTopPadding * 2) + $lookScaleHeight) + 10; ?>px;
}

<!--[if IE]>
#scroller {
    /*
    = width + margin left + margin right from the content rule + border*2 from the container rule
    */
    width:<?php echo ($numOfLooks * ($lookWidth + ($lookBorder * 2) )); ?>px;
}
<! [endif]-->

</style>

</head>

<div id="collection-banner">
<?php
// echo $this->getLayout()->createBlock('cms/block')->setBlockId('collesction-banner')->toHtml();
?>
</div>

<div class="mainContainer">
<center>
<!--
<div style="text-align:center; width:<? echo $lookbookWidth; ?>px; border:0px solid #000">
<span class="scrollNav">
<a href="#null" onclick="toLeft('container')">« first</a> | 
<a href="#null" onmouseover="scrollDivLeft('container')" onmouseout="stopMe()">scroll left</a> | 
<a href="#null" onmouseover="scrollDivRight('container')" onmouseout="stopMe()">scroll right</a> | 
<a href="#null" onclick="toRight('container')">last »</a>
</span>
</div>
-->
<!--
border-left:10px solid #000; border-right:10px solid #000;
-->
<div id="main" style="">
 
<div style="position: absolute; left: -5px; top: <?php echo ($lookHeight  + $lookDescHeight + 25); ?>px; height: 26px; width: 26px; z-index:9999999">
    <img src="<?php echo $arrowLeft; ?>" 
        onMouseOver="this.style.cursor='pointer'; "
        onmouseout="stopMe()"
        onclick="jumpLeft('container', <? echo $lookbookWidth; ?>);">
</div> 
<div style="position: absolute; left: 940px; top: <?php echo ($lookHeight  + $lookDescHeight + 25); ?>px; height: 26px; width: 26px; z-index:9999999">
    <img src="<?php echo $arrowRight; ?>"
        onMouseOver="this.style.cursor='pointer';"
        onmouseout="stopMe()"
        onclick="jumpRight('container', <? echo $lookbookWidth; ?>, <? echo $lookWidth + ($lookBorder * 2); ?>);">
</div> 

<div id="scaleContainer">
    <div id="scale" style="left:0px; width:<?php echo $scaleWidth; ?>px;">&nbsp;</div>
</div>

<!-- white bars -->
<?php
$bars = round($lookbookWidth / $lookWidth);
//echo sprintf("bars=%d", $bars);
for($b = 1; $b < $bars ; $b++) {
    $left = ($lookWidth * $b) - ($barWidth / 2);
    echo sprintf("<div class=\"whiteBar\" style=\"left:%dpx;\">&nbsp;</div>", $left);
}
?>
<!-- white bars -->

<!--
<div id="getTheLook" class="getTheLook" style="position:absolute; z-index:9999999">
    <img src="<?php echo $this->getSkinUrl('images/thelook/get_the_look.gif'); ?>"></div>
-->
<div id="container">
<div id="scroller">
<div id="lookbook" style="text-align:left; background-color:#ccc; height:<?php echo $lookHeight ?>px; z-index:-999;">
<ul id="menu">
<?php
$_helper = $this->helper('catalog/output');
foreach ($_productCollection as $_product) {
    $_product_id = $_product->getId();
    $_product = Mage::getModel('catalog/product')->load($_product_id);
    $img = (string)Mage::helper('catalog/image')->init($_product, 'image')->resize($lookWidth, $lookHeight);
?>
    <li>
        <a href="<?php echo $_product->getProductUrl();?>">
        <img src="<?php echo $img; ?>"/>
        <div class='lookDesc'>
            <img src="<?php echo $this->getSkinUrl('images/campaign/shop-the-look.png'); ?>" />
            <?php
            
            /**
                        
            $desc = $_product->getDescription();
            if ($desc) {
                // replace br with line feed
                $desc = preg_replace("/<br[^>]*>\s*\r*\n*[forwardslash]is", "\n", $desc);
                $desc = strip_tags($desc);
                $d = explode(PHP_EOL, $desc);
                //echo sprintf("[%d]", count($d));
                $cnt = 1;
                foreach($d as $line) {
                    echo sprintf("%s<br/>", $line);
                    if ($cnt++ >= $lookDescMaxLines) {
                        break;
                    }
                }
            }
            */
        ?></div>
        </a>
    </li>
<?php 
} //endforeach
?>
</ul>
</div>

</div> <!-- scroller -->
</div> <!-- container -->
</div> <!-- main -->


</center>
</div>

<!-- optional block -->
<?php
$catId = Mage::getSingleton('catalog/layer')->getCurrentCategory()->getId();
$cmsBlockId = sprintf("look-%d-bottom", $catId);
//echo sprintf("cmsBlockId=%s", $cmsBlockId);
$active = Mage::getModel('cms/block')->load($cmsBlockId)->getIsActive();
if ($active == 1) {
    echo $this->getLayout()->createBlock('cms/block')->setBlockId($cmsBlockId)->toHtml(); 
}
?>
<script>
objScale = document.getElementById("scale");
var curr_width = parseInt(objScale.style.width); 
var curr_left = parseInt(objScale.style.left);
//alert("curr_width=" + curr_width + ",curr_left=" + curr_left);

// reset
document.getElementById('container').scrollLeft = 0;
</script>

