<?php

// Get all enabled lookbooks
$activeLookbooks = $this->getActiveLookbooks();

if (count($activeLookbooks)==1): ?>
	<li class="level0 nav-0 first level-top parent">
		<?php $activeLookbook = $activeLookbooks->getFirstItem(); ?>
		<a href="<?php echo Mage::getUrl($activeLookbook->getIdentifier()) ?>">
			<span><?php echo $activeLookbook->getTitle(); ?></span>
		</a>
	</li>
<?php elseif (count($activeLookbooks)>1): ?>
	<li class="level0 nav-0 first level-top parent">
		<a class="level-top" href="<?php echo Mage::getUrl($activeLookbooks->getFirstItem()->getIdentifier()) ?>">
			<span><?php echo $this->__('Collections') ?></span>
		</a>
		<ul class="level0" style="width: auto">
			<?php $count = 0; ?>
			<?php foreach ($activeLookbooks as $activeLookbook): ?>
				<li class="level1 nav-0-<?php echo $count ?> <?php if(!$count):?>first<?php endif; ?>">
					<a href="<?php echo Mage::getUrl($activeLookbook->getIdentifier()) ?>">
						<span><?php echo $activeLookbook->getTitle() ?></span>
					</a>
				</li>
				<?php $count++ ; ?>
			<?php endforeach; ?>
		</ul>
	</li>
<?php endif; ?>