<?php
// Retrieve the lookbook
$lookbook = $this->getCurrentLookbook();

// Get lookbook images
$_imageCollection = $lookbook->getGallery();

// Count lookbook images
$numOfSlides = count($_imageCollection);

?>

<script type="text/javascript">
	// document.body.style.overflow = "hidden";
	jQuery.noConflict();
	
	var trueHeight = jQuery(window).height()-30;
	var trueWidth = Math.ceil(700/1000*trueHeight);
	var thumbHeight = Math.ceil((trueHeight-72)/3);
	var thumbWidth = Math.ceil(700/1000*thumbHeight);
	var maxWidth = jQuery(window).width() - thumbWidth -40;
	if (trueWidth>maxWidth) {
		trueWidth = maxWidth;
		trueHeight = Math.ceil(trueWidth*10/7);
	}
	var slideHeight = trueHeight-60;
	var slideWidth = Math.ceil(700/1000*slideHeight);
	jQuery(window).load(function() {
		var mygallery = new fadeSlideShow({
			wrapperid: "fadeshow1", //ID of blank DIV on page to house Slideshow
			dimensions: [slideWidth, slideHeight], //width/height of gallery in pixels. Should reflect dimensions of largest image
			imagearray: [
				<?php $count = 0; ?>
				<?php foreach ($_imageCollection as $_image): ?>
					<?php $img = (string)Mage::helper('lookbook/image')->init($lookbook, 'image', $_image['file']); ?>
					["<?php echo $img ?>", "<?php echo $lookbook->getDefaultUrl() ?>", "_new"]<?php if (++$count < $numOfSlides): ?>,<?php endif; ?>
				<?php endforeach; ?>
			],
			displaymode: {type:'manual', pause:2500, cycles:0, wraparound:false},
			persist: false, //remember last viewed slide and recall within same session?
			fadeduration: 500, //transition duration (milliseconds)
			descreveal: "ondemand",
			togglerid: "fadeshow1toggler"
		})

		// nav
		jQuery('#carouselh').jsCarousel({
			onthumbnailclick: function(src) {
				var slideId = jQuery("img[src$='" + src + "']").attr('id');
				//alert(slideId);
				mygallery.navigate(slideId - 1);
			},
			autoscroll      : false,
			circular        : true,
			masked          : false,
			itemstodisplay  : 3,
			orientation     : 'v',
			trueTotalHeight : (trueHeight-72+36),
			pageNumberId    : 'currentpos',
			pageThumbId     : 'slidePagination'
		});
		jQuery('#leftNav').css({width:thumbWidth+20+'px'});
		jQuery('.jscarousal-contents-vertical img').css({height:thumbHeight+'px',border:'1px solid #E0E0E0'});
		jQuery('.jscarousal-contents-vertical').css({height:(jQuery('.visible > .slide').first().outerHeight()*3)+(7*4)+'px'});

		var total = jQuery('.slide').length;
		for (var i=1;i<total;i++){
			if (jQuery('.slide > #'+i).attr('src') != "about:blank"){            
				jQuery('#slidePagination').append("<div id='"+i+"'>"+i+"</div>");
			}
		}
		jQuery('#slidePagination > div').first().addClass('selected');
		jQuery('#slidePagination > div').click(function(){
			mygallery.navigate(jQuery(this).html()-1);
			jQuery('#slidePagination > .selected').removeClass('selected');
			jQuery(this).addClass('selected');
			jQuery('#currentpos').html(jQuery(this).html());

		});
		var x = setTimeout(function(){
			jQuery('#fadeshow1').prepend('<div id="currentpos">1</div>');
			jQuery('#fadeshow1').css({'margin-top':Math.ceil((jQuery(window).height()-trueHeight)/2)+'px','display':'inline-block'});
			var slidePositionY = jQuery('#fadeshow1').position().left;
			var leftNavSize = jQuery('#leftNav').outerWidth();
			jQuery('#fadeshow1').css({'margin-left':(0-(slidePositionY-leftNavSize))+'px'});
			jQuery('#slidePagination').css({'position':'relative','left':((0-(slidePositionY-leftNavSize))/2)+'px'});
			jQuery('#leftNav').css({'margin-left':slidePositionY-leftNavSize+'px'});
		});
	});
</script>

<center>
	<div id="wrapper">

		<div id="leftNav">
			<div id="carouselh">
				<?php $count = 1; ?>
				<?php foreach ($_imageCollection as $_image): ?>
					<?php $img = (string)Mage::helper('lookbook/image')->init($lookbook, 'image', $_image['file']); ?>
					<div class="slide">
						<img id="<?php echo $count ?>"  src="<?php echo $img ?>" alt="<?php echo $lookbook->getTitle() ?>" />
						<div class="slideNum"> <?php echo $count++ ?></div>
					</div>
				<?php endforeach; ?>
			</div>
		</div>

		<div id="fadeshowwrapper">
			<div id="fadeshow1">
			</div>
			<div id="slidePagination">
			</div>
		</div>

		<div id="fadeshow1toggler">
			<a href="#" class="prev"><img src=""/></a>
			<a href="#" class="next"><img src=""/></a>
		</div>										

	</div>

	<div id="close" onclick="window.history.back()">
		<img src="<?php echo $this->getSkinUrl('images/btn_close.png') ?>" alt="<?php echo $this->__('Close') ?>" />
	</div>
	
</center>