<?php
// Retrieve the lookbook
$lookbook = $this->getCurrentLookbook();
//echo sprintf("lookbookId=%d<br/>", $lookbook->getLookbookId());

// Retrieve configurable settings
$lookbookWidth = $this->getLookbookWidth();
$looksPerPage = $this->getLooksPerPage();
//echo sprintf("looksPerPage=%d<br/>", $looksPerPage);

$lookBorder = $this->getLookbookBorder();
//echo sprintf("lookBorder=%s<br/>", $lookBorder);
$lookWidth = $this->getLookWidth();
//echo sprintf("lookWidth=%s<br/>", $lookWidth);
$lookHeight = $this->getLookHeight();
//echo sprintf("lookHeight=%s<br/>", $lookHeight);
$lookColor = $this->getLookColor();
//echo sprintf("lookColor=%s<br/>", $lookColor);
$lookbookType = $lookbook->getLookbookType();
//echo sprintf("lookbookType=%s<br/>", $lookbookType);

$lookbookNavType = "dots";
if ($lookbook->getData('nav_type')) {
    $lookbookNavType = $lookbook->getData('nav_type');
}
//echo sprintf("lookbookNavType=%s", $lookbookNavType);
//echo sprintf("BundleClick=%s", $lookbook->getBundleClick());


$clickToUrl = "";
$newTarget = "";

if ($lookbook->getBundleClick() != 0) {
    if ($lookbook->getClickNewTab()) {
        $newTarget = "target='_blank'";
    }
    if ($lookbook->getClickToUrl()) {
        $clickToUrl = $lookbook->getClickToUrl();
    }
}

// Under product
// 0 - none
// 1 - show child product
// 2 - show shop now button
// 3 - show bundle product description
$underProductDisplay = $lookbook->getUnderProductInfo();

/*
Mage::helper('lookbook')->log("lookbookWidth=".$lookbookWidth);
Mage::helper('lookbook')->log("looksPerPage=".$looksPerPage);
Mage::helper('lookbook')->log("lookWidth=".$lookWidth);
Mage::helper('lookbook')->log("lookHeight=".$lookHeight);
*/

// Retrieve non configurable settings
$lookDescTopPadding = $this->getLookDescTopPadding();
$lookDescMaxLines = $this->getLookDescMaxLines();
$lookDescHeight = $this->getLookDescHeight();
$lookScaleHeight = $this->getLookScaleHeight();
$lookDescBorderWidth = $this->getLookDescBorderWidth();
$lookDescSidePadding = $this->getLookDescSidePadding();
$barWidth = $this->getBarWidth();
$scaleLeftPad = $this->getScaleLeftPad();



// Generate color differences
switch ($lookColor)
{
    case "black":
        $mainBorder = "10px solid #000";
        $mainPadding = "0";
        $arrowLeft = $this->getSkinUrl('images/slider/arrow-prev.png');
        $arrowRight = $this->getSkinUrl('images/slider/arrow-next.png');
        break;
    case "white":
        $mainBorder = "1px solid #FFF";
        $mainPadding = "9px";
        $arrowLeft = $this->getSkinUrl('images/slider/arrow-prev.png');
        $arrowRight = $this->getSkinUrl('images/slider/arrow-next.png');
        break;
}

// Add borders to lookbook width
$lookbookWidth += ($lookBorder * 2 * $looksPerPage);
if ($lookbookType == "category") {
    // Get lookbook products
    $_productCollection = $lookbook->getLookbookProducts();
	if ($_productCollection)
	{
		// Count lookbook products
		$numOfLooks = count($_productCollection);
	}
	else $numOfLooks = 0;
    //echo sprintf("numOfLooks=%d<br/>", $numOfLooks);
}
else {
    // Get lookbook images
    $_imageCollection = $lookbook->getGallery();
    // Count lookbook images
    $numOfLooks = count($_imageCollection);
}
if (!$numOfLooks): ?>
	<p><?php echo $this->__('This lookbook is not available in this store.'); ?></p>
<?php else: ?>
    <div class="swiper-container" <?= ($lookbook->getLookbookWidth()) ? "style='width:".$lookbook->getLookbookWidth()."px'" : "" ?>>
        <div class="swiper-wrapper" style='position:relative;'>
            <?php
            if ($lookbookType == "category") {
                // Loop through looks
                $num = 0;
                foreach ($_productCollection as $_product) {
                    $num++;
                    // Resize the look image based on the look width and height
                    $img = (string)Mage::helper('catalog/image')->init($_product, 'image')->resize($lookWidth, $lookHeight);

                    $_href = "";
                    if ($lookbook->getBundleClick() == 1 ) {
                        $_href = sprintf(" href='%s'", $_product->getProductUrl());
                    }
                    elseif ($lookbook->getBundleClick() == 3 ) {
                        $_href = sprintf(" href='%s'", $clickToUrl);
                    }
                    ?>
                    <div class="swiper-slide" <?php echo ($lookbook->getLookWidth()) ? "style='position:relative; width:".$lookbook->getLookWidth()."px'" : "" ?>>
                        <a <?php echo $newTarget." ".$_href; ?>>
                            <img class="lookImg" src="<?php echo $img; ?>" style="width: <?php echo $lookWidth; ?>px" />
                            <?php if ($lookbook->getShowShopPix()): ?>
                                <?php
                                $relMediaPath = substr(Mage::getBaseDir('media'), strlen(Mage::getBaseDir()) );
                                $imageUrl = sprintf("%s/lookbook%s", $relMediaPath, $lookbook->getShopPix());
                                ?>
                                <div class="lookDesc">
                                    <img src="<?php echo $imageUrl; ?>" />
                                </div>
                            <?php endif; ?>
                        </a>
                        <!-- Display configurable products links if enabled -->
                        <?php
                        if ($underProductDisplay == 1) {
                        ?>
                            <div class="childProductsLink">
                                <?php $childProductsLinks = Mage::helper('lookbook')->getChildProductsLink($_product); ?>
                                <?php $cnt = 1; ?>
                                <?php foreach ($childProductsLinks as $childProductLink): ?>
                                    <a <?php echo $newTarget; ?> href="<?php echo $childProductLink['link'] ?>"><?php echo $childProductLink['name'].' '.$childProductLink['price'] ?></a><br/>
                                    <?php if ($cnt++ >= $lookDescMaxLines) break; ?>
                                <?php endforeach; ?>
                            </div>
                        <?php
                        }
                        elseif ($underProductDisplay == 3) {
                        ?>
                            <div class="product_description"><?php echo nl2br(rtrim(strip_tags($_product->getDescription()))); ?></div>
                        <?php
                        }
                        if ($lookbook->getShowLookNumber()) {
                        ?>
                            <div class='numberedBoxes' id="num<?php echo sprintf("%02d", $num); ?>" style="position:absolute; bottom:4px; text-align:top; padding:4px 0 0 0; width:22px; height:18px; border-width: 1px; border-style: solid; border-color: #000; background-color:#fff; ">
                                <?php echo sprintf("%02d", $num); ?></div>
                        <?php
                        }
                        ?>
                    </div>
                <?php
                } //endforeach
            }
            else {
                // Loop through looks
                foreach ($_imageCollection as $_image)
                {
                    // Resize the look image based on the look width and height
                    $img = (string)Mage::helper('lookbook/image')->init($lookbook, 'image', $_image['file'])->resize($lookWidth, $lookHeight);
                    ?>
                    <div style="width: <?php echo $lookWidth + ($lookBorder * 2); ?>px;height:  <?php echo ($lookHeight + $lookDescHeight + ($lookDescTopPadding * 2)); ?>px">
                        <?php if ($lookbook->getDefaultUrl()): ?>
                        <a <?php echo $newTarget; ?> href="<?php echo $lookbook->getDefaultUrl();?>">
                            <?php endif; ?>
                            <img class="lookImg" src="<?php echo $img; ?>" style="width: <?php echo $lookWidth; ?>px" />
                            <?php if ($lookbook->getDefaultUrl()): ?>
                        </a>
                    <?php endif; ?>
                    </div>
                <?php
                } //endforeach
            }
            ?>
        </div>
        <?php
        if (!preg_match("/none/i", $lookbookNavType)) {
        ?>
            <div class="pagination-wrapper">
                <div class="pagination"></div>
            </div>
        <?php
        }
        ?>    
        <div class="nav-button nav-button-left"><</div>
        <div class="nav-button nav-button-right">></div>
    </div> <!-- lookbook -->

    </div>

    <!-- Display Credits if enabled -->
	<?php if ($lookbook->getShowCredits()): ?>
		<div id="lookbook-credits">
			<!-- Model -->
			<?php if ($model = $lookbook->getModel()): ?>
				<?php echo $this->__('Model: <b>%s</b>', $model); ?>
			<?php endif; ?>
			|
			<!-- Photography -->
			<?php if ($photography = $lookbook->getPhotography()): ?>
				<?php echo $this->__('Photography: <b>%s</b>', $photography); ?>
			<?php endif; ?>
			|
			<!-- Make Up -->
			<?php if ($makeup = $lookbook->getMakeUp()): ?>
				<?php echo $this->__('Make up: <b>%s</b>', $makeup); ?>
			<?php endif; ?>
		</div>
	<?php endif; ?>

    <script type="text/javascript">
        var mySwiper = new Swiper('.swiper-container',{
            //Your options here:
            mode:'horizontal',
            speed : 500,
            calculateHeight: 'true',
            loop: false,
            slidesPerView: <?php echo $looksPerPage; ?>,
            <?php
            if (!preg_match("/none/i", $lookbookNavType)) {
            ?>
                pagination: '.pagination',
                paginationClickable: true,
            <?php
            }
            ?>
            loop: false,
            onSlideChangeEnd: function(){
                if (jQuery('.swiper-slide:last-child').hasClass('swiper-slide-visible') && jQuery('.nav-button-right').is(':visible')){
                    jQuery('.nav-button-right').css('display','none');
                }
                else if (!jQuery('.nav-button-right').is(':visible')){
                    jQuery('.nav-button-right').css('display','block');
                }
                if (jQuery('.swiper-slide:first-child').hasClass('swiper-slide-visible')  && jQuery('.nav-button-left').is(':visible')) {
                    jQuery('.nav-button-left').css('display', 'none');
                }
                else if (!jQuery('.nav-button-left').is(':visible')){
                    jQuery('.nav-button-left').css('display', 'block');
                }
            },
            onInit: function(){
                jQuery('.nav-button-left').css('display', 'none');
            }
        });
        jQuery('.nav-button').mousedown(function(e){ e.preventDefault();});
        jQuery('.nav-button-left').click(function(){ mySwiper.swipePrev(); });
        jQuery('.nav-button-right').click(function(){ mySwiper.swipeNext(); });
        var height = 0;
        setInterval(function(){
            if (height == 0){
                height = Math.floor(jQuery('.lookImg').first().height()/2-50);
                if (height != 0){
                    jQuery(".nav-button").css('top',height+'px');
                }
            }
        },1000);
        jQuery('.swiper-pagination-switch:gt('+(jQuery('.swiper-slide').length - <?php echo $looksPerPage; ?> ) +')').css('display','none') ;

        /*
        position numbered boxes
        */
        <?php
        if ($lookbook->getShowLookNumber()) {
        ?>
        var leftPos = 0;
        var prevWidth = 0;
        jQuery('.swiper-slide').each(
            function() {
                // right side
                //leftPos += jQuery(this).width();
                //jQuery('.numberedBoxes', this).css('left', (leftPos - (24 + 4)));
                
                // left side
                leftPos += prevWidth;
                jQuery('.numberedBoxes', this).css('left', (leftPos + 4) );
                prevWidth = jQuery(this).width();
            }
        );
        <?php
        }
        ?>        

        <!-- Enable Zoom -->
        <?php if ($lookbook->getZoomOnHover()): ?>
        jQuery(function() {
            jQuery("div#lookbook ul#menu li img.lookImg").bubbleup({tooltip: false, scale:<?php echo $lookWidth; ?>+10});
        });
        <?php endif; ?>
    </script>

	<?php if ($lookbook->getLookbookFacebook()): ?>
		<style>
			body, .page-empty{padding:0;}
			body, html {overflow: hidden;}
		</style>
		<script type="text/javascript" src="https://connect.facebook.net/en_US/all.js"></script>
		<script type="text/javascript">
			FB.init({
				appId      : '<?=$lookbook->getFacebookAppId()?>',
			});
			setTimeout(function(){
				FB.Canvas.setAutoGrow();
			},500);

			FB.Event.subscribe('edge.create', function(href, widget) {
				window.location.reload();
			});
		</script>
	<?php endif; ?>
<?php endif; ?>