<?php
// Retrieve the lookbook
$lookbook = $this->getCurrentLookbook();

// Retrieve configurable settings
$lookbookWidth = $this->getLookbookWidth();
$looksPerPage = $this->getLooksPerPage();
//$lookBorder = $this->getLookbookBorder();
$lookHeight = $this->getLookHeight();
$lookbookType = $lookbook->getLookbookType();
$lookbookLayout = $lookbook->getLayout();
$lookBundleWindowWidth = (($lookbook->getLookBundleWindowWidth()) ? $lookbook->getLookBundleWindowWidth() : 1003);
$includePrice = true;
$includeRenderBundleJs = false;

/*
# Nav Types
    fontawesome ???
    arrows
    dots
    arrows-dots
    scrollbar
*/

if ($lookbookNavType = $lookbook->getNavType()) {
    // Get the corresponding nav/pag styles
    switch($lookbookNavType) {
        case "fontawesome":
            $arrowStyle = Mage::helper('lookbook')->stripNav($lookbook->getSliderNavStyle());
            //$dotStyle = Mage::helper('lookbook')->stripPag($lookbook->getSliderPaginationStyle());
            $dotStyle = "pagination-fontawesome";
        case "arrows":
            $arrowStyle = Mage::helper('lookbook')->stripNav($lookbook->getSliderNavStyle());
            break;
        case "dots":
            $dotStyle = Mage::helper('lookbook')->stripPag($lookbook->getSliderPaginationStyle());
            break;
        case "arrows-dots":
            $arrowStyle = Mage::helper('lookbook')->stripNav($lookbook->getSliderNavStyle());
            $dotStyle = Mage::helper('lookbook')->stripPag($lookbook->getSliderPaginationStyle());
            break;
        default:
            $arrowStyle = "a01";
            $dotStyle = "b02";
            break;
    }
}

$clickToUrl = "";
$newTarget = "";
if ($lookbook->getClickNewTab() || $lookbook->getLookbookFacebook()) {
    $newTarget = "target='_blank' rel='noopener noreferrer'";
}
if ($lookbook->getBundleClick() != 0) {
    if ($lookbook->getClickToUrl()) {
        $clickToUrl = $lookbook->getClickToUrl();
    }
}

// Under product
// 0 - none
// 1 - show child product
// 2 - show shop now button
// 3 - show bundle product description
$underProductDisplay = $lookbook->getUnderProductInfo();

// 1 - Show Child Products with Links (additional fields)
$underProductLinksContact = $lookbook->getUnderProductInfoLinksContact();
$underProductLinksSubject = $lookbook->getUnderProductInfoLinksSubject();
$underProductLinksUnavailablePrefix = $lookbook->getUnderProductInfoLinksUnavailablePrefix();
$underProductLinksAvailablePrefix = $lookbook->getUnderProductInfoLinksAvailablePrefix();

// Retrieve non configurable settings
$lookDescTopPadding = $this->getLookDescTopPadding();
$lookDescMaxLines = $this->getLookDescMaxLines();
$lookDescHeight = $this->getLookDescHeight();

if ($lookbookType == "category")
{
    // Get lookbook products
    $_productCollection = $lookbook->getLookbookProducts();
    if ($_productCollection)
    {
        // Count lookbook products
        $numOfLooks = count($_productCollection);
    }
    else $numOfLooks = 0;
}
else {
    // Get lookbook images
    $_imageCollection = $lookbook->getGallery();
    // Count lookbook images
    $numOfLooks = count($_imageCollection);
}

// display category image if one is available
if ($lookbookType == "category") {
    $bannerImage = $lookbook->getLookbookBannerImage();
    if ($bannerImage) {
        echo sprintf("<div id='lookbook_banner_img_wrapper'><img id='lookbook_banner_img' src='%s' alt='%s'/></div>", $bannerImage, $lookbook->getTitle());
    }
}

if (!$numOfLooks): ?>
    <p><?php echo $this->__('This lookbook is not available in this store.'); ?></p>
    <?php return; ?>
<?php endif; ?>

<?php if ($lookbookLayout == "default"): ?>

<div class="swiper-container">
    <div class="swiper-wrapper">
        <?php
        if ($lookbookType == "category")
        {
            // Loop through looks
            $num = 0;
            foreach ($_productCollection as $_product)
            {
                $num++;

                // Get original image as their resolution is ready for lookbook
                $img = (string)Mage::helper('catalog/image')->init($_product, 'image');

                $_href = "";
                if ($lookbook->getBundleClick() == 1 )
                {
                    $_href = sprintf(" href='%s' %s", $_product->getProductUrl(), $newTarget);
                }
                elseif ($lookbook->getBundleClick() == 2 )
                {
                    $includeRenderBundleJs = true;
                    $height = Mage::helper('catalog/image')->init($_product, 'image')->getOriginalHeight();
                    $_href = sprintf(" href=\"javascript:void(0);\" onclick=\"renderBundle('%s', %d);\" style=\"display:block;\"", $_product->getId(), ($height + 40));

                }
                elseif ($lookbook->getBundleClick() == 3 )
                {
                    $_href = sprintf(" href='%s' %s", $clickToUrl, $newTarget);
                }
                ?>
                <div class="swiper-slide">
                    <?php if ($lookbook->getBundleClick()): ?>
                        <a <?php echo $_href; ?>>
                    <?php endif; ?>
                    <img class="lookImg" src="<?php echo $img; ?>" alt="<?php $_product->getName(); ?>" />
                    <?php if ($lookbook->getShowShopPix()): ?>
                        <?php
                        $relMediaPath = substr(Mage::getBaseDir('media'), strlen(Mage::getBaseDir()) );
                        $imageUrl = sprintf("%s/lookbook%s", $relMediaPath, $lookbook->getShopPix());
                        ?>
                        <div class="lookDesc">
                            <img src="<?php echo $imageUrl; ?>" alt="<?php echo $this->__('Shop'); ?>" />
                        </div>
                    <?php endif; ?>
                    <?php if ($lookbook->getBundleClick()): ?>
                        </a>
                    <?php endif; ?>
                    <!-- Display configurable products links if enabled -->
                    <?php if ($underProductDisplay == 1): ?>
                        <div class="childProductsLink">
                            <?php $childProductsLinks = Mage::helper('lookbook')->getChildProductsLink($_product); ?>
                            <?php $cnt = 1; ?>
                            <?php foreach ($childProductsLinks as $childProductLink): ?>
                                <?php
                                $class = "";
                                $productLink = "";
                                ?>
                                <?php if (array_key_exists('link', $childProductLink)): ?>
                                    <?php
                                    $class = "available";
                                    $name = $childProductLink['name'];
                                    if ($includePrice && array_key_exists('price', $childProductLink)) {
                                        $name = sprintf("%s %s", $name, $childProductLink['price']);
                                    }
                                    $productLink = sprintf("%s<a %s href=\"%s\">%s</a>", $underProductLinksAvailablePrefix, $newTarget, $childProductLink['link'], $name);
                                    ?>
                                <?php else: ?>
                                    <?php
                                    $class = "unavailable";
                                    $name = sprintf("%s", $childProductLink['name']);
                                    if ($underProductLinksContact) {
                                        $subject = "";
                                        if ($underProductLinksSubject) {
                                            $newName = Mage::helper('lookbook')->stripPrice($name);
                                            $subject = "?subject=" . rawurlencode(preg_replace("/%PRODUCT_NAME%/i", "$newName", $underProductLinksSubject));
                                        }
                                        $productLink = sprintf("%s <a href=\"mailto:%s%s\">%s</a>", $underProductLinksUnavailablePrefix, $underProductLinksContact, $subject, $newName);
                                    }
                                    else {
                                        $productLink = $name;
                                    }
                                    ?>
                                <?php endif; ?>
                                <div class='link <?php echo $class; ?>'>
                                    <?php echo $productLink; ?><br/>
                                </div>
                                <?php if ($cnt++ >= $lookDescMaxLines) break; ?>
                            <?php endforeach; ?>
                        </div>
                    <?php elseif ($underProductDisplay == 3): ?>
                        <div class="product_description"><?php echo nl2br(rtrim(strip_tags($_product->getDescription()))); ?></div>
                    <?php endif; ?>

                    <?php if ($lookbook->getShowLookNumber()): ?>
                        <div class='numberedBoxes' id="num<?php echo sprintf("%02d", $num); ?>">
                            <?php echo sprintf("%02d", $num); ?></div>
                    <?php endif; ?>
                </div>
            <?php
            } //endforeach
        }
        else
        {
            // Loop through looks
            foreach ($_imageCollection as $_image)
            {
                $img = (string)Mage::helper('lookbook/image')->init($lookbook, 'image', $_image['file']);
                ?>
                <div class="swiper-slide">
                    <?php if ($lookbook->getDefaultUrl()): ?>
                    <a <?php echo $newTarget; ?> href="<?php echo $lookbook->getDefaultUrl();?>">
                        <?php endif; ?>
                        <img class="lookImg" src="<?php echo $img; ?>" alt="<?php echo $lookbook->getTitle(); ?>"/>
                        <?php if ($lookbook->getDefaultUrl()): ?>
                    </a>
                <?php endif; ?>
                </div>
            <?php
            } //endforeach
        }
        ?>
    </div>
    <?php if ($lookbookNavType == "scrollbar"): ?>
        <div class="swiper-scrollbar"></div>
    <?php elseif ($lookbookNavType == "fontawesome"):?>
        <div class="pagination-wrapper">
            <div class="pagination pagination-fontawesome"></div>
        </div>
        <span class="nav-button nav-button-left">
            <i class="fa fa-arrow-circle-left"></i>
        </span>
        <span class="nav-button nav-button-right">
            <i class="fa fa-arrow-circle-right"></i>
        </span>
    <?php elseif ($lookbookNavType != "scrollbar" && $lookbookNavType != "dots"): ?>
        <?php if ($arrowStyle): ?>
            <span class="nav-button nav-button-left <?php echo $arrowStyle; ?>"></span>
            <span class="nav-button nav-button-right <?php echo $arrowStyle; ?>"></span>
        <?php else: ?>
            <span class="nav-button nav-button-left">
            <i class="fa fa-arrow-circle-left"></i>
        </span>
            <span class="nav-button nav-button-right">
            <i class="fa fa-arrow-circle-right"></i>
        </span>
        <?php endif; ?>
    <?php endif; ?>
</div> <!-- end lookbook -->

<?php if ($lookbookNavType): ?>
    <?php if ($lookbookNavType == "dots" || $lookbookNavType == "arrows-dots"): ?>
        <div class="pagination-wrapper <?php echo $dotStyle; ?>">
            <div class="pagination"></div>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php if ($lookbook->getShowCredits()): ?>
    <!-- show credits start -->
    <div id="lookbook-credits">
        <!-- Model -->
        <?php if ($model = $lookbook->getModel()): ?>
            <?php echo $this->__('Model: <b>%s</b>', $model); ?>
        <?php endif; ?>
        |
        <!-- Photography -->
        <?php if ($photography = $lookbook->getPhotography()): ?>
            <?php echo $this->__('Photography: <b>%s</b>', $photography); ?>
        <?php endif; ?>
        |
        <!-- Make Up -->
        <?php if ($makeup = $lookbook->getMakeUp()): ?>
            <?php echo $this->__('Make up: <b>%s</b>', $makeup); ?>
        <?php endif; ?>
    </div>
    <!-- show credits end -->
<?php endif; ?>

<script>
var defaultSlidesPerView = <?php echo $looksPerPage; ?>;
var mySwiper = null;
var settings = {
    //Your options here:
    mode: 'horizontal',
    speed: 500,
    calculateHeight: true,
    loop: false,
    slidesPerView: defaultSlidesPerView,
    slidesPerGroup: <?=($lookbook->getData('slides_per_group')) ? $lookbook->getData('slides_per_group') : 1?>,
    <?php if ($lookbookNavType): ?>
    <?php if ($lookbookNavType == "scrollbar"): ?>
    scrollbar: '.swiper-scrollbar',
    scrollbarHide: false,
    <?php elseif ($lookbookNavType == "fontawesome" || $lookbookNavType == "dots" || $lookbookNavType == "arrows-dots"): ?>
    pagination: '.pagination',
    paginationClickable: true,
    <?php endif; ?>
    <?php endif; ?>
    loop: false,
    <?php if ($lookbookNavType != "dots" || $lookbookNavType != "scrollbar"): ?>
    onSlideChangeEnd: function (mySwiper) {
        if (mySwiper.isBeginning)
        {
            jQuery('.nav-button-left').css('display', 'none');
        }
        else if(mySwiper.isEnd)
        {
            jQuery('.nav-button-right').css('display', 'none');
        }
        else{
            jQuery('.nav-button-left').css('display','block');
            jQuery('.nav-button-right').css('display','block');
        }
    },
    <?php endif; ?>
    onClick: function (mySwiper) {
        // Create a 60 days expiry date
        var expiryDate = new Date();
        expiryDate.setDate(expiryDate.getDate() + 60);
        // Get the last slide index
        var lastIndex = mySwiper.activeIndex;
        // Save them in cookies
        Mage.Cookies.set('lastIndex-<?php echo $lookbook->getId() ?>', lastIndex, expiryDate);
    },
    onInit: function (mySwiper) {
        if (jQuery('.nav-button-left').length > 0){
            jQuery('.nav-button-left').css('display', 'none');
        }
        jQuery('.pagination').css('left', 'calc(50% - ' + (jQuery('.pagination').width() / 2) + 'px)');
    }
    <?php if ($lookbookNavType != "dots" || $lookbookNavType != "scrollbar"): ?>
    ,
    nextButton: '.nav-button-right',
    prevButton: '.nav-button-left'
    <?php endif; ?>
};

function adjustSlidesPerView(){
    if (jQuery(window).width() <= 480 && defaultSlidesPerView != 1){
        settings.slidesPerView = 1;
    }else if (jQuery(window).width() <= 768 && defaultSlidesPerView > 2){
        settings.slidesPerView = 2;
    }else{
        settings.slidesPerView = defaultSlidesPerView;
    }
}

jQuery(document).ready(function(){
    adjustSlidesPerView();
    mySwiper = new Swiper('.swiper-container',settings);
    var height = 0;
    var setSwiperHight = setInterval(function(){
        height = Math.floor(jQuery('.lookImg').first().height()/2-25);
        if (height != 0){
            jQuery(".nav-button").css('top',height+'px');
            clearInterval(setSwiperHight);
        }
    },1000);
    jQuery('.swiper-pagination-switch:gt('+(jQuery('.swiper-slide').length - <?php echo $looksPerPage; ?> ) +')').css('display','none') ;

    <!-- Enable Zoom -->
    <?php if ($lookbook->getZoomOnHover()): ?>
    jQuery(function() {
        jQuery("div#lookbook ul#menu li img.lookImg").bubbleup({tooltip: false, scale:<?php echo $lookWidth; ?>+10});
    });
    <?php endif; ?>
});

jQuery(window).resize(function(){
    adjustSlidesPerView();
    var height = Math.floor(jQuery('.lookImg').first().height()/2-25);
    if (height != 0){
        jQuery(".nav-button").css('top',height+'px');
    }
});
</script>

<?php if ($lookbook->getLookbookFacebook() || ($this->getFacebook())): ?>
    <style type="text/css">
        body, .page-empty{padding:0;}
        <?php if ($lookbook->getFacebookCss()) echo $lookbook->getFacebookCss(); ?>
    </style>
    <script type="text/javascript" src="https://connect.facebook.net/en_US/all.js"></script>
    <script type="text/javascript">
        FB.init({
            appId      : '<?=$lookbook->getFacebookAppId()?>',
        });
        setTimeout(function(){
            FB.Canvas.setAutoGrow();
        },500);

        FB.Event.subscribe('edge.create', function(href, widget) {
            window.location.reload();
        });
    </script>
<?php elseif ($lookbook->getSiteCss()): ?>
    <style type="text/css">
        <?php echo $lookbook->getSiteCss()?>
    </style>
<?php endif; ?>

<?php elseif ($lookbookLayout == "grid"): ?>
    <div class="lookbook-grid">
        <?php
        if ($lookbookType == "category")
        {
            // Loop through looks
            $num = 0;
            foreach ($_productCollection as $_product)
            {
                $num++;
                // Get original image as their resolution is ready for lookbook
                $img = (string)Mage::helper('catalog/image')->init($_product, 'image');
                $height = Mage::helper('catalog/image')->init($_product, 'image')->getOriginalHeight()
                ?>
                <div class="lookbook-grid-item">
                    <?php if ($lookbook->getBundleClick() == 1): ?>
                        <?php $includeRenderBundleJs = true; ?>
                        <a onclick="renderBundle('<?php echo $_product->getId(); ?>', <?php echo ($height + 10); ?>);" href="javascript:void(0);">
                    <?php endif; ?>
                        <img class="lookImg" src="<?php echo $img; ?>" alt="<?php $_product->getName(); ?>" />
                    <?php if ($lookbook->getShowShopPix()): ?>
                        <?php
                        $relMediaPath = substr(Mage::getBaseDir('media'), strlen(Mage::getBaseDir()) );
                        $imageUrl = sprintf("%s/lookbook%s", $relMediaPath, $lookbook->getShopPix());
                        ?>
                        <div class="lookDesc">
                            <img src="<?php echo $imageUrl; ?>" alt="<?php echo $this->__('Shop'); ?>" />
                        </div>
                    <?php endif; ?>
                    <?php if ($lookbook->getBundleClick() == 1): ?>
                        </a>
                    <?php endif; ?>
                    <!-- Display configurable products links if enabled -->
                    <?php if ($underProductDisplay == 1): ?>
                        <div class="childProductsLink">
                            <?php $childProductsLinks = Mage::helper('lookbook')->getChildProductsLink($_product); ?>
                            <?php $cnt = 1; ?>
                            <?php foreach ($childProductsLinks as $childProductLink): ?>
                                <?php if (array_key_exists('link', $childProductLink)): ?>
                                    <?php
                                    $name = $childProductLink['name'];
                                    if ($includePrice && array_key_exists('price', $childProductLink)) {
                                        $name = sprintf("%s %s", $name, $childProductLink['price']);
                                    }
                                    ?>
                                    <a <?php echo $newTarget; ?> href="<?php echo $childProductLink['link'] ?>"><?php echo $name ?></a><br/>
                                <?php else: ?>
                                    <?php echo $childProductLink['name'] ?><br/>
                                <?php endif; ?>
                                <?php if ($cnt++ >= $lookDescMaxLines) break; ?>
                            <?php endforeach; ?>
                        </div>
                    <?php elseif ($underProductDisplay == 3): ?>
                        <div class="product_description"><?php echo nl2br(rtrim(strip_tags($_product->getDescription()))); ?></div>
                    <?php endif; ?>

                    <?php if ($lookbook->getShowLookNumber()): ?>
                        <div class='numberedBoxes' id="num<?php echo sprintf("%02d", $num); ?>">
                            <?php echo sprintf("%02d", $num); ?></div>
                    <?php endif; ?>
                </div>
                <?php
            } //endforeach
        }
        else
        {
            // Loop through looks
            foreach ($_imageCollection as $_image)
            {
                $img = (string)Mage::helper('lookbook/image')->init($lookbook, 'image', $_image['file']);
                ?>
                <div class="lookbook-grid-item">
                    <?php if ($lookbook->getDefaultUrl()): ?>
                        <a <?php echo $newTarget; ?> href="<?php echo $lookbook->getDefaultUrl();?>">
                    <?php endif; ?>
                    <img class="lookImg" src="<?php echo $img; ?>" alt="<?php echo $lookbook->getTitle(); ?>"/>
                    <?php if ($lookbook->getDefaultUrl()): ?>
                        </a>
                    <?php endif; ?>
                </div>
                <?php
            } //endforeach
        }
        ?>
    </div>
<?php endif; ?>

<?php if ($includeRenderBundleJs): ?>
    <script type="text/javascript">
        function renderBundle(product_id, height)
        {
            if (height > jQuery(window).height()) {
                height = jQuery(window).height();
            }

            var url = "<?php echo Mage::getUrl("lookbook/index/bundle", array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on'))); ?>id/" + product_id;
            var $dialog = jQuery('<div></div>')
                .html('<iframe id="bundle-iframe" style="border:0px; overflow:hidden;" src="' + url + '" width="100%" height="100%"></iframe>')
                .dialog({
                    autoOpen: false,
                    modal: true,
                    height: height,
                    dialogClass: "bundle-dialog",
                    width: <?php echo $lookBundleWindowWidth; ?>
                });
            $dialog.dialog('open');

            jQuery('#bundle-iframe').load(function(){
                var contentHeight = jQuery('#bundle-iframe').contents().find('.lookbook-index-bundle').height();
                $dialog.height(contentHeight + 20);
                jQuery('#bundle-iframe').contents().find('html').css('overflow','hidden');
            });
        }
    </script>
<?php endif; ?>