<?php
$relMediaPath = substr(Mage::getBaseDir('media'), strlen(Mage::getBaseDir()) );
$imagePath = sprintf("%s/homepage%s", Mage::getBaseDir('media'), $this->getImage()->getUrl());
$imageUrl = sprintf("%s/homepage%s", $relMediaPath, $this->getImage()->getUrl());
if (is_file($imagePath)) {
	list($width, $height, $type, $attr) = getimagesize($imagePath); ?>
	<?php if ($link = $this->getImage()->getLink()): ?>
		<a <?php if ($this->getImage()->getPopup()): ?>target="_blank" <?php endif; ?>href="<?php echo $link ?>">
	<?php endif; ?>
		<img <?php echo $attr; ?> src="<?php echo $imageUrl ?>" alt="<?php echo $this->getImage()->getAlt(); ?>" /> 
	<?php if ($link): ?>
		</a>
	<?php endif; ?>
<?php } // endif ?>