<?php
/**
 * Based on /app/code/design/adminhtml/default/default/template/catalog/product/helper/gallery.phtml
 */
?>
<?php
/**
 * Template for block FactoryX_Lookbook_Block_Adminhtml_Edit_Tab_Media_Gallery_Content
 */
?>
<?php
$_block = $this;
/* @var $_block FactoryX_Lookbook_Block_Adminhtml_Edit_Tab_Media_Gallery_Content */
?>
<div id="<?php echo $_block->getHtmlId() ?>" >
    <div class="grid">
        <table cellspacing="0" class="data border" id="<?php echo $_block->getHtmlId() ?>_grid" width="100%">
            <col width="1" />
            <col />
            <col width="70" />
            <?php foreach ($_block->getImageTypes() as $typeId=>$type): ?>
                <col style="display:none"/>
            <?php endforeach; ?>
            <col width="70" />
            <col width="70" />
            <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('catalog')->__('Image') ?></th>
                <th><?php echo Mage::helper('catalog')->__('Label') ?></th>
                <th><?php echo Mage::helper('catalog')->__('Sort Order') ?></th>
                <?php foreach ($_block->getImageTypes() as $typeId=>$type): ?>
                    <th style="display:none"><?php echo $type['label'] ?></th>
                <?php endforeach; ?>
                <th><?php echo Mage::helper('catalog')->__('Exclude') ?></th>
                <th class="last"><?php echo Mage::helper('catalog')->__('Remove') ?></th>
            </tr>
            </thead>
            <tbody id="<?php echo $_block->getHtmlId() ?>_list">
            <tr id="<?php echo $_block->getHtmlId() ?>_template" class="template no-display">
                <td class="cell-image"><div class="place-holder" onmouseover="<?php echo $_block->getJsObjectName(); ?>.loadImage('__file__')"><span><?php echo Mage::helper('catalog')->__('Roll Over for preview') ?></span></div><img src="<?php echo $this->getSkinUrl('images/spacer.gif')?>" width="100" style="display:none;" alt="" /></td>
                <td class="cell-label"><input type="text" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                <td class="cell-position"><input type="text" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> class="input-text validate-number" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                <?php foreach ($_block->getImageTypes() as $typeId=>$type): ?>
                    <td style="display:none" class="cell-<?php echo $typeId ?> a-center"><input <?php if($_block->getElement()->getAttributeReadonly($typeId)) :?> disabled="disabled" <?php endif;?> type="radio" name="<?php echo $type['field'] ?>" onclick="<?php echo $_block->getJsObjectName(); ?>.setProductImages('__file__')" value="__file__" /></td>
                <?php endforeach; ?>
                <td class="cell-disable a-center"><input type="checkbox" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                <td class="cell-remove a-center last"><input type="checkbox" <?php if($_block->getElement()->getReadonly()):?> disabled="disabled"<?php endif;?> onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
            </tr>
            <tr id="<?php echo $_block->getHtmlId() ?>-image-0">
                <td class="cell-image"><?php echo Mage::helper('catalog')->__('No image') ?></td>
                <td class="cell-label"><input type="hidden" />&nbsp;</td>
                <td class="cell-position"><input type="hidden" />&nbsp;</td>
                <?php foreach ($_block->getImageTypes() as $typeId=>$type): ?>
                    <td style="display:none" class="cell-<?php echo $typeId ?> a-center"><input type="radio" <?php if($_block->getElement()->getAttributeReadonly($typeId)) :?> disabled="disabled" <?php endif;?> name="<?php echo $type['field'] ?>" onclick="<?php echo $_block->getJsObjectName(); ?>.setProductImages('no_selection')" value="no_selection" /></td>
                <?php endforeach; ?>
                <td class="cell-disable"><input type="hidden" />&nbsp;</td>
                <td class="cell-remove last"><input type="hidden" />&nbsp;</td>
            </tr>
            </tbody>
            <?php if (!$_block->getElement()->getReadonly()):?>
                <tfoot>
                <tr>
                    <td colspan="100" class="last" style="padding:8px">
                        <?php echo $_block->getUploaderHtml() ?>
                    </td>
                </tr>
                </tfoot>
            <?php endif;?>
        </table>
    </div>
</div>
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save" name="<?php echo $_block->getElement()->getName() ?>[images]" value="<?php echo $_block->htmlEscape($_block->getImagesJson()) ?>" />
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save_image" name="<?php echo $_block->getElement()->getName() ?>[values]" value="<?php echo $_block->htmlEscape($_block->getImagesValuesJson()) ?>" />
<script type="text/javascript">
    //<![CDATA[
    <?php if (class_exists("Mage_Uploader_Block_Abstract")): ?>
    var <?php echo $_block->getJsObjectName(); ?> = new Product.Gallery('<?php echo $_block->getHtmlId() ?>', <?php echo $_block->getImageTypesJson() ?>);
    <?php else: ?>
    var <?php echo $_block->getJsObjectName(); ?> = new Product.Gallery('<?php echo $_block->getHtmlId() ?>', <?php if ($_block->getElement()->getReadonly()):?>null<?php else:?><?php echo $_block->getUploader()->getJsObjectName() ?><?php endif;?>, <?php echo $_block->getImageTypesJson() ?>);
    <?php endif; ?>
    //]]>
</script>