<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3 class="icon-head head-auspost"><?php echo Mage::helper('shippedfrom')->__('Auspost Shipments') ?></h3>
            </td>
            <td class="a-right">
                <?php echo $this->getProcessPendingButtonHtml() ?>
                <?php echo $this->getProcessPendingLabelsButtonHtml() ?>
                <?php echo $this->getProcessManifestsButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getGridHtml() ?>
</div>