<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <div class="modal fade" id="ajaxloginModal" tabindex="-1" role="dialog" aria-labelledby="ajaxloginModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-times"></i><?php else: ?>&times;<?php endif; ?></span></button>
                    <h4 class="modal-title" id="ajaxloginModal"><?php echo $this->__('Login into your Account') ?></h4>
                </div>
                <div class="modal-body">
                    <form action="<?php echo $this->getUrl('ajaxlogin/index/login', array('_secure'=>true)) ?>" method="post" id="ajaxlogin-login-form">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon">@</span>
                                <input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="form-control input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" placeholder="<?php echo $this->__('Email Address') ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="password" name="login[password]" class="form-control input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" placeholder="<?php echo $this->__('Password') ?>" />
                        </div>
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('form.additional.info.login'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                        <div class="buttons-set row">
                            <div class="col-lg-4 col-md-4 col-xs-3 col-sm-4">
                                <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left ajaxlogin-forgot"><?php echo $this->__('Forgot Your Password?') ?></a>
                            </div>
                            <div class="progress-indicator col-lg-2 col-md-2 col-sm-2 col-xs-2">
                                <span class="please-wait" id="login-please-wait" style="display:none;">
                                    <?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-spinner fa-pulse"></i><?php else: ?><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="Loading"/><?php endif; ?>
                                </span>
                            </div>
                            <div class="col-lg-3 col-md-3 col-xs-4 col-sm-3">
                                <button type="button" class="btn btn-default button ajaxlogin-account" title="<?php echo $this->__('No Account Yet ?') ?>" name="noaccount"><span><span><?php echo $this->__('No Account Yet ?') ?></span></span></button>
                            </div>
                            <div class="col-lg-3 col-md-3 col-xs-3 col-sm-3 text-right">
                                <button type="submit" class="btn btn-primary button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                            </div>
                        </div>
                    </form>
                    <script type="text/javascript">
                        //<![CDATA[
                        var ajaxLoginForm = new VarienForm('ajaxlogin-login-form', true);
                        //]]>
                    </script>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <div class="modal fade" id="ajaxforgotModal" tabindex="-1" role="dialog" aria-labelledby="ajaxforgotModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-times"></i><?php else: ?>&times;<?php endif; ?></span></button>
                    <h4 class="modal-title" id="ajaxforgotModalLabel"><?php echo $this->__('Forgot Your Password?') ?></h4>
                </div>
                <div class="modal-body">
                    <form action="<?php echo $this->getUrl('ajaxlogin/index/forgotpassword', array('_secure'=>true)) ?>" method="post" id="ajaxlogin-forgot-password-form">
                        <div class="content">
                            <?php
                            $customerHelper = Mage::helper('customer');
                            if (method_exists($customerHelper, 'generateResetPasswordLinkToken')) : ?>
                                <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
                            <?php else: ?>
                                <p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
                            <?php endif; ?>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon">@</span>
                                    <input type="text" name="email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" id="email_address" class="form-control input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" placeholder="<?php echo $this->__('Email Address') ?>" />
                                </div>
                            </div>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                            <?php echo $this->getChildHtml('form.additional.info.forgotpassword'); ?>
                        </div>
                        <div class="buttons-set row">
                            <div class="progress-indicator col-md-6 col-lg-6 col-xs-6 col-sm-6">
                                <span class="please-wait" id="forgot-please-wait" style="display:none;">
                                    <?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-spinner fa-pulse"></i><?php else: ?><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="Loading"/><?php endif; ?>
                                </span>
                            </div>
                            <div class="col-lg-6 col-md-6 col-xs-6 col-sm-6 text-right">
                                <button type="submit" class="btn btn-primary button" title="<?php echo $this->__('Submit') ?>" name="send" id="btn-forgot"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                            </div>
                        </div>
                    </form>
                    <script type="text/javascript">
                        //<![CDATA[
                        var ajaxForgotForm = new VarienForm('ajaxlogin-forgot-password-form', true);
                        //]]>
                    </script>
                </div>
                <div class="modal-footer">
                    <a href="<?php echo $this->helper('customer')->getLoginUrl() ?>" class="btn btn-default ajaxlogin-login"><?php echo $this->__('Back to Login') ?></a>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <div class="modal fade" id="ajaxcreateModal" tabindex="-1" role="dialog" aria-labelledby="ajaxcreateModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-times"></i><?php else: ?>&times;<?php endif; ?></span></button>
                    <h4 class="modal-title" id="ajaxcreateModalLabel"><?php echo $this->__('Create an Account') ?></h4>
                </div>
                <div class="modal-body">
                    <form action="<?php echo $this->getUrl('ajaxlogin/index/create', array('_secure'=>true)) ?>" method="post" id="ajaxlogin-create-form">
                        <?php echo $this->getChildHtml(); ?>
                    </form>
                    <script type="text/javascript">
                        //<![CDATA[
                        var ajaxCreateForm = new VarienForm('ajaxlogin-create-form', true);
                        //]]>
                    </script>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <div class="modal fade" id="ajaxlogoutModal" tabindex="-1" role="dialog" aria-labelledby="ajaxlogoutModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-times"></i><?php else: ?>&times;<?php endif; ?></span></button>
                    <h4 class="modal-title" id="ajaxlogoutModalLabel"><?php echo $this->__('Logout from your Account') ?></h4>
                </div>
                <div class="modal-body">
                    <form action="<?php echo $this->getUrl('ajaxlogin/index/logout', array('_secure'=>true)) ?>" method="post" id="ajaxlogin-logout-form">
                        <div class="content">
                            <p><?php echo $this->__('Are you sure you want to log out ?') ?></p>
                        </div>
                        <div class="buttons-set row">
                            <div class="progress-indicator col-lg-6 col-md-6 col-xs-6 col-sm-6">
                                <span class="please-wait" id="login-please-wait" style="display:none;">
                                    <?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-spinner fa-pulse"></i><?php else: ?><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="Loading"/><?php endif; ?>
                                </span>
                            </div>
                            <div class="col-lg-6 col-md-6 col-xs-6 col-sm-6 text-right">
                                <button type="submit" class="btn btn-primary button" title="<?php echo $this->__('Logout') ?>" name="send" id="send2"><span><span><?php echo $this->__('Logout') ?></span></span></button>
                            </div>
                        </div>
                    </form>
                    <script type="text/javascript">
                        //<![CDATA[
                        var ajaxLogoutForm = new VarienForm('ajaxlogin-logout-form', true);
                        //]]>
                    </script>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php if (Mage::getConfig()->getModuleConfig('Mage_Persistent')) : ?>
    <?php
    $isActive = Mage::getConfig()->getNode('modules/Mage_Persistent/active');
    if (!$isActive || !in_array((string)$isActive, array('true', '1'))) {
        return false;
    }
    ?>

    <?php if (Mage::helper('persistent/session')->isPersistent() && !Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <?php $customer = Mage::helper('persistent/session')->getCustomer(); ?>
        <div class="modal fade" id="persistent-cart-window" tabindex="-1" role="dialog" aria-labelledby="persistentModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-times"></i><?php else: ?>&times;<?php endif; ?></span></button>
                        <h4 class="modal-title" id="ajaxlogoutModalLabel"><?php echo Mage::helper('persistent')->__('Welcome, %s!', Mage::helper('core')->escapeHtml($customer->getName(), null)) ?></h4>
                    </div>
                    <div class="modal-body">
                        <div class="content">
                            <p><?php
                                echo Mage::helper('ajaxlogin')->__(
                                    'You are browsing our store as %s %s',
                                    $customer->getName(),
                                    $this->getLayout()->createBlock('persistent/header_additional')->toHtml()
                                );
                                ?></p>
                            <p><?php
                                $login    = $this->__('Login');
                                $register = $this->__('Register');
                                echo Mage::helper('ajaxlogin')->__(
                                    'Please %s or %s a new account to place order.',
                                    "<a href='" . $this->getUrl('customer/account/login') . "' class='ajaxlogin-login'>" . $login . "</a>",
                                    "<a href='" . $this->getUrl('persistent/index/saveMethod') . "' class='ajaxlogin-register'>" . $register . "</a>"
                                );
                                ?></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            //<![CDATA[
            if (jQuery('#persistent-cart-window') && jQuery('#persistent-cart-window').up().up().next('.close'))
            {
                jQuery('#persistent-cart-window').up().up().next('.close').click(function(event) {
                    if (!Mage.Cookies.get("hasPersistentBeenClosed"))
                    {
                        // Create the expiry date
                        var expiryDate = new Date();
                        expiryDate.setDate(expiryDate.getDate() + <?php echo ( Mage::helper('persistent')->getLifeTime() / 86400 ) ?>);
                        // Call the set method
                        Mage.Cookies.set('hasPersistentBeenClosed', true, expiryDate);
                    }
                });
            }
            //]]>
        </script>

    <?php endif; ?>
<?php endif; ?>

<?php
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$url = Mage::getSingleton('core/url')->parseUrl($currentUrl);
$path = $url->getPath();
?>

<script type="text/javascript">
    var currentPath = '<?php echo $path; ?>';
</script>
