    <fieldset>
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <?php if (version_compare(Mage::getVersion(),"1.9.2.2",">=")): ?>
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <?php endif; ?>
        <legend><?php echo $this->__('Personal Information') ?></legend>
        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
        <div class="col-md-12 col-lg-12 col-xs-12 col-sm-12">
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">@</span>
                    <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" placeholder="<?php echo $this->__('Email Address') ?>" class="form-control input-text validate-email required-entry" />
                </div>
            </div>
        </div>
        <?php if ($this->isNewsletterEnabled()): ?>
            <div class="col-md-12 col-lg-12 col-xs-12 col-sm-12">
                <div class="checkbox">
                    <label for="is_subscribed">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> />
                        <?php echo $this->__('Sign Up for Newsletter') ?>
                    </label>
                </div>
            </div>
        <?php endif ?>
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?>
            </div>
        <?php endif ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?>
            </div>
        <?php endif ?>
    </fieldset>
    <?php if($this->getShowAddressFields()): ?>
        <fieldset>
            <input type="hidden" name="create_address" value="1" />
            <legend><?php echo $this->__('Address Information') ?></legend>
            <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
                <div class="form-group">
                    <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" placeholder="<?php echo $this->__('Company') ?>" class="form-control input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
                <div class="form-group">
                    <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" placeholder="<?php echo $this->__('Telephone') ?>" class="form-control input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                </div>
            </div>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                <div class="form-group">
                    <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" placeholder="<?php echo $this->__('Street Address') ?>" id="street_1" class="form-control input-text <?php echo $_streetValidationClass ?>" />
                </div>
            </div>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                    <div class="form-group">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" placeholder="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="form-control input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </div>
            <?php endfor; ?>
            <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
                <div class="form-group">
                    <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" placeholder="<?php echo $this->__('City') ?>" class="form-control input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
                <div class="form-group">
                    <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="form-control validate-select" style="display:none;">
                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>
                    <script type="text/javascript">
                        //<![CDATA[
                        $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                        //]]>
                    </script>
                    <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" placeholder="<?php echo $this->__('State/Province') ?>" class="form-control input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
                <div class="form-group">
                    <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" placeholder="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="form-control input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
                <div class="form-group">
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <?php echo $this->getCountryHtmlSelect() ?>
                </div>
            </div>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </fieldset>
    <?php endif; ?>
    <fieldset>
        <legend><?php echo $this->__('Login Information') ?></legend>
        <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
            <div class="form-group">
                <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" placeholder="<?php echo $this->__('Password') ?>" class="form-control input-text required-entry validate-password" />
            </div>
        </div>
        <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
            <div class="form-group">
                <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" placeholder="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="form-control input-text required-entry validate-cpassword" />
            </div>
        </div>
        <?php echo $this->getChildHtml('form.additional.info'); ?>
        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
    </fieldset>
    <div class="buttons-set row">
        <div class="progress-indicator col-md-6 col-lg-6 col-xs-6 col-sm-6">
            <span class="please-wait" id="create-please-wait" style="display:none;">
                <?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-spinner fa-pulse"></i><?php else: ?><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="Loading"/><?php endif; ?>
            </span>
        </div>
        <div class="col-lg-6 col-md-6 col-xs-6 col-sm-6 text-right">
            <button type="submit" class="btn btn-primary button" title="<?php echo $this->__('Submit') ?>" name="create" id="create"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    <?php if($this->getShowAddressFields()): ?>
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    <?php endif; ?>
    //]]>
</script>
