<?php
	// Set images
	$this->getChild('left')->setData('image', $this->getLeft());
	$this->getChild('left')->setData('over', $this->getOverLeft());
	$this->getChild('right1')->setData('image', $this->getRight1());
	$this->getChild('right1')->setData('over', $this->getOverRight1());
	$this->getChild('right2')->setData('image', $this->getRight2());
	$this->getChild('right2')->setData('over', $this->getOverRight2());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td rowspan="2"><?php echo $this->getChildHtml('left', false) // LEFT ?></td>
		<td><?php echo $this->getChildHtml('right1', false) // RIGHT1 ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('right2', false) // RIGHT2 ?></td>
	</tr>
</table>