<?php
	// Set images
	$this->getChild('left')->setData('image', $this->getLeft());
	$this->getChild('middle')->setData('image', $this->getMiddle());
	$this->getChild('right')->setData('image', $this->getRight());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('left', false) // LEFT ?></td>
		<td><?php echo $this->getChildHtml('middle', false) // MIDDLE ?></td>
		<td><?php echo $this->getChildHtml('right', false) // RIGHT ?><
	</tr>
</table>