<?php
	// Set images
	$this->getChild('top')->setData('image', $this->getTop());
	$this->getChild('top')->setData('over', $this->getOverTop());
	$this->getChild('middle')->setData('image', $this->getMiddle());
	$this->getChild('middle')->setData('over', $this->getOverMiddle());
	$this->getChild('bottom')->setData('image', $this->getBottom());
	$this->getChild('bottom')->setData('over', $this->getOverBottom());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('top', false) // TOP ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('middle', false) // MIDDLE ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('bottom', false) // BOTTOM ?></td>
	</tr>
</table>