<?php
	// Set images
	$this->getChild('left1')->setData('image', $this->getLeft1());
	$this->getChild('left2')->setData('image', $this->getLeft2());
	$this->getChild('right')->setData('image', $this->getRight());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('left1', false) // LEFT1 ?></td>
		<td rowspan="2"><?php echo $this->getChildHtml('right', false) // RIGHT ?></td>
	</tr>
	<tr>
		<td><?php echo $this->getChildHtml('left2', false) // LEFT2 ?></td>
	</tr>
</table>