<?php
	// Set images
	$this->getChild('bottom')->setData('image', $this->getBottom());
	$this->getChild('bottom')->setData('over', $this->getOverBottom());
	$this->getChild('slider')->setData('slides', $this->getSlides());
	// Set slider speed
	$this->getChild('slider')->setData('speed', $this->getSliderSpeed());
	$this->getChild('slider')->setData('nav', $this->getSliderNav());
	$this->getChild('slider')->setData('pag', $this->getSliderPag());
	$this->getChild('slider')->setData('dir', $this->getSliderOrientation());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<?php echo $this->getChildHtml('slider', false) // SLIDER ?>
<?php echo $this->getChildHtml('bottom', false) // BOTTOM ?>