<?php
	// Set images
	$this->getChild('top1')->setData('image', $this->getTop1());
	$this->getChild('top2')->setData('image', $this->getTop2());
	$this->getChild('bottom')->setData('image', $this->getBottom());
	// Using the false parameter with getChildHtml is to tell not to cache block
?>
<table>
	<tr>
		<td><?php echo $this->getChildHtml('top1', false) // TOP1 ?></td>
		<td><?php echo $this->getChildHtml('top2', false) // TOP22 ?></td>
	</tr>
	<tr>
		<td colspan="2"><?php echo $this->getChildHtml('bottom', false) // BOTTOM ?></td>
	</tr>
</table>