<?php $currentContests = $this->getCollection(); ?>
<div class="page-title">
	<h1><?php echo $this->__('Contests') ?></h1>
</div>
<?php if ($currentContests->getSize()):?>
	<?php echo $this->getPagerHtml(); ?>
	<table id="contestsList">
		<?php foreach($currentContests as $currentContest): ?>
			<tr>
				<td class="contest-image">
                    <a href="<?php echo Mage::getUrl($currentContest->getIdentifier()) ?>">
                        <?php $imageUrl = Mage::getBaseUrl('media') . 'contest' . $currentContest->getListImageUrl(); ?>
                        <img src="<?php echo $imageUrl; ?>" width="250" height="200" alt="<?php echo $currentContest->getTitle(); ?>" />
                    </a>
				</td>
				<td class="contest-info">
					<h2><?php echo $currentContest->getTitle(); ?></h2>
					<?php if ($currentContest->isAutomatic() || ($currentContest->getStartDate != "" && $currentContest->getEndDate != "")): ?>
						<p class="contest-date"><?php echo $this->__('From %s to %s', substr($currentContest->getStartDate(),0,10), substr($currentContest->getEndDate(),0,10)); ?></p>
					<?php elseif($currentContest->getEndDate != ""): ?>
						<p class="contest-date"><?php echo $this->__('Ends on %s', substr($currentContest->getEndDate(),0,10)); ?></p>
					<?php endif; ?>
					<p><?php echo $currentContest->getListText(); ?></p>
					<p><a href="<?php echo Mage::getUrl($currentContest->getIdentifier()) ?>"><?php echo $this->__('Read More >>>'); ?></a></p>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
	<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
	<p><?php echo $this->__('There are no contest running at the moment.'); ?></p>
<?php endif; ?>