<?php
if (!Mage::app()->isSingleStoreMode())
{
	$storeCode = Mage::app()->getStore()->getCode();
	$storeId = Mage::app()->getStore()->getId();
}
else
{
	$storeCode = "";
	$storeId = "";
}
?>
<?php if ($this->hasPopupContest($storeId)): ?>
	<div id="popup" style="display: none;">
		<div id="close-popup">
			<a href="#"><img src="<?php echo $this->getSkinUrl('images/factoryx/contests/popup_close.gif');?>" alt="Close" width="29" height="29" /></a>
		</div>
		<div class="block" id="block-contests-popup">
			<div class="block-content">
				<div id="popup-text">
					<?php echo $this->getPopupText(); ?>
				</div>
				<div id="link-div">
					<a href="<?php echo Mage::getUrl($this->getPopupIdentifier()); ?>">
						<img src="<?php echo $this->getSkinUrl('images/factoryx/contests/popup_button.gif');?>" alt="Click to enter" width="366" height="51" />
					</a>
				</div>
				<div id="terms-link">
					<a href="#">
						<?php echo $this->__('Click here for full terms and conditions') ?>
					</a>
				</div>
			</div>
		</div>

		<script type="text/javascript">
			// Expiry Date
			var expDate = new Date();
			expDate.setDate(expDate.getDate() + 60);
			// Past Date used to erase cookies (notice the -1)
			var eraseDate = new Date();
			eraseDate.setTime(eraseDate.getTime()+(-1*24*60*60*1000));
			// Test if iPad or another touchscreen device
			if ("ontouchstart" in window || "ontouch" in window) 
			{	
				// Bind the touchend event to refuse and hide the popup
				jQuery('#close-popup a').bind('touchstart',function(){
					jQuery('#popup').fadeOut();
					Mage.Cookies.set("hasRefused-<?php echo $this->getPopupContestId(); ?>", true, expDate);
					return false;
				});
				
				// Bind the click event to hide the popup on contest page
				jQuery('#link-div a').bind('touchstart',function(){
					Mage.Cookies.set("hasOpened-<?php echo $this->getPopupContestId(); ?>", true, expDate);
				});
				
				// Bind the touchend event to show the terms
				jQuery('#terms-link a').bind('touchstart',function(){
					popupTerms('<?php echo $storeCode ?>',<?php echo $this->getPopupContestId(); ?>);
					return false;
				});
			}
			else 
			// If it's a normal browser
			{
				// Bind the click event to refuse and hide the popup
				jQuery('#close-popup a').bind('click',function(){
					jQuery('#popup').fadeOut();
					Mage.Cookies.set("hasRefused-<?php echo $this->getPopupContestId(); ?>", true, expDate);
					return false;
				});
				
				// Bind the click event to hide the popup on contest page
				jQuery('#link-div a').bind('click',function(){
					Mage.Cookies.set("hasOpened-<?php echo $this->getPopupContestId(); ?>", true, expDate);
				});
				
				// Bind the touchend event to show the terms
				jQuery('#terms-link a').bind('click',function(){
					popupTerms('<?php echo $storeCode ?>',<?php echo $this->getPopupContestId(); ?>);
					return false;
				});
			}
			// If the contest popup has got referer limitations
			<?php if ($referersLimitation = $this->getReferersLimitation()): ?>
				// We first check if the http referer key is set in the server array
				<?php if (array_key_exists('HTTP_REFERER',$_SERVER)): ?> 
					// We parse the url to get the referer host/domain
					<?php $refererInfo = parse_url($_SERVER['HTTP_REFERER']); ?>
					// We loop through the popup limitations
					<?php foreach ($referersLimitation as $refererLimitation): ?>
						// And check if the referer host contains one of the referer limitation
						<?php if ($refererInfo && strpos($refererInfo['host'], $refererLimitation) !== FALSE): ?>
							// If the cookie is present, the popup is showed
							if(!Mage.Cookies.get("hasSubscribed-<?php echo $this->getPopupContestId(); ?>") && !Mage.Cookies.get("hasRefused-<?php echo $this->getPopupContestId(); ?>"))
							{
								jQuery(document).ready(
									function(){
										// If the customer has just opened the contest page we hide the popup and remove the related cookie
										if (Mage.Cookies.get("hasOpened-<?php echo $this->getPopupContestId(); ?>"))
										{
											Mage.Cookies.set("hasOpened-<?php echo $this->getPopupContestId(); ?>", "", eraseDate);
										}
										else
										{
											jQuery("#popup").fadeIn();
										}
									}
								);
							}
							<?php break; ?>
						<?php endif; ?>
					<?php endforeach; ?>
				<?php endif; ?>
			<?php else: ?>
				// If the cookie is present, the popup is showed
				if(!Mage.Cookies.get("hasSubscribed-<?php echo $this->getPopupContestId(); ?>") && !Mage.Cookies.get("hasRefused-<?php echo $this->getPopupContestId(); ?>"))
				{
					jQuery(document).ready(
						function(){
							// If the customer has just opened the contest page we hide the popup and remove the related cookie
							if (Mage.Cookies.get("hasOpened-<?php echo $this->getPopupContestId(); ?>"))
							{
								Mage.Cookies.set("hasOpened-<?php echo $this->getPopupContestId(); ?>", "", eraseDate);
							}
							else
							{
								jQuery("#popup").fadeIn();
							}
						}
					);
				}
			<?php endif; ?>
		</script>
	</div>
<?php endif; ?>
