<div id="thankyou">

	<div>
		<h1 class="thanks-title"><?php echo $this->__('Thank you and good luck!!!') ?></h1>
	</div>

</div>

<script type="text/javascript">
function delayedRedirect() {
    var redirectUrl = "<?php echo Mage::getSingleton('customer/session')->getData('thank_you_redirect_url', true); ?>";
    if (redirectUrl) {
        window.location = redirectUrl;
    }
}
window.onload = setTimeout('delayedRedirect()', 2500)
</script>