<div id="thankyou">

	<?php if ($thankYouImageUrl = Mage::getSingleton('core/session')->getData('thank_you_image_url',true)): ?>
		<?php
			$relMediaPath = substr(Mage::getBaseDir('media'), strlen(Mage::getBaseDir()) );
			$imagePath = sprintf("%s/contest%s", Mage::getBaseDir('media'), $thankYouImageUrl);
			$imageUrl = sprintf("%s/contest%s", $relMediaPath, $thankYouImageUrl);
			if (is_file($imagePath)) {
				list($width, $height, $type, $attr) = getimagesize($imagePath);
			?>
				<?php if (!Mage::getSingleton('core/session')->getData('thank_you_link_type')): ?>
					<a href="<?php echo Mage::getSingleton('core/session')->getData('thank_you_redirect_url') ?>">
				<?php endif; ?>
				<img <?php echo $attr; ?> alt="<?php echo $this->__('Thank you and good luck!!!') ?>" src="<?php echo $imageUrl ?>" />
				<?php if (!Mage::getSingleton('core/session')->getData('thank_you_link_type')): ?>
					</a>
				<?php endif; ?>
		<?php } ?>
	<?php else: ?>
		<div>
			<h1 class="thanks-title"><?php echo $this->__('Thank you and good luck!!!') ?></h1>
		</div>
	<?php endif; ?>
	
</div>

<?php if (Mage::getSingleton('core/session')->getData('thank_you_link_type',true)): ?>
	<script type="text/javascript">
		function delayedRedirect() 
		{
			var redirectUrl = "<?php echo Mage::getSingleton('core/session')->getData('thank_you_redirect_url', true); ?>";
			if (redirectUrl) 
			{
				window.location = redirectUrl;
			}
		}
		window.onload = setTimeout('delayedRedirect()', 2500)
	</script>
<?php endif; ?>