<?php
// Get the contest
$contest = $this->getCurrentContest();

// DYNAMIC CSS STYLING
$backgroundColour       = $contest->getBackgroundColour();
$textColour             = $contest->getTextColour();
$buttonBackgroundColour = $contest->getButtonBackgroundColour();
$buttonTextColour       = $contest->getButtonTextColour();

// Terms URL
$termsUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'contests/index/terms/id/'.$contest->getId();
?>
    <style type="text/css">
        #rafPage{
            background-color: <?php echo $backgroundColour?>;
            color: <?php echo $textColour?>;
        }
        #rafPage a{ color: <?php echo $textColour?>;}

        /* Modified Style */
        .row.invert {background-color: <?php echo $textColour?>;color: <?php echo $backgroundColour?>;}
        <?php echo $contest->getCustomCss()?>
    </style>
<?php echo $this->getChildHtml('facebook'); ?>
<?php if (!Mage::app()->isSingleStoreMode()): ?>
    <?php
    $storeCode = Mage::app()->getStore()->getCode();
    ?>
    <?php if ($storeCode == "default"): ?>
        <?php
        $storeCode = "";
        ?>
    <?php endif; ?>
<?php else: ?>
    <?php
    $storeCode = "";
    ?>
<?php endif; ?>
<?php if (!$contest->getId()): ?>
    <h1><?php echo $this->__('Sorry, this contest does not exist, you will be redirect in a few seconds'); ?></h1>
    <script type="text/javascript">
        function delayedRedirect() {
            var redirectUrl = "<?php echo Mage::helper('contests')->getNotFoundRedirectUrl(); ?>";
            if (redirectUrl) {
                window.location = redirectUrl;
            }
        }
        window.onload = setTimeout('delayedRedirect()', 2500)
    </script>
<?php elseif (!$contest->getDisplayed()): ?>
    <div id="rafPage">
        <div class="row" style="margin:0;">
            <?php
            $relMediaPath = substr(Mage::getBaseDir('media'), strlen(Mage::getBaseDir()) );
            $imagePath = sprintf("%s/contest%s", Mage::getBaseDir('media'), $contest->getImageUrl());
            $imageUrl = sprintf("%s/contest%s", $relMediaPath, $contest->getImageUrl());
            ?>
            <?php if (is_file($imagePath)): ?>
                <?php
                list($width, $height, $type, $attr) = getimagesize($imagePath);
                ?>
                <img alt="<?php echo $contest->getTitle(); ?>" src="<?php echo $imageUrl; ?>" />
            <?php endif; ?>
        </div>
        <div class="row center invert nomargin">
            <div class="label" style="padding:10px 0px">
                <?php echo $this->__('Sorry this contest has closed!');?>
            </div>
        </div>
    </div>
<?php elseif ($contest->getType() == 1): ?>
    <div id="rafPage">
        <div class="row" style="margin:0;">
            <?php
            $relMediaPath = substr(Mage::getBaseDir('media'), strlen(Mage::getBaseDir()) );
            $imagePath = sprintf("%s/contest%s", Mage::getBaseDir('media'), $contest->getImageUrl());
            $imageUrl = sprintf("%s/contest%s", $relMediaPath, $contest->getImageUrl());
            ?>
            <?php if (is_file($imagePath)): ?>
                <?php
                list($width, $height, $type, $attr) = getimagesize($imagePath);
                ?>
                <a class="zoomable" target="_blank" rel="noopener noreferrer" href="<?php echo $imageUrl; ?>"><img alt="<?php echo $contest->getTitle(); ?>" src="<?php echo $imageUrl; ?>" /></a>
            <?php endif; ?>
        </div>
        <div>
            <form name="contestForm" id="contestForm" action="<?php echo $this->getFormAction(); ?>" method="post">
                <input type="hidden" id="contest_id" name="contest_id" value="<?php echo $this->getRequest()->getParam('id') ?>" />
                <div class="row center">
                    <div class="label">
                        <?php echo $contest->getPleaseText() ? $contest->getPleaseText() : $this->__('Please Enter Your Details');?>
                    </div>
                </div>
                <div class="row center">
                    <input id="name" name="name" class="input-text required-entry input-text-medium" placeholder="<?php echo $this->__('Your Name')?>"/>
                    <input id="email" name="email" class="input-text required-entry validate-email input-text-medium"  placeholder="<?php echo $this->__('Your Email')?>"/>
                    <input id="mobile" name="mobile" class="input-text validate-number input-text-medium" placeholder="<?php echo $this->__('Your Mobile Number')?>" />
                    <?php if ($contest->getGender()): ?>
                        <select id="gender" name="gender" class="validate-select">
                            <option value="" disabled selected><?php echo $this->__('Gender')?></option>
                            <option value="M"><?php echo $this->__('Male')?></option>
                            <option value="F"><?php echo $this->__('Female')?></option>
                        </select>
                    <?php endif; ?>
                    <select id="state" name="state" class="validate-select">
                        <?php $allowed_states = explode(',',$contest->getStates()); ?>
                        <option value="" selected disabled><?php echo $this->__('Your State')?></option>
                        <?php $states = Mage::helper('contests')->getStates(); ?>
                        <?php foreach($states as $value): ?>
                            <?php if (!in_array($value,$allowed_states)): ?>
                                <?php continue; ?>
                            <?php endif; ?>
                            <option value="<?php echo $value ?>"><?php echo $value ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <?php if ($contest->getIsCompetition()): ?>
                    <div class="row center">
                        <div class="label">
                            <?php echo $contest->getCompetitionText()?>
                        </div>
                    </div>
                    <div class="row center">
                        <?php if ($contest->getCompetitionOptions()): ?>
                            <?php
                            $options = explode(",",$contest->getCompetitionOptions());
                            $width = round(100/count($options), 0, PHP_ROUND_HALF_DOWN)-1;
                            ?>
                            <?php foreach ($options as $option): ?>
                                <div class="choice" style="width:<?php echo $width?>%;" data-choice="<?php echo $option?>"><?php echo $option?></div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <textarea id="competition" name="competition" rows="4" cols="134" class="input-text input-competition required-entry" style="<?php echo ($contest->getCompetitionOptions()) ? "display:none" : "" ?> "></textarea>
                    </div>
                <?php endif; ?>
                <div class="row center">
                    <div class="label">
                        <?php if ($contest->getMoreFriendLine()): ?>
                            <?php
                            echo $contest->getMoreFriendLine();
                            ?>
                        <?php else: ?>
                            <?php
                            echo $this->__('The more friends you refer the more entries you get to the prize draw.');
                            ?>
                        <?php endif; ?>
                    </div>
                </div>
                <?php if ($this->getChildHtml('form.additional.info')): ?>
                    <div class="row center">
                        <div class="label">
                            <?php echo $this->getChildHtml('form.additional.info') ?>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="emailRefereeForm">
                    <div id="emailReferee">
                        <div class="row email">
                            <input type="textbox" name="friend1" id="friend1" class="input-text validate-email" placeholder="Your Friend's Email" />
                        </div>
                    </div>
                    <div class="row email">
                        <a class="email-link" onclick="addEmailField('emailReferee')">+ Add More Friends</a>
                    </div>
                </div>
                <div class="form-control">
                    <div class="row" style="margin-top:0px;margin-bottom:5px;">
                        <input name="terms" id="terms" type="checkbox" checked>
                        <label for="terms"><?php echo $this->__('I have read and agree with the <a href="javascript:void(0);" onclick="popupTerms(\'%s\', %s);">terms and conditions</a>', $storeCode, $contest->getId())?></a></label>
                        <?php if ($contest->getShareOnFacebook()): ?>
                            <?php if ($this->getFacebook()): ?>
                                <?php $urlToShare = "http://www.facebook.com/sharer.php?u=" . urlencode($contest->getFacebookPage() . "app/" . $contest->getFacebookAppId()); ?>
                            <?php else: ?>
                                <?php $urlToShare = "http://www.facebook.com/sharer.php?u=" . urlencode(Mage::helper('core/url')->getCurrentUrl()); ?>
                            <?php endif; ?>
                            <a class="fb-share-button" href="<?php echo $urlToShare ?>" target="_blank" rel="noopener noreferrer">
                                <?php echo $this->__('Share on Facebook'); ?>
                            </a>
                        <?php endif; ?>
                    </div>
                    <button onclick="clearForm(this.form);" title="<?php echo $this->__('Reset') ?>" class="button">
                        <span>
                            <span>
                                <?php echo $this->__('Reset') ?>
                            </span>
                        </span>
                    </button>
                    <button id="btn-enter" type="submit" title="<?php echo $this->__('Enter Now') ?>" class="button">
                        <span>
                            <span>
                                <?php echo $this->__('Enter Now') ?>
                            </span>
                        </span>
                    </button>
                    <div class="row">
                        <?php if ($contest->getStatus() == 2): ?>
                            <?php $jsDate = Mage::helper('contests')->getCountdownFormattedEndDate($contest->getEndDate()); ?>
                            <div class="countdown" id="countdown-container">Closes in <span id="javascript-countdown"></span></div>
                            <script type="text/javascript">
                                // Client side date
                                var nowOnBrowser = new Date();
                                // Client side offset
                                var timezoneOffset = nowOnBrowser.getTimezoneOffset();
                                <?php
                                // Magento store timezone
                                $timezone = Mage::app()->getStore()->getConfig(Mage_Core_Model_Locale::XML_PATH_DEFAULT_TIMEZONE);
                                date_default_timezone_set($timezone);

                                // Magento locale offset
                                $localeOffset = date("Z");
                                ?>
                                // Offset between client and server
                                var finalOffset = timezoneOffset*60 + <?php echo $localeOffset; ?>;
                                if (finalOffset != 0) {
                                    // Convert to hours
                                    finalOffset /= 3600;
                                    // Get offset hours
                                    var finalOffsetHours = Math.floor(finalOffset);
                                    // Get offset minutes
                                    var finalOffsetMinutes = 60*(finalOffset-finalOffsetHours);
                                    // Client side target date
                                    var targetDate = new Date(<?php echo $jsDate['year']?>, <?php echo $jsDate['month']?>, <?php echo $jsDate['day']?>, <?php echo $jsDate['hours']?>, <?php echo $jsDate['minutes']?>); // Jan 1, 2050
                                    // Update client side based on offset
                                    if (finalOffsetHours >= 0) {
                                        targetDate.setHours(targetDate.getHours() - finalOffsetHours);
                                    } else {
                                        targetDate.setHours(targetDate.getHours() + finalOffsetHours);
                                    }
                                    // Repeat for the minutes
                                    if (finalOffsetMinutes >= 0) {
                                        targetDate.setMinutes(targetDate.getMinutes() - finalOffsetMinutes);
                                    } else {
                                        targetDate.setMinutes(targetDate.getMinutes() + finalOffsetMinutes);
                                    }
                                } else {
                                    var targetDate = new Date(<?php echo $jsDate['year']?>, <?php echo $jsDate['month']?>, <?php echo $jsDate['day']?>, <?php echo $jsDate['hours']?>, <?php echo $jsDate['minutes']?>); // Jan 1, 2050
                                }
                                var clock = document.getElementById("javascript-countdown");
                                var refreshIntervalId = setInterval(function(){
                                    var timespan = countdown(null, targetDate);
                                    if (timespan.value > 0) {
                                        clock.innerHTML = timespan.toString();
                                    } else {
                                        jQuery("#countdown-container").html("Closed");
                                        jQuery("#btn-enter").prop('disabled',true);
                                        clearInterval(refreshIntervalId);
                                    }
                                }, 1000);
                            </script>
                        <?php endif; ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
<?php elseif ($contest->getType() == 2): ?>
    <div id="rafPage">
        <div class="row" style="margin:0;">
            <?php
            $relMediaPath = substr(Mage::getBaseDir('media'), strlen(Mage::getBaseDir()) );
            $imagePath = sprintf("%s/contest%s", Mage::getBaseDir('media'), $contest->getImageUrl());
            $imageUrl = sprintf("%s/contest%s", $relMediaPath, $contest->getImageUrl());
            ?>
            <?php if (is_file($imagePath)): ?>
                <?php
                list($width, $height, $type, $attr) = getimagesize($imagePath);
                ?>
                <a class="zoomable" target="_blank" rel="noopener noreferrer" href="<?php echo $imageUrl; ?>"><img alt="<?php echo $contest->getTitle(); ?>" src="<?php echo $imageUrl; ?>" /></a>
            <?php endif; ?>
        </div>
        <div>
            <form name="contestForm" id="contestForm" action="<?php echo $this->getFormAction(); ?>" method="post">
                <input type="hidden" id="contest_id" name="contest_id" value="<?php echo $this->getRequest()->getParam('id') ?>" />
                <div class="row center">
                    <div class="label">
                        <?php echo $contest->getPleaseText() ? $contest->getPleaseText() : $this->__('Please Enter Your Details');?>
                    </div>
                </div>
                <div class="row center">
                    <input id="name" name="name" class="input-text required-entry input-text-medium" placeholder="<?php echo $this->__('Your Name')?>"/>
                    <input id="email" name="email" class="input-text required-entry validate-email input-text-medium"  placeholder="<?php echo $this->__('Your Email')?>"/>
                    <input id="mobile" name="mobile" class="input-text validate-number input-text-medium" placeholder="<?php echo $this->__('Your Mobile Number')?>" />
                    <select id="state" name="state" class="validate-select">
                        <option value="" selected disabled><?php echo $this->__('Your State')?></option>
                        <?php $states = Mage::helper('contests')->getStates(); ?>
                        <?php foreach($states as $key => $value): ?>
                            <option value="<?php echo $key ?>"><?php echo $value ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <?php if ($contest->getIsCompetition()): ?>
                    <div class="row center">
                        <div class="label">
                            <?php echo $contest->getCompetitionText()?>
                        </div>
                    </div>
                    <div class="row center">
                        <?php if ($contest->getCompetitionOptions()): ?>
                            <?php
                            $options = explode(",",$contest->getCompetitionOptions());
                            $width = round(100/count($options), 0, PHP_ROUND_HALF_DOWN)-1;
                            ?>
                            <?php foreach ($options as $option): ?>
                                <div class="choice" style="width:<?php echo $width?>%;" data-choice="<?php echo $option?>"><?php echo $option?></div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <textarea id="competition" name="competition" rows="4" cols="134" class="input-text input-competition required-entry" style="<?php echo ($contest->getCompetitionOptions()) ? "display:none" : "" ?> "></textarea>
                    </div>
                <?php endif; ?>
                <?php if ($this->getChildHtml('form.additional.info')): ?>
                    <div class="row center">
                        <div class="label">
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="form-control">
                    <div class="row" style="margin-top:0px;margin-bottom:5px;">
                        <input name="terms" id="terms" type="checkbox" checked>
                        <label for="terms"><?php echo $this->__('I have read and agree with the <a href="javascript:void(0);" onclick="popupTerms(\'%s\', %s);">terms and conditions</a>', $storeCode, $contest->getId())?></a></label>
                        <?php if ($contest->getShareOnFacebook()): ?>
                            <?php if ($this->getFacebook()): ?>
                                <?php $urlToShare = "http://www.facebook.com/sharer.php?u=" . urlencode($contest->getFacebookPage() . "app/" . $contest->getFacebookAppId()); ?>
                            <?php else: ?>
                                <?php $urlToShare = "http://www.facebook.com/sharer.php?u=" . urlencode(Mage::helper('core/url')->getCurrentUrl()); ?>
                            <?php endif; ?>
                            <a class="fb-share-button" href="<?php echo $urlToShare ?>" target="_blank" rel="noopener noreferrer">
                                <?php echo $this->__('Share on Facebook'); ?>
                            </a>
                        <?php endif; ?>
                    </div>
                    <button onclick="clearForm(this.form);" title="<?php echo $this->__('Reset') ?>" class="button">
                        <span>
                            <span>
                                <?php echo $this->__('Reset') ?>
                            </span>
                        </span>
                    </button>
                    <button id="btn-enter" type="submit" title="<?php echo $this->__('Enter Now') ?>" class="button">
                        <span>
                            <span>
                                <?php echo $this->__('Enter Now') ?>
                            </span>
                        </span>
                    </button>
                    <div class="row">
                        <?php if ($contest->getStatus() == 2): ?>
                            <div class="countdown" id="countdown-container">Closes in <span id="javascript-countdown"></span></div>
                        <?php $jsDate = Mage::helper('contests')->getCountdownFormattedEndDate($contest->getEndDate()); ?>
                            <script type="text/javascript">
                                // Client side date
                                var nowOnBrowser = new Date();
                                // Client side offset
                                var timezoneOffset = nowOnBrowser.getTimezoneOffset();
                                <?php
                                // Magento store timezone
                                $timezone = Mage::app()->getStore()->getConfig(Mage_Core_Model_Locale::XML_PATH_DEFAULT_TIMEZONE);
                                date_default_timezone_set($timezone);
                                // Magento locale offset
                                $localeOffset = date("Z");
                                ?>
                                // Offset between client and server
                                var finalOffset = timezoneOffset*60 + <?php echo $localeOffset; ?>;
                                if (finalOffset != 0) {
                                    // Convert to hours
                                    finalOffset /= 3600;
                                    // Get offset hours
                                    var finalOffsetHours = Math.floor(finalOffset);
                                    // Get offset minutes
                                    var finalOffsetMinutes = 60*(finalOffset-finalOffsetHours);
                                    // Client side target date
                                    var targetDate = new Date(<?php echo $jsDate['year']?>, <?php echo $jsDate['month']; ?>, <?php echo $jsDate['day']?>, <?php echo $jsDate['hours']?>, <?php echo $jsDate['minutes']; ?>); // Jan 1, 2050
                                    // Update client side based on offset
                                    if (finalOffsetHours >= 0) {
                                        targetDate.setHours(targetDate.getHours() - finalOffsetHours);
                                    } else {
                                        targetDate.setHours(targetDate.getHours() + finalOffsetHours);
                                    }
                                    // Repeat for the minutes
                                    if (finalOffsetMinutes >= 0) {
                                        targetDate.setMinutes(targetDate.getMinutes() - finalOffsetMinutes);
                                    } else {
                                        targetDate.setMinutes(targetDate.getMinutes() + finalOffsetMinutes);
                                    }
                                } else {
                                    var targetDate = new Date(<?php echo $jsDate['year']?>, <?php echo $jsDate['month']?>, <?php echo $jsDate['day']?>, <?php echo $jsDate['hours']?>, <?php echo $jsDate['minutes']?>); // Jan 1, 2050
                                }
                                var clock = document.getElementById("javascript-countdown");
                                clock.innerHTML = countdown(targetDate).toString();
                                var refreshIntervalId = setInterval(function(){
                                    var timespan = countdown(null, targetDate);
                                    if (timespan.value > 0) {
                                        clock.innerHTML = timespan.toString();
                                    } else {
                                        jQuery("#countdown-container").html("Closed");
                                        jQuery("#btn-enter").prop('disabled',true);
                                        clearInterval(refreshIntervalId);
                                    }
                                }, 1000);
                            </script>
                        <?php endif; ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
<?php endif; ?>

    <script type="text/javascript">
        (function(){
            var contestForm = new VarienForm('contestForm');
            var supportsTouch = 'ontouchstart' in window || navigator.msMaxTouchPoints;


            jQuery(document).ready(function(){
                var contest = JSON.parse(localStorage.getItem('contest'));
                if (contest){
                    jQuery('#name').val(contest.name);
                    jQuery('#email').val(contest.email);
                    jQuery('#mobile').val(contest.mobile);
                    var oState = document.getElementById("state");
                    if (oState)
                    {
                        for(i=0;i<oState.length;i++)
                        {
                            if (oState.options[i].value == contest.state)
                            {
                                oState.selectedIndex=i;
                            }
                        }
                    }
                }

                jQuery('a.zoomable').click(function(e){
                    if (!supportsTouch)
                        e.preventDefault();
                });

                jQuery('#contestForm').submit(function(e){
                    if (jQuery('.choice').length > 0 && jQuery('.choice-selected').length == 0){
                        e.preventDefault();
                        alert('Please select one of the options');
                    }
                    localStorage.setItem('contest',JSON.stringify({name: jQuery('#name').val(), email: jQuery('#email').val(), mobile: jQuery('#mobile').val(), state: jQuery('#state').val()}));
                });

                jQuery('.choice').click(function(){
                    jQuery('.choice-selected').removeClass('choice-selected');
                    jQuery(this).addClass('choice-selected');
                    jQuery('#competition').html(jQuery(this).attr('data-choice'));
                });
            });
        })();
    </script>

<?php if ($this->getFacebook()): ?>
    <?php $contest = $this->getCurrentContest(); ?>
    <script type="text/javascript" src="https://connect.facebook.net/en_US/all.js"></script>
    <script type="text/javascript">
        FB.init({
            appId      : '<?php echo $contest->getFacebookAppId(); ?>'
        });
        setTimeout("FB.Canvas.setAutoGrow()",500);
        FB.Event.subscribe('edge.create', function(href, widget) {
            window.location.reload();
        });
    </script>
<?php endif; ?>