<?php if ($this->getProductData()->getId()): ?>
	<div class="product-review">
	    <div class="page-title">
	        <h1><?php echo $this->__('Review Details') ?></h1>
	    </div>
	    <div class="row-fluid">
			<div class="span12">
				<div class="row-fluid">

					<div class="span4">
						<a href="<?php echo $this->getProductData()->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getProductData()->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($this->getProductData(), 'small_image')->resize(300, 300); ?>" height="300" width="300" alt="<?php echo $this->htmlEscape($this->getProductData()->getName()) ?>" /></a>
						<?php if ($this->getRating() && $this->getRating()->getSize()): ?>
							<p class="label"><?php echo $this->__('Average Customer Rating') ?></p>
							<?php echo $this->getReviewsSummaryHtml($this->getProductData()) ?>
						<?php endif; ?>
					</div>
					<div class="span8">
						<div class="product-details">
							<h2 class="product-name"><?php echo $this->htmlEscape($this->getProductData()->getName()) ?></h2>
							<?php if ($this->getRating() && $this->getRating()->getSize()): ?>
								<h3><?php echo $this->__('Product Rating:') ?></h3>
								<table class="ratings-table table">
									<?php foreach ($this->getRating() as $_rating): ?>
										<?php if ($_rating->getPercent()): ?>
											<tr>
												<th><?php echo $this->__($this->escapeHtml($_rating->getRatingCode())) ?></th>
												<td>
													<div class="rating-box">
														<div class="rating" style="width:<?php echo ceil($_rating->getPercent()) ?>%;"></div>
													</div>
												</td>
											</tr>
										<?php endif; ?>
									<?php endforeach; ?>
								</table>
							<?php endif; ?>

							<div>
								<blockquote>
									<p><?php echo nl2br($this->htmlEscape($this->getReviewData()->getDetail())) ?></p>
									<small><cite><?php echo $this->__('Product Review (submitted on %s):', $this->dateFormat($this->getReviewData()->getCreatedAt())) ?></cite></small>
								</blockquote>
								<p>

								</p>
								<p>

								</p>
							</div>

						</div>
						<div class="buttons-set">
							<p><a clas="btn backbutton" href="<?php echo $this->getBackUrl() ?>"><?php echo $this->__('Back to Product Reviews') ?></a></p>
						</div>

					</div>
				</div>
			</div>
	    </div>

		<?php $_items = $this->getReviewsCollection()->getItems(); ?>
		<div class="box-collateral box-reviews" id="customer-reviews">
			<?php if (count($_items)): ?>
				<div class="row-fluid">
					<div class="span12">

		                <h2 class="well"><?php echo $this->__('Customer Reviews') ?></h2>
						<?php echo $this->getChildHtml('toolbar') ?>

						<?php foreach ($_items as $_review): ?>

			                <div class="review-name">
			                    <a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><?php echo $this->htmlEscape($_review->getTitle()) ?></a>
			                    <br/>
			                    <div class="author">
			                        <small> <?php echo $this->__('<span>%s</span>', $this->htmlEscape($_review->getNickname())) ?> </small>
									<br/><br/>
			                    </div>
			                    <div class="row-fluid">

									<?php $_votes = $_review->getRatingVotes(); ?>
									<?php if (count($_votes)): ?>

										<div class="span2">
				                            <table class="ratings-table table">
				                                <col class="span1" />
				                                <col class="span2" />
												<col class="span2" />
				                                <tbody>
													<?php foreach ($_votes as $_vote): ?>
					                                    <tr>
					                                        <th><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></th>
					                                        <td>
					                                            <div class="progress">
					                                                <div class="bar" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
					                                            </div>
															</td>
														</tr>
													<?php endforeach; ?>
				                                </tbody>
											</table>
										</div>

									<?php endif; ?>
									<div class="span8">
										<blockquote>
											<div class="revdate"><?php echo $this->__('%s', $this->formatDate($_review->getCreatedAt()), 'long') ?></div>
											<br/>
											<p><?php echo nl2br($this->htmlEscape($_review->getDetail())) ?></p>
											<br/>
											<p>
											<table>
			                                    <tr>
													<td>
														<p><small>Was this review helpful Yes |No  </small> </P>
													</td>
													<td>
														<div class="review-feedback"> <i class="icon-flag"></i> Report this Comment </li> </div>
													</td>
			                                    </tr>
											</table>
											</p>



										</blockquote>
									</div>
								</div>
			                </div>
						<?php endforeach; ?>

						<?php echo $this->getChildHtml('toolbar') ?>

					</div>
				</div>
			<?php endif; ?>
			<?php echo $this->getChildHtml('review_form') ?>
		</div>

	</div>
<?php endif; ?>
