<?php if (Mage::getStoreConfigFlag('aromicon_gua/general/enable')): ?>
	<!--Aromicon Google Universal Analytics Section start -->
	<script type="text/javascript">
		<?php if(Mage::getStoreConfigFlag('aromicon_gua/ecommerce/enableec')): ?>
			function onShippingComplete(formId) {
				ga('require', 'ec');
				<?php try{
					$_products = Mage::getModel('core/session')->getGuaCheckout();
					foreach ($_products as $_product): ?>
						ga('ec:addProduct', {
						  'id': '<?php echo $_product->getSku() ?>',
						  'name': '<?php echo str_replace('\'','', $_product->getName()) ?>',
						  'category': '<?php echo $_product->getCategory() ?>',
						  'brand': '',
						  'variant': '',
						  'price': '<?php echo $_product->getPrice() ?>',
						  'quantity': <?php echo (int) $_product->getQty() ?>
						});
				<?php endforeach; ?>				
				<?php
				}catch (Exception $e){}
				?>
			
				var joForm = document.getElementById(formId);

				for (var i = 0; i < joForm.elements.length; i++) {
					if (joForm.elements[i].checked)
					{	
						var shippingOption = "";
						switch (joForm.elements[i].value)
						{
							case 'tablerate_bestway':
								shippingOption = "International";
								break;
							case 'freeshipping_freeshipping':
								shippingOption = "Free Parcel (AusPost)";
								break;
							case 'flatrate_flatrate':
								shippingOption = "Express (AusPost)";
								break;
							default:
								if (joForm.elements[i].value.indexOf("temando") != -1)	shippingOption = "Temando";
								else shippingOption = joForm.elements[i].value;
								break;
						}
						break;
					}
				}
				ga('ec:setAction', 'checkout', {
					'step': 1,
					'option': shippingOption
				});
				
				ga('send', 'pageview');
				ga('send', 'event', 'Checkout', 'Shipping');
			}
		<?php endif; ?>	
	</script>
<?php endif; ?>