<?php
	$_option = $this->getOption();
	$_selections = $_option->getSelections();
	$_showSingle = (count($_selections) == 1 && $_option->getRequired()) 
		
?>

<div class="option-wrapper bundle-option-wrapper-select">

	<?php
	$_product = Mage::getModel('catalog/product')->load($_selections[0]->getId());
	$configurable_product = Mage::getModel('catalog/product_type_configurable');
	$parentIdArray = $configurable_product->getParentIdsByChild($_product->getId());
	if(!empty($parentIdArray)) 
	{
		// currently in the master configurable product
		//print_r($parentIdArray);
		$_product = Mage::getModel('catalog/product')->load($parentIdArray[0]);
	}

	//$_helper = $this->helper('catalog/output'); 
	?>
	
	<div class="bundle-img-container">
		<a href="<?php echo $_product->getProductUrl()?>" >
			<img id="image-<?php echo $_option->getId()?>" src="<?php echo $_product->getThumbnailUrl(100,100); ?>" height="100" alt="<?php echo $this->htmlEscape($_option->getTitle()) ?>" />			
		</a>
	</div>
	
	<div class="option-dropdowns">	
		<dt>
			<span class="qty-holder">
				<?php if ($_default = $_option->getDefaultSelection()): ?>
					<?php 
						$_defaultQty = $_default->getSelectionQty()*1;
						$_canChangeQty = $_default->getSelectionCanChangeQty(); 
					?>
				<?php else: ?>
					<?php 
						$_defaultQty = '0';
						$_canChangeQty = false; 
					?>
				<?php endif; ?>
				<input onkeyup="changeprice(<?php echo $_option->getId() ?>)" onblur="changeprice(<?php echo $_option->getId() ?>)" <?php echo 
$_canChangeQty?'':'disabled="disabled"' ?> id="bundle-option-<?php echo $_option->getId() ?>-qty-input" class="input-text qty<?php echo $_canChangeQty?'':' qty-disabled' ?>" type="hidden" 
name="bundle_option_qty[<?php echo $_option->getId() ?>]" value="<?php echo $_defaultQty ?>" />
			</span>
			
			<div class="bundle-conf-label">
				<label<?php if ($_option->getRequired()) {echo ' class="required"';} ?>><?php if ($_option->getRequired()) {echo '<em>*</em>';} ?>
					<a href="<?=$_product->getProductUrl()?>"><?php echo $this->htmlEscape($_option->getTitle()) ?></a>
				</label>
			</div>
		</dt>
		<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
			<div class="input-box">
				<?php $produk_id=$_option->getId();	?>
				<div class="bundle-color-select">
					<select id="bundle-color-<?php echo $produk_id?>" name="bundle-color-<?php echo $produk_id?>" onchange="choosecolor(<?php echo $produk_id?>)" <?php if ($_option->getRequired()) {echo 'class="required-entry"';}?>>
						<option selected="selected" value=""><?php echo $this->__('Choose a colour ...') ?></option>
		
					</select>
				</div>   
				<div class="bundle-size-select">
					<select onchange="bundle.changeSelection(this);" id="bundle-size-<?php echo $produk_id?>" name="bundle_option[<?php echo $produk_id?>]">
					</select>
				</div>
				<input id="the-price-<?php echo $produk_id?>" name="the-price[]" class="the-price" type="hidden" />
			</div>
		</dd>
	</div>
</div>
