<?php
$couponCode = Mage::getSingleton('checkout/session')->getQuote()->getCouponCode();
?>
<form id="co-discount-form" action="">
<fieldset>
	<ul class="form-list">
		<li class="wide">
			<label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.')?></label>
			<div class="input-box"><input value="<?php echo $this->escapeHtml($couponCode) ?>" name="coupon_code" id="coupon_code" class="input-text"></div>
		</li>
	</ul>
</fieldset>
</form>
<div class="buttons-set" id="discount-buttons-container">
	<p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	<button type="button" class="button" onclick="discount.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
	<span id="discount-please-wait" class="please-wait" style="display:none;">
		<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
	</span>
</div>

<script type="text/javascript">
//<![CDATA[
var discount = new Discount('co-discount-form','<?php echo $this->getUrl('checkoutdiscount/index/submit')?>');
//]]>
</script>