<?php
$couponCode = Mage::getSingleton('checkout/session')->getQuote()->getCouponCode();
?>
<form id="co-discount-form" action="">
<fieldset>
	<ul class="form-list">
		<li class="wide">
			<label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.')?></label>
			<div class="input-box"><input value="<?php echo $this->escapeHtml($couponCode) ?>" name="coupon_code" id="coupon_code" class="input-text"></div>
		</li>
	</ul>
</fieldset>
</form>
<div class="buttons-set" id="discount-buttons-container">
    <div class="col-sm-6 col-xs-12">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
    <div class="col-sm-6 col-xs-12">
        <button type="button" class="btn btn-primary pull-right button" onclick="discount.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="discount-please-wait" style="display:none;">
            <?php if (Mage::helper('framework')->isFaEnabled()):?><i class="fa fa-spinner fa-pulse"></i><?php else: ?><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /><?php endif; ?> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
var discount = new Discount('co-discount-form','<?php echo $this->getUrl('checkoutdiscount/index/submit')?>');
//]]>
</script>