<?php
// Get the current product
$_product = $this->getProduct();
$cUrl = $this->getPUrl();
// Mage::app()->getStore()->getName()
$cDesc = sprintf("%s - %s", Mage::getStoreConfig('general/store_information/name'), $this->getDesc());
// current product count on Pinterest
$count = $this->getCount();
$cMedia = $this->getMedia();
/*
// the following is not nessary as 'image-swatch' is clicked onload
foreach($_product->getMediaGalleryImages() as $img) {
	if (preg_match("/^front_/", $img['label'])) {
		//$cMedia = Mage::helper('catalog/image')->init($_product, 'thumbnail', $img->getFile())->resize(75,75);
		$cMedia = Mage::helper('catalog/image')->init($_product, 'image', $img->getFile());
		break;
	}
}
//echo sprintf("cMedia=%s", $cMedia);
*/
$aUrl = sprintf("%s?url=%s&description=%s&media=%s", "http://pinterest.com/pin/create/button/", $cUrl, $cDesc, $cMedia);
?>
<a id="pinit" href="<?php echo $aUrl ?>" class="pin-it-button" data-pin-config="beside" count-layout="<?=$count?>">Pin It</a>
<script type="text/javascript" src="http://assets.pinterest.com/js/pinit.js"></script>
<script language="JavaScript">
/**
dynamically change the href using the current image displayed by magiczoom
*/
jQuery(document).ready(function() {
	jQuery(".image-swatch").click(function() {
		var pinThis = jQuery('.MagicZoomBigImageCont img').attr('src');
		var sHref = "<?php echo $aUrl ?>";
		sHref += "&media=" + encodeURI(pinThis);
		// get the new pinterest object
		var pinIt = jQuery("a[class^='PIN_']");
		pinIt.attr('href', sHref);
		//alert(pinIt.attr('href'));
		return true;
	});
});
</script>
