<?php
/** @var Mage_Page_Block_Html_Topmenu_Renderer $this */
/** @var Varien_Data_Tree_Node $menuTree */
/** @var string $childrenWrapClass */

$html = '';

$children = $menuTree->getChildren();
$parentLevel = $menuTree->getLevel();
$childLevel = is_null($parentLevel) ? 0 : $parentLevel + 1;

$counter = 1;
$childrenCount = $children->count();

$parentPositionClass = $menuTree->getPositionClass();
$itemPositionClassPrefix = $parentPositionClass ? $parentPositionClass . '-' : 'nav-';

foreach ($children as $child) {
    $child->setLevel($childLevel);
    $child->setIsFirst($counter == 1);
    $child->setIsLast($counter == $childrenCount);
    $child->setPositionClass($itemPositionClassPrefix . $counter);

    $outermostClassCode = 'level'. $childLevel;
    $_hasChildren = ($child->hasChildren()) ? 'has-children' : '';

    $html .= '<li '. $this->_getRenderedMenuItemAttributes($child) .'>';

    $html .= '<a href="'. $child->getUrl() .'" class="'. $outermostClassCode .' '. $_hasChildren .'">'. $this->escapeHtml($this->__($child->getName())) .'</a>';

    if (!empty($childrenWrapClass)) {
        $html .= '<div class="'. $childrenWrapClass .'">';
    }

    $nextChildLevel = $childLevel + 1;

    if (!empty($_hasChildren)) {
        $html .= '<ul class="level'. $childLevel .'">';
        // Don't display a view all for the lookbooks main categories
        if (strpos($child->getId(),"lookbook-node-parent") === false)
        {
            $html .=     '<li class="level'. $nextChildLevel .' view-all">';
            $html .=         '<a class="level'. $nextChildLevel .'" href="'. $child->getUrl() .'">';
            $html .=             $this->__('View All') . ' ' . $this->escapeHtml($this->__($child->getName()));
            $html .=         '</a>';
            $html .=     '</li>';
        }
        $html .=     $this->render($child, $childrenWrapClass);

        // Check menu
        $menuImage = Mage::getModel('menuimage/menuimage')->getCollection()->addStatusFilter(1)->addCategoryFilter($child->getId());
        if ($menuImage->getSize())
        {
            $menuImageBlocks = Mage::getModel('menuimage/block')->getCollection()->addMenuimageFilter($menuImage->getFirstItem()->getId())->addAttributeToSort('sort_order');
            $imagesArray = Mage::helper('menuimage')->generateBlocksArray($menuImageBlocks);
        }
        if (!empty($imagesArray))
        {
            $html .= '<div class="menu-image">';
            foreach($imagesArray as $catMenuImage)
            {
                $html .= '<span><a href="'.$catMenuImage['url'].'"><img height="200" src="'.$catMenuImage['image'].'" alt="'.$this->escapeHtml($catMenuImage['alt']).'"/></a></span>';
            }
            $html .= '</div>';
        }
        $html .= '</ul>';
    }

    if (!empty($childrenWrapClass)) {
        $html .= '</div>';
    }

    $html .= '</li>';

    $counter++;
}

return $html;
