<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif;?>
        <p class="review-p">
            <a class="customer-reviews" href="<?php echo $this->getReviewsUrl() ?>#customer-reviews">
				<?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?>
			</a>
            <span class="separator">|</span>
            <a class="button btn writeareview" href="<?php echo $this->getReviewsUrl() ?>#review-form">
				<?php echo $this->__('Write a review') ?>
			</a>
        </p>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <a class="button btn writeareview" href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Write a review') ?></a>
<?php endif; ?>
