<?php
/**
 * @category    Bubble
 * @package     Bubble_AttributeOptionPro
 * @version     1.1.0
 * @copyright   Copyright (c) 2013 BubbleCode (http://shop.bubblecode.net)
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
    <div class="block block-layered-nav">
        <?php /* <div class="block-title">
            <strong><span><?php echo $this->__('Shop By') ?></span></strong>
        </div> */ ?>
        <div class="block-content">
            <?php if($this->canShowOptions()): ?>
                <?php /*  <p class="block-subtitle"><?php echo $this->__('Shopping Options') ?></p> */ ?>
                <ul id="narrow-by-list" class="filter-nav">
                    <?php $_filters = $this->getFilters() ?>
                    <?php foreach ($_filters as $code => $_filter): ?>
                        <?php if($_filter->getItemsCount()): ?>
							<li class="filter-<?php echo strtolower(str_replace(" ","-", $_filter->getName())); ?>">
								<?php if ($_filter->getAttributeModel() && $_img = $this->helper('bubble_aop')->getAttributeImage($_filter->getAttributeModel())): ?>
									<div class="filter-title">
										<img src="<?php echo $_img; ?>" alt="<?php echo $this->__($_filter->getName()) ?>" style="vertical-align: middle;" />
										<span style="vertical-align: middle;"><?php echo $this->__($_filter->getName()) ?></span>
									</div>
								<?php else: ?>
									<div class="filter-title"><?php echo $this->__($_filter->getName()) ?></div>
								<?php endif; ?>	

								<?php if ($_filter->getName() == 'Size' ): ?>
									<ul class="filter-group">
										<?php foreach ($_filter->getItems() as $_item): ?>
											<li>
												<?php if ($_item->getCount() > 0): ?>
													<a href="<?php echo $this->urlEscape($_item->getUrl()); ?>">Size <?php echo $_item->getLabel(); ?></a>
												<?php else: echo $_item->getLabel(); ?>
												<?php endif; ?>
											</li>
										<?php endforeach ?>
									</ul>				
								<?php else: ?>								
									<?php echo $_filter->getHtml() ?>
								<?php endif; ?>
							</li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
                <script type="text/javascript">decorateDataList('narrow-by-list')</script>
            <?php endif; ?>
			<div class="filter-nav">	
				<?php echo $this->getStateHtml() ?>
				
				<?php if ($this->getLayer()->getState()->getFilters()): ?>
					<div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
				<?php endif; ?>	
			</div>
        </div>
    </div>
<?php endif; ?>

<?php /* $_filtersact = Mage::getSingleton('Mage_Catalog_Block_Layer_State')->getActiveFilters() ?>
<?php echo "<h2> filtersact = " . count($_filtersact) . "</h2>"; */ ?>