<?php
    if (!Mage::getStoreConfig('htmlinject/phonesupport/enabled')) { return; }    
	$today = date('D');
	if ($today == "Sat")
	{
		$start = intval(trim(Mage::getStoreConfig('htmlinject/phonesupport/satstarttime')));
		$end   = intval(trim(Mage::getStoreConfig('htmlinject/phonesupport/satendtime'))); 
	}
	elseif($today == "Sun")
	{
		$start = intval(trim(Mage::getStoreConfig('htmlinject/phonesupport/sunstarttime')));
		$end   = intval(trim(Mage::getStoreConfig('htmlinject/phonesupport/sunendtime'))); 
	}
	else
	{
	    $start = intval(trim(Mage::getStoreConfig('htmlinject/phonesupport/weekstarttime')));
		$end   = intval(trim(Mage::getStoreConfig('htmlinject/phonesupport/weekendtime')));    
	}
	
    if ($start == 0 || $end == 0 || $start > $end) { return; }    
?>


<!-- Start script to add support pop up -->
<script>
    var expDate = new Date();
    expDate.setDate(expDate.getDate() + 1);
    
    function closeSupport(){
        Mage.Cookies.set('phone-support','false',expDate);        
        jQuery('#phone-support').animate({bottom:'-279px'});
    }
	
	function whatTimeIsIt()
	{
		var d = new Date();
		return d.getHours();
	}
	
    function calcTime(offset) {
        // create Date object for current location
        var d = new Date();
        // convert to msec
        // add local time zone offset
        // get UTC time in msec
        var utc = d.getTime() + (d.getTimezoneOffset() * 60000);
        // create new Date object for different city
        // using supplied offset
        var nd = new Date(utc + (3600000*offset));
        // return time as a string
        return nd.getHours();
    }
    jQuery(document).ready(function(){
        if ((!Mage.Cookies.get('phone-support') || Mage.Cookies.get('phone-support')!="false") && (whatTimeIsIt() >= <?=($start)?>) && (whatTimeIsIt() < <?=($end)?>)){
            jQuery('#phone-support').animate({bottom:'0px'});
        }
    });
</script>
<!-- End script to add support pop up -->

<?php
	// Convert 24 hours format to 12 hours format
	$twelvehoursEnd = date('g:i a', strtotime($end.":00"));
?>

<div id="phone-support">
    <img src="<?php echo $this->getSkinUrl('images/dangerfield-support.jpg'); ?>" alt="Alannah Hill Support" style="float:left;margin-right:10px;width:71px" />
    <img src="<?php echo $this->getSkinUrl('images/btn_window_close.gif'); ?>"  alt="Windows Close" style="float:right;cursor:pointer;" onclick="closeSupport()"/>
    <div>We are open to chat until <b><?php echo $twelvehoursEnd ?></b> tonight!<p/>Please call<p/><b><?=Mage::getStoreConfig('general/store_information/phone')?></b> or <a href="mailto:<?=Mage::getStoreConfig('trans_email/ident_support/email')?>">email</a></div>
</div>

<style>
    #phone-support{
        position:fixed;bottom:-279px;left:0px;padding:5px;border:2px solid white;
        width:200px;background-color:#F0F0F0;line-height:18px;font-size:11px;
    }

</style>