<?php
/*
Varien_Profiler::enable();
Mage::setIsDeveloperMode(true);
ini_set('display_errors', 1);
umask(0);
*/

//Mage::helper('picklist')->log($this->getUrl('picklist/PickList1/'));
$helper = new FactoryX_PickList_Helper_Data(); 
?>
<div class="main-col-inner">
<div id="messages"></div>

<div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td><h3>Generate Pick List</h3></td>
            <td class="form-buttons">
            <!--
            <button style="" onclick="configForm.submit()" class="scalable save" type="button" id="id_76e3c2861062a5cc3f4af92dd999c0f3"><span>Save Config</span></button>
            -->
            <button onclick="picklist_form.submit();" class="scalable save" type="button"><span>Submit</span></button>
            </td>
			</tr>
    	</tbody>
    </table>
</div>

<form id="picklist_form" name="picklist_form" action="<?=$this->getUrl('*/*/generatePicklist')?>" method="post" target="thePopup" onsubmit="return thePopupWindow(this.target);">
	<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />

    <div class="entry-edit">
    <div class="entry-edit-head collapseable">

<!--
onclick="Fieldset.toggleCollapse('general_country', 'http://dev.alannahhill.com.au/index.php/admin/system_config/state/key/17c15273f42d1cc51956cfd210018444/'); return false;" 
-->
<a href="#" id="general_country-head">Pick List Options</a>
</div>

<fieldset id="general_country" class="config collapseable">
<legend>Pick List Options</legend>
<table cellspacing="0" class="form-list" border="1">
<colgroup class="label"></colgroup>
<colgroup class="value"></colgroup>
<colgroup class="scope-label"></colgroup>
<colgroup class=""></colgroup>
<tbody>
	
	
<tr id="row_status">
	<td class="label"><label for="label_status"><?php echo $this->__('Status') ?></label></td>
	<td class="value">
        <select class="select" name="status" id="status">
        	<option value="processing" selected>Processing</option>
        	<option value="processing_stage2">Processing - Stage 2</option>
        	<option value="processing_partial">Processing - Partial</option>
        </select>&nbsp;
	</td>
	<td class="scope-label">* selecting 'Processing Stage 2' will highlight items that have NOT been shipped</td>
</tr>

<tr id="row_date_range">
	<td class="label"><label for="label_date_range"><?php echo $this->__('Range') ?></label></td>
	<td class="value">
	    <select class="select" name="custom_date_range" id="custom_date_range" onchange="switchDateRange();">
	        <?php
	        foreach ( $helper->getOptions() as $option ) {
	        ?>
	            <option value="<?php echo  $option['value'] ?>"
	            	<?php 
	            	if ( $this->getFilter('custom_date_range') ? $this->getFilter('custom_date_range') === $option['value'] : $option['value'] == 'yesterday' ): ?>selected<?php endif;
	            	/*
	            	if ( $this->getFilter('custom_date_range') ? $this->getFilter('custom_date_range') === $option['value'] : isset($option['default']) ): ?>selected<?php endif;
	            	*/
	            	?>>
	            	<?php echo $helper->__($option['label']) ?>
	            </option>
	        <?php } ?>    
	    </select>&nbsp;
	</td>
	<td class="scope-label"></td>
</tr>

<tr id="row_date_from">
	<td class="label"><label for="label_date_from"><?php echo $this->__('Date From') ?></label></td>
	<td class="value">
		<input class="input-text no-changes required-entry" style="width:110px !important;" type="text" id="period_date_from" name="report_from" value="<?php echo $this->getFilter('report_from') ?>" style="width:5em" onchange="setCustomRange();" />
		<img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" title="<?php echo $this->__('Select Date') ?>" id="period_date_from_trig" alt="<?php echo $this->__('Select Date') ?>" class="v-middle"/>&nbsp;&nbsp;</div>
		<div id="period_date_from_advice"></div>		
	</td>
	<td class="scope-label"></td>
</tr>

<tr id="row_date_to">
	<td class="label"><label for="label_date_to"><?php echo $this->__('Date To') ?></label></td>
	<td class="value">
		<input class="input-text no-changes required-entry" style="width:110px !important;" type="text" id="period_date_to" name="report_to" value="<?php echo $this->getFilter('report_to') ?>" style="width:5em" onchange="setCustomRange();" />
		<img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" title="<?php echo $this->__('Select Date') ?>" id="period_date_to_trig" alt="<?php echo $this->__('Select Date') ?>" class="v-middle"/>&nbsp;&nbsp;</div>
		<div id="period_date_to_advice"></div>		
	</td>
	<td class="scope-label"></td>
</tr>

<tr id="row_general_country_allow"><td class="label">
<label for="general_country_allow"><?php echo $this->__('Destinations') ?></label></td><td class="value">
<select multiple="multiple" size="10" class="select multiselect" name="region_filter[]" id="general_country_allow">
	<!--
	<option selected="selected" value="AU">Australia</option>
	-->
	<option value="ALL" selected="selected">All Regions</option>
	<!-- order[shipping_address][region_id] -->
	<?php
	$country = array("AU","NZ");
	foreach($country as $countryCode) {
		$regionCollection = Mage::getModel('directory/country')->load($countryCode)->getRegionCollection();
		$hasRegions = false;
		foreach($regionCollection as $region) {
			$hasRegions = true;
			//Mage::helper('picklist')->log(sprintf("%s->region=%s", __METHOD__, var_export($region, true)));
		?>
    		<option value="<?php echo $region['region_id'] ?>" ><?php echo sprintf("%s - %s", $countryCode, $region['name']); ?></option>
		<?php
		}
		if (!$hasRegions) {
			echo sprintf("<option value=\"%s\">%s</option>", $countryCode, $countryCode);
		}
	}
    ?>	
</select>
</td>
<td class="scope-label">Use the following list to include OR exclude orders by region</td>
</tr>
<tr id="row_general_country_allow"><td class="label">
<label for="general_country_allow"><?php echo $this->__('Destination Filter') ?></label></td><td class="value">
	<input style="margin-bottom:4px;" class="radio" type="radio" checked="checked" value="include" name="apply_filter">&nbsp;Include
	&nbsp;&nbsp;&nbsp;
	<input style="margin-bottom:4px;" class="radio" type="radio" value="exclude" name="apply_filter">&nbsp;Exclude
</td>
<td class="scope-label"></td>
</tr>

<tr id="row_sort_by">
	<td class="label"><label for="label_sort_by"><?php echo $this->__('Sort By') ?></label></td>
	<td class="value">
        <select class="select" name="sort_by" id="sort_by">
        	<option value="shipping_method" selected>Shipping</option>            
        	<option value="date">Order Date</option>
        	<option value="status">Status</option>
        </select>&nbsp;
	</td>
	<td class="scope-label">* shipping will show express first</td>
</tr>

<tr id="row_include_images">
	<td class="label"><label for="label_include_images"><?php echo $this->__('Include Images') ?></label></td>
	<td class="value" style="text-align:left !important;">
	    <input type="checkbox" name="include_image" id="include_image" value="on" />
	</td>
	<td class="scope-label"></td>
</tr>

<tr id="row_generate">
	<td class="label"><label for="label_generate"></td>
	<td class="value" style="text-align:left !important;">
		<button class="scalable save" type="button" onclick="picklist_form.submit();">
			<span>Generate</span>
		</button>
	</td>
	<td class="scope-label"></td>
</td>
</tr>

</tbody></table>
</fieldset>

<script type="text/javascript">
//Fieldset.applyCollapse('general_locale');
</script>

<!--
<div class="entry-edit-head collapseable">
<a onclick="Fieldset.toggleCollapse('general_store_information', 'http://dev.alannahhill.com.au/index.php/admin/system_config/state/key/17c15273f42d1cc51956cfd210018444/'); return false;" href="#" id="general_store_information-head">Store Information</a></div><input type="hidden" value="0" name="config_state[general_store_information]" id="general_store_information-state"><fieldset id="general_store_information" class="config collapseable"><legend>Store Information</legend><table cellspacing="0" class="form-list"><colgroup class="label"></colgroup><colgroup class="value"></colgroup><colgroup class="scope-label"></colgroup><colgroup class=""></colgroup><tbody><tr id="row_general_store_information_name"><td class="label"><label for="general_store_information_name"> Store Name</label></td><td class="value"><input type="text" class=" input-text" value="Alannah Hill" name="groups[store_information][fields][name][value]" id="general_store_information_name">
</td><td class="scope-label">[STORE VIEW]</td><td class=""></td></tr><tr id="row_general_store_information_phone"><td class="label"><label for="general_store_information_phone"> Store Contact Telephone</label></td><td class="value"><input type="text" class=" input-text" value="(03) 9824 0406" name="groups[store_information][fields][phone][value]" id="general_store_information_phone">
</td><td class="scope-label">[STORE VIEW]</td><td class=""></td></tr><tr id="row_general_store_information_address"><td class="label"><label for="general_store_information_address"> Store Contact Address</label></td><td class="value"><textarea cols="15" rows="2" class=" textarea" name="groups[store_information][fields][address][value]" id="general_store_information_address">61 Church St, Abbotsford,
Melbourne, VIC, 3067</textarea></td><td class="scope-label">[STORE VIEW]</td><td class=""></td></tr></tbody></table></fieldset><script type="text/javascript">Fieldset.applyCollapse('general_store_information');</script></div>
-->
</form>

<script type="text/javascript">
//< ![CDATA[	

var customForm = new varienForm('picklist_form');

var period_date_from = $('period_date_from');
var period_date_to   = $('period_date_to');    
period_date_from.adviceContainer = $('period_date_from_advice');
period_date_to.adviceContainer = $('period_date_to_advice');

function thePopupWindow(windowsname) {
	//alert(windowsname);
	var win = window.open('', windowsname); // , 'width=580,height=450');
	return true;
}

function validateFilterDate() {
    if (period_date_from && period_date_to) {
        return Validation.validate(period_date_from) && Validation.validate(period_date_to);
    }
    else {
        return true;
    }
}	

function reInitGrid()
{
    Calendar.setup({
        inputField : 'period_date_from',
        ifFormat : '<?php echo  $helper->getDateFormat() ?>',
        button : 'period_date_from_trig',
        align : 'Bl',
        singleClick : true
    });
    Calendar.setup({
        inputField : 'period_date_to',
        ifFormat : '<?php echo  $helper->getDateFormat() ?>',
        button : 'period_date_to_trig',
        align : 'Bl',
        singleClick : true
    });	
}

function switchDateRange() {
	<?php $values = $helper->getRangeValues() ?>
    var keys = [
    <?php foreach($values as $value): ?>
         '<?php echo  $value['key'] ?>',
    <?php endforeach; ?>
    ];
    var from_dates = [
    <?php foreach($values as $value): ?>
         '<?php echo  $value['from'] ?>',
    <?php endforeach; ?>
    ];
    var to_dates = [
    <?php foreach($values as $value): ?>
         '<?php echo  $value['to'] ?>',
    <?php endforeach; ?>
    ];
    date_range = document.getElementById('custom_date_range');
    date_from  = document.getElementById('period_date_from');
    date_to    = document.getElementById('period_date_to');
    //alert("date_range=" + date_range.value);
    value = date_range.value;
    if (value != 'custom') {
        var i;
        for (i = 0;i < keys.length; i++)
        {
            if ( keys[i] == value )
            {
                date_from.setValue(from_dates[i]);
                date_to.setValue(to_dates[i]);
            }
        }
    }
}

function setCustomRange()
{
    date_range = document.getElementById('custom_date_range');
    date_range.setValue('custom');
}

function switchDefDateRange()
{
    switchDateRange();
    date_range = document.getElementById('custom_date_range');
    date_from  = document.getElementById('period_date_from');
    if ('<?php echo  $this->getFilter('report_from') ?>' && '<?php echo  $this->getFilter('report_to')   ?>')
    {
        date_from.setValue('<?php echo $this->getFilter('report_from') ?>');
        date_to.setValue('<?php echo $this->getFilter('report_to')   ?>');
        //setCustomRange();
    }
    <?php if ( !$this->getDisableAutoload() ): ?>
    else
    {
        // alert("doFilter()");
    }
    <?php endif; ?>
}

switchDefDateRange();

Calendar.setup({
    inputField : 'period_date_from',
    ifFormat : '<?php echo $helper->getDateFormat() ?>',
    button : 'period_date_from_trig',
    align : 'Bl',
    singleClick : true
});
Calendar.setup({
    inputField : 'period_date_to',
    ifFormat : '<?php echo  $helper->getDateFormat() ?>',
    button : 'period_date_to_trig',
    align : 'Bl',
    singleClick : true
});
//]]>
</script>

</div>