<?php
/*
Varien_Profiler::enable();
Mage::setIsDeveloperMode(true);
ini_set('display_errors', 1);
umask(0);
*/

//Mage::helper('picklist')->log($this->getUrl('picklist/PickList1/'));
$helper = new FactoryX_PickList_Helper_Data(); 
?>
<div class="main-col-inner">
<div id="messages"></div>

<div class="content-header">
    <table cellspacing="0" border="0">
        <tbody><tr>
            <td><h3>Generate Pick List</h3></td>
            <td class="form-buttons">
            <!--
            <button style="" onclick="configForm.submit()" class="scalable save" type="button" id="id_76e3c2861062a5cc3f4af92dd999c0f3"><span>Save Config</span></button>
            -->
            <button onclick="picklist_form.submit();" class="scalable save" type="button"><span>Submit</span></button>
            </td>
			</tr>
    	</tbody>
    </table>
</div>

<form id="picklist_form" name="picklist_form" action="<?=$this->getUrl('*/*/generatePicklist')?>" method="post" target="thePopup" onsubmit="return thePopupWindow(this.target);">
	<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />

    <div class="entry-edit">
    <div class="entry-edit-head collapseable">

<!--
onclick="Fieldset.toggleCollapse('general_country', 'http://dev.alannahhill.com.au/index.php/admin/system_config/state/key/17c15273f42d1cc51956cfd210018444/'); return false;" 
-->
<a href="#" id="general_country-head">Filter Options</a>
</div>

<fieldset id="general_country" class="config collapseable">
<legend>Order Filter</legend>

<div class="comment">
<div style="background-color: #efefef;margin-bottom: 10px; padding:10px;">
Select what orders you want on your pick list using the options below.
</div>
</div>

<table cellspacing="0" class="form-list" border="1">
<colgroup class="label"></colgroup>
<colgroup class="value"></colgroup>
<colgroup class="scope-label"></colgroup>
<colgroup class=""></colgroup>
<tbody>
	
<tr id="row_status">
	<td class="label"><label for="label_status"><?php echo $this->__('Status') ?></label></td>
	<td class="value">
        <select class="select" name="status" id="status">
        	<option value="processing" selected>Processing</option>
        	<option value="processing_stage2">Processing - Stage 2</option>
        	<option value="processing_partial">Processing - Partial</option>
        	<option value="complete">Complete</option>
        </select>&nbsp;
	</td>
	<td class="scope-label">* selecting 'Processing Stage 2' will highlight items that have NOT been shipped</td>
</tr>

<tr id="row_date_range">
	<td class="label"><label for="label_date_range"><?php echo $this->__('Range') ?></label></td>
	<td class="value">
	    <select class="select" name="custom_date_range" id="custom_date_range" onchange="switchDateRange();">
	        <?php
	        foreach ( $helper->getOptions() as $option ) {
	        ?>
	            <option value="<?php echo  $option['value'] ?>"
	            	<?php 
	            	if ( $this->getFilter('custom_date_range') ? $this->getFilter('custom_date_range') === $option['value'] : $option['value'] == 'yesterday' ): ?>selected<?php endif;
	            	/*
	            	if ( $this->getFilter('custom_date_range') ? $this->getFilter('custom_date_range') === $option['value'] : isset($option['default']) ): ?>selected<?php endif;
	            	*/
	            	?>>
	            	<?php echo $helper->__($option['label']) ?>
	            </option>
	        <?php } ?>    
	    </select>&nbsp;
	</td>
	<td class="scope-label"></td>
</tr>

<tr id="row_date_from">
	<td class="label"><label for="label_date_from"><?php echo $this->__('Date From') ?></label></td>
	<td class="value">
		<input class="input-text no-changes required-entry" style="width:110px !important;" type="text" id="period_date_from" name="report_from" value="<?php echo $this->getFilter('report_from') ?>" style="width:5em" onchange="setCustomRange();" />
		<img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" title="<?php echo $this->__('Select Date') ?>" id="period_date_from_trig" alt="<?php echo $this->__('Select Date') ?>" class="v-middle"/>&nbsp;&nbsp;</div>
		<div id="period_date_from_advice"></div>		
	</td>
	<td class="scope-label"></td>
</tr>

<tr id="row_date_to">
	<td class="label"><label for="label_date_to"><?php echo $this->__('Date To') ?></label></td>
	<td class="value">
		<input class="input-text no-changes required-entry" style="width:110px !important;" type="text" id="period_date_to" name="report_to" value="<?php echo $this->getFilter('report_to') ?>" style="width:5em" onchange="setCustomRange();" />
		<img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" title="<?php echo $this->__('Select Date') ?>" id="period_date_to_trig" alt="<?php echo $this->__('Select Date') ?>" class="v-middle"/>&nbsp;&nbsp;</div>
		<div id="period_date_to_advice"></div>		
	</td>
	<td class="scope-label"></td>
</tr>

<!-- Destinations -->
<tr id="row_general_country_allow"><td class="label">
<label for="general_country_allow"><?php echo $this->__('Destinations') ?></label></td><td class="value">
<select multiple="multiple" size="10" class="select multiselect" name="region_filter[]" id="general_country_allow">
	<!--
	<option selected="selected" value="AU">Australia</option>
	-->
	<option value="ALL" selected="selected">All Regions</option>
    <option value="INT">International</option>
	<!-- order[shipping_address][region_id] -->
	<?php
	//$country = array("AU","NZ");
	$country = array("AU");
	foreach($country as $countryCode) {
		$regionCollection = Mage::getModel('directory/country')->load($countryCode)->getRegionCollection();
		$hasRegions = false;
		foreach($regionCollection as $region) {
			$hasRegions = true;
			//Mage::helper('picklist')->log(sprintf("%s->region=%s", __METHOD__, var_export($region, true)));
		?>
    		<option value="<?php echo $region['region_id'] ?>" ><?php echo sprintf("%s - %s", $countryCode, $region['name']); ?></option>
		<?php
		}
		if (!$hasRegions) {
			echo sprintf("<option value=\"%s\">%s</option>", $countryCode, $countryCode);
		}
	}
    ?>	
</select>
</td>
<td class="scope-label">Use the following list to include OR exclude orders by region</td>
</tr>
<tr id="row_general_country_allow"><td class="label">
<label for="general_country_allow"><?php echo $this->__('Destination Filter') ?></label></td><td class="value">
	<input style="margin-bottom:4px;" class="radio" type="radio" checked="checked" value="include" name="region_filter_apply">&nbsp;Include
	&nbsp;&nbsp;&nbsp;
	<input style="margin-bottom:4px;" class="radio" type="radio" value="exclude" name="region_filter_apply">&nbsp;Exclude
</td>
<td class="scope-label"></td>
</tr>

<!-- Customer Groups -->
<?php if (Mage::getStoreConfig('picklist/default_filter/show_cg_filter')): ?>
    <tr id="row_customer_groups_allow"><td class="label">
    <label for="customer_groups_allow"><?php echo $this->__('Customer Groups') ?></label></td><td class="value">
    <?php
    $customerGroups = new FactoryX_PickList_Model_System_Config_Source_CustomerGroup();
    $customerGroupsDefault = Mage::getStoreConfig('picklist/default_filter/customer_group_filter_default');
    $default = preg_split("/,/",$customerGroupsDefault);
    ?>
    <select multiple="multiple" size="<?php echo sprintf("%d", count($customerGroups->toOptionArray())); ?>>" class="select multiselect" name="customer_groups_filter[]" id="customer_groups_allow">
    	<?php foreach($customerGroups->toOptionArray() as $group): ?>
            <option value="<?php echo $group['value'] ?>" <?php echo (in_array($group['value'], $default) ? "selected" : "") ?>><?php echo sprintf("%s", $group['label']); ?></option>
        <?php endforeach; ?>
    </select>
    </td>
    <td class="scope-label">Use the following list to include OR exclude orders by customer group</td>
    </tr>
    <tr id="row_customer_groups_allow"><td class="label">
    <label for="customer_groups_allow"><?php echo $this->__('Customer Groups Filter') ?></label></td><td class="value">
    	<input style="margin-bottom:4px;" class="radio" type="radio" checked="checked" value="include" name="customer_groups_filter_apply">&nbsp;Include
    	&nbsp;&nbsp;&nbsp;
    	<input style="margin-bottom:4px;" class="radio" type="radio" value="exclude" name="customer_groups_filter_apply">&nbsp;Exclude
    </td>
    <td class="scope-label"></td>
    </tr>
<?php else: ?>
    <input type="hidden" name="customer_groups_filter[]" value="ALL">
    <input type="hidden" name="customer_groups_filter_apply" value="include">
<?php endif; ?>

<!-- Product Types -->
<?php if (Mage::getStoreConfig('picklist/default_filter/show_pt_filter')): ?>
    <tr id="row_product_type_allow"><td class="label">
    <label for="product_type_allow"><?php echo $this->__('Product Types') ?></label></td><td class="value">
    <?php
    $productTypes = new FactoryX_PickList_Model_System_Config_Source_ProductTypes();    
    $productTypesDefault = Mage::getStoreConfig('picklist/default_filter/product_type_filter_default');
    $default = preg_split("/,/",$productTypesDefault);
    //echo sprintf("<pre>default: %s</pre>", print_r($default, true));
    ?>
    <select multiple="multiple" size="<?php echo sprintf("%d", count($productTypes->toOptionArray())); ?>>" class="select multiselect" name="product_type_filter[]" id="product_type_allow">
        <?php
    	foreach($productTypes->toOptionArray() as $type): ?>
            <option value="<?php echo $type['value'] ?>" <?php echo (in_array($type['value'], $default) ? "selected" : "") ?>><?php echo sprintf("%s", $type['label']); ?></option>
        <?php endforeach;
        ?>
    </select>
    </td>
    <td class="scope-label">Use the following list to include OR exclude orders by product types</td>
    </tr>
    <tr id="row_product_type_allow"><td class="label">
    <label for="product_type_allow"><?php echo $this->__('Product Type Filter') ?></label></td><td class="value">
    	<input style="margin-bottom:4px;" class="radio" type="radio" checked="checked" value="include" name="product_type_filter_apply">&nbsp;Include
    	&nbsp;&nbsp;&nbsp;
    	<input style="margin-bottom:4px;" class="radio" type="radio" value="exclude" name="product_type_filter_apply">&nbsp;Exclude
    </td>
    <td class="scope-label"></td>
    </tr>
<?php else: ?>
    <input type="hidden" name="product_type_filter[]" value="ALL">
    <input type="hidden" name="product_type_filter_apply" value="include">
<?php endif; ?>

<?php
/*
<tr id="row_include_consolidations">
	<td class="label"><label for="label_include_consolidations"><?php echo $this->__('Include consolidations') ?></label></td>
	<td class="value" style="text-align:left !important;">
	    <input type="checkbox" name="include_consolidations" id="include_consolidations" <?php echo (Mage::getStoreConfig('picklist/default_filter/include_consolidations'))?"checked":"" ?> />
	</td>
	<td class="scope-label"></td>
</tr>
<tr id="row_include_preorders">
	<td class="label"><label for="label_include_preorders"><?php echo $this->__('Include pre-orders') ?></label></td>
	<td class="value" style="text-align:left !important;">
	    <input type="checkbox" name="include_preorders" id="include_preorders" <?php echo (Mage::getStoreConfig('picklist/default_filter/include_preorders'))?"checked":"" ?> />
	</td>
	<td class="scope-label"></td>
</tr>
*/
?>
<tr id="row_include_zero">
	<td class="label"><label for="label_include_zero"><?php echo $this->__('Include item with zero quantity') ?></label></td>
	<td class="value" style="text-align:left !important;">
	    <input type="checkbox" name="include_zero" id="include_zero" <?php echo (Mage::getStoreConfig('picklist/default_filter/include_zero'))?"checked":"" ?> />
	</td>
	<td class="scope-label"></td>
</tr>

</tbody></table>
</fieldset>

<div class="entry-edit-head collapseable"><a href="#" id="general_country-head">Output Options</a></div>

<fieldset id="general_country" class="config collapseable">
<legend>Output Options</legend>

<table cellspacing="0" class="form-list" border="1">
<colgroup class="label"></colgroup>
<colgroup class="value"></colgroup>
<colgroup class="scope-label"></colgroup>
<colgroup class=""></colgroup>
<tbody>
    
<tr id="row_include_image">
	<td class="label"><label for="label_include_image"><?php echo $this->__('Include Product Images') ?></label></td>
	<td class="value" style="text-align:left !important;">
	    <input type="checkbox" name="include_image" id="include_image" <?php echo (Mage::getStoreConfig('picklist/default_output/show_images'))?"checked":"" ?> />
	</td>
	<td class="scope-label"></td>
</tr>

<tr id="row_include_summary">
	<td class="label"><label for="label_include_summary"><?php echo $this->__('Include Summary') ?></label></td>
	<td class="value" style="text-align:left !important;">
	    <input type="checkbox" name="include_summary" id="include_summary" <?php echo (Mage::getStoreConfig('picklist/default_output/include_summary'))?"checked":"" ?> />
	</td>
	<td class="scope-label"></td>
</tr>

<tr id="row_sort_by">
	<td class="label"><label for="label_sort_by"><?php echo $this->__('Sort By') ?></label></td>
	<td class="value">
        <select class="select" name="sort_by" id="sort_by">
        	<option value="shipping_method" selected>Shipping</option>            
        	<option value="created_at">Order Date</option>
        	<option value="status">Status</option>
        </select>&nbsp;
	</td>
	<td class="scope-label">* shipping will show express first</td>
</tr>

<tr id="row_send_to_stores">
	<td class="label"><label for="label_number_pdf"><?php echo $this->__('Send to stores') ?></label></td>
	<td class="value" style="text-align:left !important;">
        <select multiple="multiple" size="5" class="select multiselect" name="send_to_stores[]" id="send_to_stores[]">
<?php
$sendToStores = Mage::getStoreConfig('picklist/default_output/send_to_stores');
$defSendToStores = explode(",", $sendToStores);

//->addFieldToFilter('region', array('in' => 'vic'))
$stores = Mage::getModel('ustorelocator/location')->getCollection()
    ->setOrder('region', 'ASC')
    ->setOrder('store_code', 'ASC');

foreach($stores as $store) {
    $code = strtolower($store->getData('store_code'));
    $selected = "";
    if (in_array($code, $defSendToStores)) {
        $selected = " selected='selected'";
    }
    echo sprintf("<option value='%s'%s>%s - %s</option>", $code, $selected, $store->getData('region'), $code);
}
?>
        </select>
	</td>
	<td class="scope-label"></td>
</tr>

<tr id="row_split_pdf">
	<td class="label"><label for="label_split_pdf"><?php echo $this->__('Split PDF') ?></label></td>
	<td class="value" style="text-align:left !important;">
	    <input type="checkbox" name="split_pdf" id="split_pdf" <?php echo (Mage::getStoreConfig('picklist/default_output/split_pdf'))?"checked":"" ?> />
	</td>
	<td class="scope-label">if multiple stores are selected above, the orders will be split amongst that many pdf files</td>
</tr>

<tr id="row_send_email">
	<td class="label"><label for="label_send_email"><?php echo $this->__('Send email') ?></label></td>
	<td class="value" style="text-align:left !important;">
	    <input type="checkbox" name="send_email" id="send_email" <?php echo (Mage::getStoreConfig('picklist/default_output/send_email'))?"checked":"" ?> />
	</td>
	<td class="scope-label">this will email the store select above e.g. storeCode@factoryx.com.au</td>
</tr>

<tr id="row_additional_emails">
	<td class="label"><label for="label_additional_emails"><?php echo $this->__('Additional email(s)') ?></label></td>
	<td class="value" style="text-align:left !important;">
	    <input type="text" name="additional_emails" id="additional_emails" class="input-text" <?php echo Mage::getStoreConfig('picklist/default_output/additional_emails'); ?> />
	</td>
	<td class="scope-label">comma separated list of emails</td>
</tr>

<?php
$option = Mage::getModel('picklist/system_config_source_option');
$options = $option->toOptionArray();
//echo sprintf("<pre>%s</pre>", print_r($options, true));
echo sprintf("<pre>%s</pre>", print_r($this->getFormData(), true));

// TODO: override with form
// $this->getFormData()->getFileOutput()
$fileOutput = Mage::getStoreConfig('picklist/default_output/file_output');

//$attribute = Mage::getModel('eav/config')->getAttribute('customer', 'option');
?>
<tr id="row_file_output">
    <td class="label"><label for="label_number_pdf"><?php echo $this->__('PDF Output\'s') ?></label></td>
	<td class="value" style="text-align:left !important;">
        <select name="file_output" id="file_output" class="">
        <?php
        foreach($options as $value => $label) {
        ?>
            <option value='<?php echo $value ?>' <?php if ($fileOutput == $value) {
                echo 'selected="selected"';
            }
        ?>>
            <?php echo $this->__($label)?></option>
        <?php
        }
        ?>
        </select>
    </td>
	<td class="scope-label"></td>
</tr>


<tr id="row_generate">
	<td class="label"><label for="label_generate"></td>
	<td class="value" style="text-align:left !important;">
		<button class="scalable save" type="button" onclick="picklist_form.submit();">
			<span>Generate</span>
		</button>
	</td>
	<td class="scope-label"></td>
</td>
</tr>

</tbody></table>
</fieldset>

<script type="text/javascript">
//Fieldset.applyCollapse('general_locale');
</script>

</form>

<script type="text/javascript">
//< ![CDATA[	

var customForm = new varienForm('picklist_form');

var period_date_from = $('period_date_from');
var period_date_to   = $('period_date_to');    
period_date_from.adviceContainer = $('period_date_from_advice');
period_date_to.adviceContainer = $('period_date_to_advice');

function thePopupWindow(windowsname) {
	//alert(windowsname);
	var win = window.open('', windowsname); // , 'width=580,height=450');
	return true;
}

function validateFilterDate() {
    if (period_date_from && period_date_to) {
        return Validation.validate(period_date_from) && Validation.validate(period_date_to);
    }
    else {
        return true;
    }
}	

function reInitGrid()
{
    Calendar.setup({
        inputField : 'period_date_from',
        ifFormat : '<?php echo  $helper->getDateFormat() ?>',
        button : 'period_date_from_trig',
        align : 'Bl',
        singleClick : true
    });
    Calendar.setup({
        inputField : 'period_date_to',
        ifFormat : '<?php echo  $helper->getDateFormat() ?>',
        button : 'period_date_to_trig',
        align : 'Bl',
        singleClick : true
    });	
}

function switchDateRange() {
	<?php $values = $helper->getRangeValues() ?>
    var keys = [
    <?php foreach($values as $value): ?>
         '<?php echo  $value['key'] ?>',
    <?php endforeach; ?>
    ];
    var from_dates = [
    <?php foreach($values as $value): ?>
         '<?php echo  $value['from'] ?>',
    <?php endforeach; ?>
    ];
    var to_dates = [
    <?php foreach($values as $value): ?>
         '<?php echo  $value['to'] ?>',
    <?php endforeach; ?>
    ];
    date_range = document.getElementById('custom_date_range');
    date_from  = document.getElementById('period_date_from');
    date_to    = document.getElementById('period_date_to');
    //alert("date_range=" + date_range.value);
    value = date_range.value;
    if (value != 'custom') {
        var i;
        for (i = 0;i < keys.length; i++)
        {
            if ( keys[i] == value )
            {
                date_from.setValue(from_dates[i]);
                date_to.setValue(to_dates[i]);
            }
        }
    }
}

function setCustomRange()
{
    date_range = document.getElementById('custom_date_range');
    date_range.setValue('custom');
}

function switchDefDateRange()
{
    switchDateRange();
    date_range = document.getElementById('custom_date_range');
    date_from  = document.getElementById('period_date_from');
    if ('<?php echo  $this->getFilter('report_from') ?>' && '<?php echo  $this->getFilter('report_to')   ?>')
    {
        date_from.setValue('<?php echo $this->getFilter('report_from') ?>');
        date_to.setValue('<?php echo $this->getFilter('report_to')   ?>');
        //setCustomRange();
    }
    <?php if ( !$this->getDisableAutoload() ): ?>
    else
    {
        // alert("doFilter()");
    }
    <?php endif; ?>
}

switchDefDateRange();

Calendar.setup({
    inputField : 'period_date_from',
    ifFormat : '<?php echo $helper->getDateFormat() ?>',
    button : 'period_date_from_trig',
    align : 'Bl',
    singleClick : true
});
Calendar.setup({
    inputField : 'period_date_to',
    ifFormat : '<?php echo  $helper->getDateFormat() ?>',
    button : 'period_date_to_trig',
    align : 'Bl',
    singleClick : true
});
//]]>
</script>

</div>