<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Bag'); ?>
<?php if($_product->isSaleable()): ?>

        <?php if(!$_product->isGrouped()): ?>
        <label for="qty"><?php echo $this->__('Quantity:') ?></label><input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="span1 input-text qty" />
        <?php endif; ?>
        <br>
        <button type="button" title="<?php echo $buttonTitle ?>" class="btn addtobag" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>

<?php endif; ?>
