  
<?php $_product = $this->getProduct() ?>

<div class="addto-controls"> 
<?php if ($this->helper('wishlist')->isAllow()) : ?>
		
			<div class="addtowishlist">
				<a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a>
			</div>
		
<?php endif; ?>

<?php if ($this->hasRequiredOptions()):?>	
	<p class="help-block"><?php echo $this->__('* Entry Required') ?></p>
<?php endif;?>
</div>
	
<?php /*
<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ): ?>
	<li class="addtocompare">
		<a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a>
	</li>
<?php endif; >
*/

