<div class="page-title">
    <h1><?php echo $this->__('Edit Account Information') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" class="form">
    <div class="row">
    <fieldset class="span4">
        <?php echo $this->getBlockHtml('formkey')?>
        <legend><h2 class="legend"><?php echo $this->__('Account Information') ?></h2></legend>
            <div class="controls">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </div>
            <div class="control-group">                
                <div class="controls">
                    <label for="email" class="control-label"><?php echo $this->__('Email Address') ?><em>*</em></label>
                    <input type="email" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
                </div>
            
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <div class="controls"><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></div>
        <?php endif ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <div class="controls"><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></div>
        <?php endif ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <div class="controls"><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></div>
        <?php endif ?>
		
            <div class="controls">
                <label for="change_password" class="checkbox"></label>
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    <?php echo $this->__('Change Password') ?>                        
            </div>
		</div>
    </fieldset>
    <fieldset class="span4" style="display:none;">
        <legend><h2 class="legend"><?php echo $this->__('Change Password') ?></h2></legend>		
		<div class="controls">
			<label for="current_password" class="required"><?php echo $this->__('Current Password') ?><em>*</em></label>
			<input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
		</div>
		
			<div class="controls">
				<label for="password" class="required"><?php echo $this->__('New Password') ?><em>*</em></label>
				<input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
			</div>
			<div class="controls">
				<label for="confirmation" class="required"><?php echo $this->__('Confirm New Password') ?><em>*</em></label>
				<input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
			</div>
		
    </fieldset>
    </div>
	<div class="row">
		<div class="span7">
			<p class="help-block"><?php echo $this->__('* Required Fields') ?></p>
			<button type="submit" title="<?php echo $this->__('Save') ?>" class="btn savebutton pull-right"><span><span><?php echo $this->__('Save') ?></span></span></button>
			<?php /* <p><a class="btn backbutton" href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><?php echo $this->__('Back') ?></a></p> */ ?>        
		</div>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(1).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(1).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
