<div class="page-title">
    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate" class="form-forgotten-password">
    <fieldset>
        <h2><?php echo $this->__('Retrieve your password here') ?></h2>
        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <div class="control-group">
			<label for="email_address"><em>*</em><?php echo $this->__('Email Address') ?></label>
			<div class="controls">
				<div class="input-prepend">
					<span class="add-on">@</span>
					<input type="text" name="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
				</div>
			</div>

        </div>
		<?php echo $this->getChildHtml('form.additional.info'); ?>
        <p class="help-block"><?php echo $this->__('* Entry Required') ?></p>
		<div class="row">
			<div class="span">
				<button type="submit" title="<?php echo $this->__('Submit') ?>" class="btn btn-forgotten-password"><span><span><?php echo $this->__('Submit') ?></span></span></button>
				<p class="back-link">
					<span class="icon-backward"></span>
					<a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><?php echo $this->__('Back to Login') ?></a>
				</p>
			</div>
		</div>
	</fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
	var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
