<?php $_item = $this->getItem() ?>
<tr class="border">
    <td><?php echo $this->getColumnHtml($_item, 'name') ?></td>
    <td><?php echo $this->getColumnHtml($_item, 'qty') ?></td>
	
	<td>
		<select name="shipment[sourced_from][<?php echo $_item->getOrderItemId() ?>]" id="shipment[sourced_from][<?php echo $_item->getOrderItemId() ?>]" class="select sourcedfrom">
			<?php
				$stores = Mage::helper('shippedfrom')->getStores();
				foreach($stores as $storeId => $storeTitle) {
					echo sprintf("<option value='%d'%s>%s</option>", $storeId, (preg_match("/default/i", $storeTitle)?" selected":""), $storeTitle);
				}
			?>
		</select>
	</td>
	
	<td>
		<?php
			$user = Mage::getSingleton('admin/session');
			$userName = $user->getUser()->getName();
		?>
		<select name="shipment[sourced_by][<?php echo $_item->getOrderItemId() ?>]" id="shipment[sourced_by][<?php echo $_item->getOrderItemId() ?>]" class="select sourcedby">
            <?php	echo sprintf("<option value='%s'%s>%s</option>", $userName, " selected",$userName); ?>
		</select>
	</td>

    <td class="<?php if ($this->isShipmentRegular()): ?>last<?php endif; ?> a-center">
        <?php if ($this->canShipPartiallyItem()): ?>
            <input type="text" class="input-text" name="shipment[items][<?php echo $_item->getOrderItemId() ?>][qty]" value="<?php echo $_item->getQty()*1 ?>" />
        <?php else: ?>
            <?php echo $_item->getQty()*1 ?>
        <?php endif; ?>
    </td>
    <?php if (!$this->canShipPartiallyItem()): ?>
    <td class="a-center last">
        <input type="hidden" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="0" />
        <input type="checkbox" name="shipment[items][<?php echo $_item->getOrderItemId() ?>]" value="<?php echo $_item->getQty()*1 ?>" checked />
    </td>
    <?php endif; ?>
</tr>
