<div class="input-group">
    <input type='text' placeholder="<?php echo $this->getField()->getName(); ?>" name='<?php echo $this->getFieldName()?>' id='<?php echo $this->getFieldId()?>' class='<?php echo $this->getFieldClass()?> form-control' style='<?php echo $this->getFieldStyle()?>' value='<?php echo $this->getCustomerValue()?>' readonly='readonly'/>
    <span class="input-group-addon">
        <?php if (Mage::helper('framework')->isFaEnabled()): ?>
            <i class="fa fa-calendar"></i>
        <?php else: ?>
            <img src="<?php echo $this->getSkinUrl('images/calendar.gif'); ?>" alt="Date" />
        <?php endif; ?>
    </span>
</div>

<script type='text/javascript'>

Calendar.setup({
	inputField: '<?php echo $this->getFieldId()?>',
	ifFormat: '<?php echo str_replace("'","\'",$this->getField()->getDateStrFormat())?>',
	showsTime: <?php echo $this->getShowTime()?>,
	button: '<?php echo $this->getFieldId()?>',
	align: 'Bl',
	singleClick: true
});

</script>
