<?php $hint = htmlspecialchars(trim($this->getField()->getHint())); ?>
<?php if (strlen($this->getFieldValue())) $hint = false; ?>
<?php if ($this->getField()->getType() == 'email'): ?>
<div class="input-group">
    <span class="input-group-addon">@</span>
<?php endif; ?>
<?php if ($hint && $this->getField()->getType() != 'email'): ?>
    <div class="input-group">
        <span class="input-group-addon"><?php echo $hint; ?></span>
<?php endif; ?>
    <input type='text' name='<?php echo $this->getFieldName() ?>' id='<?php echo $this->getFieldId() ?>'
           class='<?php echo $this->getFieldClass() ?> form-control' style='<?php echo $this->getFieldStyle() ?>'
           value="<?php echo htmlspecialchars($this->getFieldValue()); ?>"
           placeholder="<?php echo $this->getField()->getName(); ?>"
           <?php if ($this->getField()->getType() == 'email'): ?>onkeyup="if(this.value.search(' ')>=0){this.value = this.value.replace(' ','');}"<?php endif; ?>
           <?php if ($this->getField()->getDisabled()): ?> disabled <?php endif; ?> />
<?php if ($this->getField()->getType() == 'email' || $hint): ?>
</div>
<?php endif; ?>