<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-homepage"><?php echo Mage::helper('homepage')->__('Home Pages Manager') ?></h3></td>
            <td class="a-right">
                <?php echo $this->getAddNewButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getStoreSwitcherHtml() ?>
        <div>
    <?php
    echo $this->getGridHtml() ?>
</div>