<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-homepage"><?php echo Mage::helper('homepage')->__('Home Pages Manager') ?></h3></td>
            <td class="a-right">
                <?php echo $this->getAddNewButtonHtml() ?>
				<?php echo $this->getPreviewButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getStoreSwitcherHtml() ?>
<div>
    <?php
    echo $this->getGridHtml() ?>
</div>
<script type="text/javascript">
	function previewStoreHomepage()
	{
		<?php if (Mage::app()->isSingleStoreMode()): ?>
			<?php if (!Mage::helper('homepage')->isHomepageModuleUsed()): ?>
				alert('The homepage module is not used to generate homepages at the moment, please enable under System > Configuration > Factory X > Homepage');
			<?php else: ?>
				previewUrl = "<?php echo Mage::getUrl("homepage/index/storepreview", array('_store' => 0)); ?>";
				window.open(previewUrl,'_blank');
			<?php endif; ?>
		<?php else: ?>
			if ($('store_switcher').selectedIndex == 0)
			{
				alert('Please select a store in the store switcher to preview a store home page');
			}
			else
			{
				<?php if (!Mage::helper('homepage')->isHomepageModuleUsed((int) $this->getRequest()->getParam('store'))): ?>
					alert('The homepage module is not used to generate homepages for this store at the moment, please enabled under System > Configuration > Factory X > Homepage');
				<?php else: ?>
					previewUrl = "<?php echo Mage::getUrl("homepage/index/storepreview", array('_store' => (int) $this->getRequest()->getParam('store'))); ?>";
					window.open(previewUrl,'_blank');
				<?php endif; ?>
			}
		<?php endif; ?>
	}
</script>