<div class="footer_left pull-left">
    <!--- from static block identifier name : footer_links --> 
    <?php //echo $this->getChildHtml('footerLinks'); ?>
    <?php echo $this->getChildHtml('cms_footer_links') ?>
    <?php //echo $this->getChildHtml('footerCurrency'); ?>
</div>
<!--- from static block identifier name : social-links --> 
<div class="footer_right pull-right">
    <?php echo $this->getChildHtml('social-links') ?>
</div>
<?php //echo $this->getChildHtml('htmlinject') ?>
<?php echo $this->getChildHtml('feedback') ?>
<?php echo $this->getChildHtml('popup') ?>