<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="container-fluid">
    <div class="row">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-lg-3 col-sm-3 hidden-xs text-left text-uppercase text-left">
                    <?php echo $this->getChildHtml('headerCurrency') ?>
                </div>
                <div class="col-md-5 col-lg-5 col-sm-5 col-xs-12 text-center text-uppercase text-center">
                    <?php echo $this->getChildHtml('notification') ?>
                </div>
                <div class="col-md-4 col-lg-4 col-sm-4 hidden-xs text-right text-uppercase text-right">
                    <?php echo $this->getChildHtml('topLinks') ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 text-center">
            <?php if ($this->getIsHomePage()):?>
                <h1 class="logo">
                    <a href="<?php echo $this->getUrl('') ?>"
                       title="<?php echo $this->getLogoAlt() ?>"
                       class="logo">
                        <img class="img-responsive center-block"
                             src="<?php echo $this->getLogoSrc() ?>"
                             alt="<?php echo $this->getLogoAlt() ?>" />
                    </a>
                </h1>
            <?php else:?>
                <a href="<?php echo $this->getUrl('') ?>"
                   title="<?php echo $this->getLogoAlt() ?>"
                   class="logo notitle">
                    <img class="img-responsive center-block"
                         src="<?php echo $this->getLogoSrc() ?>"
                         alt="<?php echo $this->getLogoAlt() ?>" />
                </a>
            <?php endif?>
        </div>
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 quick-access">
            <?php echo $this->getChildHtml('store_language') ?>
            <div class="welcome-msg text-right">
                <?php
                    /** @noinspection PhpUndefinedMethodInspection */
                    echo $this->getAdditionalHtml()
                ?>
            </div>
        </div>
        <?php echo $this->getChildHtml('topContainer'); ?>
    </div>
</div>
<div class="container">
    <div class="row" id="row-menu">
        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>
    </div>
</div>
