<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
	<div class="header_top">
		<div class="container">
			<div class="header_top_cell header_top_left">
				<?php echo $this->getChildHtml('headerCurrency') ?>
			</div>
			<div class="header_top_cell header_top_middle text-center">
				<?php echo $this->getChildHtml('notification') ?>
			</div>
			<div class="header_top_cell header_top_right clearfix">
				<?php echo $this->getChildHtml('topLinks') ?>
			</div>
		</div>
	</div>
		
	<div class="header_bottom">	
		<div class="container">
			<div class="responsive_header_left">
				<button type="button" class="responsive_nav_ico">
					<img class="bar_ico" src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
					<img src="<?php echo Mage::getDesign()->getSkinUrl();?>images/nav_cross.png" alt="nav_cross" class="nav_cross_ico" />
				</button>
			</div>
			<?php if ($this->getIsHomePage()):?>
				<a href="<?php echo $this->getUrl('') ?>"
					title="<?php echo $this->getLogoAlt() ?>"
					class="navbar-brand">
					<img
						src="<?php echo $this->getLogoSrc() ?>"
						alt="<?php echo $this->getLogoAlt() ?>" />
				</a>
			<?php else:?>
				<a href="<?php echo $this->getUrl('') ?>"
					title="<?php echo $this->getLogoAlt() ?>"
					class="navbar-brand">
					<img
					    src="<?php echo $this->getLogoSrc() ?>"
					    alt="<?php echo $this->getLogoAlt() ?>" />
				</a> 					 
			<?php endif?>
			
			<div class="row">
			    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 quick-access">
				   <?php echo $this->getChildHtml('store_language') ?>
				   <div class="welcome-msg text-right">
					  <?php
						 /** @noinspection PhpUndefinedMethodInspection */
						 echo $this->getAdditionalHtml()
					  ?>
				   </div>
			    </div>
			    <?php echo $this->getChildHtml('topContainer'); ?>
			</div>
		</div>
		
		<div class="header_nav_wrapper">
			<div class="container">
				<div class="site_nav_area clearfix">
					<nav class="main_nav pull-left">
						<?php echo $this->getChildHtml('topMenu') ?>
					</nav>
					<div class="site_search pull-right">
						<?php echo $this->getChildHtml('topSearch') ?>
					</div>
				</div>
			</div>
		</div>
		
		
		
	</div>