<?php

/**
 * Retail Evolved - Facebook Like Analytics
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA that is bundled with this
 * package in the file EVOLVED_EULA.txt.
 * It is also available through the world-wide-web at this URL:
 * http://retailevolved.com/eula-1-0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to service@retailevolved.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * You may edit this file, but only at your own risk, as long as it is within
 * the constraints of the license agreement. Before upgrading the module (not Magento), 
 * be sure to back up your original installation as the upgrade may override your
 * changes.
 *
 * @category   Evolved
 * @package    Evolved_LikeAnalytics
 * @copyright  Copyright (c) 2010 Kaelex Inc. DBA Retail Evolved (http://retailevolved.com)
 * @license    http://retailevolved.com/eula-1-0 (Retail Evolved EULA 1.0)
 */

class Evolved_LikeAnalytics_Adminhtml_ViewController extends Mage_Adminhtml_Controller_Action
{
	/**
     * Retrieve session model
     *
     * @return Mage_Adminhtml_Model_Session
     */
    protected function _getSession()
    {
        return Mage::getSingleton('adminhtml/session');
    }

	protected function _initAction() {
		$this->loadLayout()
			->_setActiveMenu('evlikeanalytics/view');
			
			return $this;
	}
	
	public function indexAction() {
		$this->loadLayout()
			->_setActiveMenu('evlikeanalytics/view')
			->_addContent($this->getLayout()->createBlock('evlikeanalytics/adminhtml_view'))
			->renderLayout();
	}
	
	public function newAction() {
		$this->_getSession()->addError(Mage::helper('evlikeanalytics')->__("Adding statistics is not allowed - statistics are generated by going to Like Analytics->Refresh Stats"));
		
		$this->_redirect('*/*');
	}
	
	public function exportCsvAction() {
		$fileName   = 'facebook_stats.csv';
		$block = $this->getLayout()->createBlock('evlikeanalytics/adminhtml_view_grid');
		
        $content = $block->getCsv();
		
        $this->_prepareDownloadResponse($fileName, $content);
	}
}