<?php
/**
 * @author         Vladimir Popov
 * @copyright      Copyright (c) 2014 Vladimir Popov
 */

/** @var VladimirPopov_WebForms_Block_Webforms $this */

// in case redirect fails
if (Mage::registry('redirect_url')) {
    ?>
    <meta http-equiv="refresh" content="0;url=<?php echo Mage::registry('redirect_url') ?>">
    <script type="text/javascript">
        window.location = '<?php echo Mage::registry('redirect_url')?>';
    </script>
<?php
}

// get temporary data
$tmpData = Mage::getSingleton('core/session')->getData('webform_result_tmp_' . $this->getWebform()->getId());
$tmpResult = new Varien_Object();
if (!empty($tmpData['field']) && is_array($tmpData['field'])) {
    foreach ($tmpData['field'] as $field_id => $value) {
        $tmpResult->setData('field_' . $field_id, $value);
    }
}

if ($this->getWebform()->getIsActive() == VladimirPopov_WebForms_Model_Webforms::STATUS_DISABLED || !$this->isDirectAvailable()) {
    echo $this->getNotAvailableMessage();
} else {

    if (Mage::registry('show_form_name')) {
        ?>
        <div class="page-title">
            <h1><?php echo $this->getWebform()->getName(); ?></h1>
        </div>
    <?php } ?>

    <?php if ($this->isAjax()) { ?>
        <div id="webform_<?php echo $this->getWebform()->getId() ?>_success_text" class="std webforms-success-text"
             style="display:none"></div>
    <?php } ?>

    <?php
    if (Mage::registry('show_success')) {
        ?>
        <div class="std webforms-success-text">
            <?php echo $this->getWebform()->getSuccessText() ?>
        </div>
    <?php
    } else {
        ?>

        <div id="webform_<?php echo $this->getWebform()->getId() ?>_form">

            <?php if ($this->getWebform()->getDescription()) { ?>
                <div class="std">
                    <?php echo $this->getWebform()->getDescription(); ?>
                </div>
            <?php } ?>

            <?php if ($this->isAjax()) { ?>
                <iframe id="webform_<?php echo $this->getWebform()->getId() ?>_iframe"
                        name="webform_<?php echo $this->getWebform()->getId() ?>_iframe"
                        style="width:0;height:0;border:0;position:absolute"></iframe>
            <?php } ?>

            <form action="<?php echo $this->getFormAction() ?>" method="post"
                  name="webform_<?php echo $this->getWebform()->getId() ?>"
                  id="webform_<?php echo $this->getWebform()->getId() ?>" enctype="<?php echo $this->getEnctype() ?>"
                  class="webforms-<?php echo $this->getWebform()->getCode() ?>"
                  <?php if ($this->isAjax()) { ?>target="webform_<?php echo $this->getWebform()->getId() ?>_iframe"<?php } ?>>


                <input type="hidden" name="submitWebform_<?php echo $this->getWebform()->getId() ?>" value="1"/>
                <input type="hidden" name="webform_id" value="<?php echo $this->getWebform()->getId() ?>"/>

                <?php if (is_array($this->getData('hidden'))) {
                    foreach ($this->getData('hidden') as $key => $value) {
                        ?>
                        <input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>"/>
                    <?php
                    }
                }?>

                <?php if (count($this->getWebform()->_getHidden())) {
                    foreach ($this->getWebform()->_getHidden() as $field) {
                        echo $field->toHtml();
                    }
                } ?>

                <?php foreach ($this->getWebform()->_getFieldsToFieldsets() as $fieldset_id => $fieldset): ?>

                    <fieldset id="fieldset_<?php echo $fieldset_id ?>" class="fieldset fieldset-<?php echo $fieldset_id ?> <?php if(!empty($fieldset['css_class'])) echo $fieldset['css_class'];?>"
                        <?php if ($fieldset['logic_visibility'] == VladimirPopov_WebForms_Model_Logic::VISIBILITY_HIDDEN) echo 'style="display:none"'; ?>>

                        <?php if (!empty($fieldset['name'])) { ?>
                            <legend><?php echo $fieldset['name'] ?></legend>
                        <?php } ?>

                        <?php
                        $fields_count = count($fieldset['fields']);
                        foreach ($fieldset['fields'] as $field):

                            // set temporary value
                            $field->setData('result', $tmpResult);

                            $size_class = "col-md-6 col-lg-6 col-sm-6 col-xs-12";
                            if ($field->getSize() == 'wide') {
                                $size_class = "col-xs-12 col-lg-12 col-sm-12 col-md-12";
                            }

                            ?>
                            <?php
                            $field_css_type = 'type-' . str_replace('/', '-', $field->getType());
                            ?>
                            <div id="field_<?php echo $field->getId() ?>_row"
                                class="<?php echo $size_class ?> <?php echo $field->getCssClassContainer()?> <?php echo $field_css_type ?> webforms-fields-<?php echo $field->getId() ?>"
                                <?php if ($field->getData('logic_visibility') == VladimirPopov_WebForms_Model_Logic::VISIBILITY_HIDDEN) echo 'style="display:none"'; ?>>

                                <?php if (($field->getType() != 'html' && $field->getType() != 'subscribe') && ($field->getType() == 'select/radio' || $field->getType() == "select/checkbox" || $field->getType() == "select")) { ?>
                                    <label id="label_field<?php echo $field->getId() ?>"
                                           for="field<?php echo $field->getId() ?>"
                                           <?php if ($field->getRequired()) { ?>class="required"<?php } ?>>
                                        <?php if ($field->getRequired()) { ?>
                                            <em>*</em>
                                        <?php } ?>
                                        <?php echo $field->getName() ?>
                                        <?php
                                        $tooltip = $field->getTooltip();
                                        if ($tooltip) {
                                            echo $this->getLayout()->createBlock(
                                                'core/template',
                                                'field' . $field->getId() . '_tooltip',
                                                array(
                                                    'field' => $field,
                                                    'tooltip' => $tooltip,
                                                    'template' => 'webforms/scripts/tooltip.phtml',
                                                )
                                            )->toHtml();
                                        }
                                        ?>
                                    </label>
                                <?php } ?>

                                <div class="form-group">
                                    <?php echo $field->toHtml(); ?>

                                    <?php if ($field->getComment()) { ?>
                                        <p class="webforms-fields-comment">
                                            <?php echo nl2br($field->getComment()) ?>
                                        </p>
                                    <?php } ?>

                                    <?php if ($field->getValidationAdvice()) { ?>
                                        <div style="display:none" class="validation-advice"
                                             id="advice-required-entry-field<?php echo $field->getId() ?>">
                                            <?php echo $field->getValidationAdvice() ?>
                                        </div>
                                    <?php } ?>
                                </div>

                            </div>
                        <?php endforeach; ?>
                    </fieldset>

                <?php endforeach; ?>

                <?php if (Mage::registry('use_captcha')): ?>
                    <?php echo $this->getCaptcha()->getHTML() ?>
                <?php endif; ?>

                <?php if (Mage::getStoreConfig('webforms/honeypot/enable')): ?>
                    <?php echo $this->getLayout()->createBlock(
                        'core/template',
                        'webform_' . $this->getWebform()->getId() . '_honeypot',
                        array(
                            'webform' => $this->getWebform(),
                            'template' => 'webforms/scripts/honeypot.phtml',
                        )
                    )->toHtml(); ?>
                <?php endif; ?>

                <div class="buttons-set col-lg-12 col-md-12 col-xs-12 col-sm-12">
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <button type="button" class="btn btn-primary button pull-right"
                            id="webform_<?php echo $this->getWebform()->getId() ?>_submit_button"
                            onclick="webform_<?php echo $this->getWebform()->getId() ?>_submit()"
                            title="<?php echo $this->__('submit') ?>">
			<span>
				<span><?php echo $this->__($this->getWebform()->getSubmitButtonText()) ?></span>
			</span>
                    </button>
		<span class="please-wait" id="webform_<?php echo $this->getWebform()->getId() ?>_sending_data"
              style="display:none;">
			<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
                 alt="<?php echo $this->__('Sending...') ?>" title="<?php echo $this->__('Sending...') ?>"
                 class="v-middle"/><span
                id="webform_<?php echo $this->getWebform()->getId() ?>_progress_text"><?php echo $this->__('Sending...') ?></span>
		</span>
                </div>

            </form>

        </div>

        <?php echo $this->getLayout()->createBlock(
            'core/template',
            'webform_' . $this->getWebform()->getId() . '_submit_script',
            array(
                'webform' => $this->getWebform(),
                'ajax' => $this->isAjax(),
                'template' => 'webforms/scripts/submit.phtml',
                'scroll_to' => $this->getData('scroll_to'),
            )
        )->toHtml();
        ?>

        <?php echo $this->getLayout()->createBlock(
            'core/template',
            'webform_' . $this->getWebform()->getId() . '_logic',
            array(
                'webform' => $this->getWebform(),
                'template' => 'webforms/scripts/logic.phtml',
            )
        )->toHtml();
        ?>

    <?php
    } // if(show_success)
} // is active