<?php
$idssukk=$_REQUEST['id'];
$issukk = 0;
$collectionssukk = Mage::getModel('Jobs/Jobs')->getCollection();
	//print_r($collection);
    //$collection->setPageSize(5);
    //$collection->setCurPage(2);
    //$size = $collection->getSize();
    $cntssukk = count($collectionssukk);
    foreach ($collectionssukk as $itemssukk) {
        $issukk = $issukk+1;
        $itemssukk->setTitle($issukk);
		//echo $itemssukk->getTitle();
		//echo $itemssukk->getId();
		//echo $idssukk;
		if($itemssukk->getId()==$idssukk)
		{
		//$countryssukk=$itemssukk->getCountrys();
		$adminemail=$itemssukk->getEmail();
		}
		}
	//echo $adminemail;
if($_POST['Send'])
{
$to  = $adminemail;
        $subject = 'Job Application'; //Specify Email Subject
        $message = "<table width=\"330\" align=\"center\" width:\"120%\">
<tr><td style=\"border-color:#00FFFF; border:7px solid;\" width:\"110%\">

<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#999999\" style=\"padding:20px\">


	
	
    <tr>
			   
    <td colspan=\"6\" align=\"center\" style=\"color:#990099; size:portrait;\"><strong>Job Application Details:</strong></td>
    </tr>
	<tr>
    <td colspan=\"6\" align=\"center\" style=\"color:#990099; size:portrait;\"><strong>&nbsp;</strong></td>
    </tr>
   
	<tr>
    <td width=424><strong>First Name:</strong></td> 
    <td>$_POST[fname]</td>
	</tr>
	<tr>
    <td width=424><strong>Surname:</strong></td>
    <td>$_POST[sname]</td></tr>
	 <tr>
    <td width=424><strong>Email:</strong></td>
    <td width=330>$_POST[email]</td>
    </tr>
	 <tr>
    <td width=424><strong>Phone:</strong></td>
    <td width=330>$_POST[phone]</td>
    </tr>
	 <tr>
    <td width=424><strong>Gender:</strong></td>
    <td width=330>$_POST[gender]</td>
    </tr>
	<tr>
    <td width=424><strong>Country:</strong></td>
    <td width=330>$_POST[country]</td>
    </tr>
	<tr>
	<td width=424><strong>Location:</strong></td> 
	<td>$_POST[location]</td></tr>
	<tr>
    <td width=424><strong>Residency Status:</strong></td>
    <td width=330>$_POST[residency]</td>
    </tr>
	<tr>
    <td width=424><strong>Interested</strong></td>
    <td width=330>$_POST[interest]</td>
    </tr>
	<tr>
    <td width=424><strong>Jobs Type</strong></td>
    <td width=330>$_POST[type]</td>
    </tr>
</table>
	
 </td> </tr>
</table>";

 //echo "Your Application post successfully";

 //Specify Email Message
        $headers  = 'MIME-Version: 1.0' . "\r\n";
        $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
        //To send HTML mail, the Content-type header must be set
        $headers .= 'From: '.$_POST['fname'].' <'.$_POST['email'].'>' . "\r\n"; //Specify Sender
        //$headers .= 'Cc: user<user1@mail.com>' . "\r\n"; //Specify CC user
        //$headers .= 'Cc: user<user2@mail.com>' . "\r\n"; //Specify Bcc User
        if(mail($to, $subject, $message, $headers))
		{
		   echo "Your Application post successfully sent";

		}
$to1  = $_POST['email'];
        $subject1 = 'Job Application'; //Specify Email Subject
        $message1 = "<table width=892 align=\"center\" width:\"120%\">
<tr><td style=\"border-color:#00FFFF; border:7px solid;\" width:\"110%\">

<table width=\"90%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#999999\" style=\"padding:20px\">


	
	
   
	
	<tr>
    <td width=897><strong>Your mail send successfully.we contact you urgently</strong></td> 
	</tr>
	
</table>
	
 </td> </tr>
</table>
";

 //echo "Your Application post successfully";

 //Specify Email Message
        $headers1  = 'MIME-Version: 1.0' . "\r\n";
        $headers1 .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
        //To send HTML mail, the Content-type header must be set
        $headers1 .= 'From: '."Admin".' <'.$adminemail.'>' . "\r\n"; //Specify Sender
        //$headers .= 'Cc: user<user1@mail.com>' . "\r\n"; //Specify CC user
        //$headers .= 'Cc: user<user2@mail.com>' . "\r\n"; //Specify Bcc User

        if(mail($to1, $subject1, $message1, $headers1))
		{
		   //echo "Your Application post successfully";

		}
		

}
?>
<script type="text/javascript">
function checkform()
{
if(document.mailform.fname.value=="")
		{
		alert("Please Enter Your First Name");
		document.mailform.fname.focus();
		return false;
		}
if(IsNumeric(document.mailform.fname.value)==true)
        {
		alert("Please Enter Proper First Name");
		document.mailform.fname.focus();
		return false;
		}			

if(document.mailform.sname.value=="")
		{
		alert("Please Enter Your Surname");
		document.mailform.sname.focus();
		return false;
		}
if(IsNumeric(document.mailform.sname.value)==true)
        {
		alert("Please Enter Proper Surname");
		document.mailform.sname.focus();
		return false;
		}

if(document.mailform.email.value=="")
		{
		alert("Please Enter Your Email Id");
		document.mailform.email.focus();
		return false;
		}
if(email(document.mailform.email.value)==false)
		{
		alert("Invalid E-mail ID ");
		document.mailform.email.focus();
		return false;
		}	

if(document.mailform.phone.value=="")
		{
		alert("Please Enter Your Phone no");
		document.mailform.phone.focus();
		return false;
		}
if(IsNumeric(document.mailform.phone.value)==false)
        {
		alert("Please Enter Proper Phone no");
		document.mailform.phone.focus();
		return false;
		}
if(document.mailform.country.value=="")
		{
		alert("Please Enter Your Country name");
		document.mailform.country.focus();
		return false;
		}
if(document.mailform.location.value=="")
		{
		alert("Please Enter Your Location name");
		document.mailform.location.focus();
		return false;
		}



	

}

/*CHECK EMAIL EXTENSION*/
function email(str) {

		var at="@"
		var dot="."
		var lat=str.indexOf(at)
		var lstr=str.length
		var ldot=str.indexOf(dot)
		if (str.indexOf(at)==-1){
		   return false
		}

		if (str.indexOf(at)==-1 || str.indexOf(at)==0 || str.indexOf(at)==lstr){
		   return false
		}

		if (str.indexOf(dot)==-1 || str.indexOf(dot)==0 || str.indexOf(dot)==lstr){
		    return false
		}

		 if (str.indexOf(at,(lat+1))!=-1){
		    return false
		 }

		 if (str.substring(lat-1,lat)==dot || str.substring(lat+1,lat+2)==dot){
		    return false
		 }

		 if (str.indexOf(dot,(lat+2))==-1){
		     return false
		 }
		
		 if (str.indexOf(" ")!=-1){
		    return false
		 }

 		 return true					
	}
	/*CHECK WHETHER VALUE IS A NUMBER*/
function IsNumeric(sText)
{
   var ValidChars = "0123456789.+";
   var IsNumber=true;
   var Char;
   for (i = 0; i < sText.length && IsNumber == true; i++) 
      { 
      Char = sText.charAt(i); 
      if (ValidChars.indexOf(Char) == -1) 

         {

         IsNumber = false;
         }

      }

   return IsNumber;

 }

</script>
<style type="text/css">
  .content{ float:left; color:#666; font-size:12px !important; font-weight:normal; font-family:Verdana, Geneva, sans-serif;}
   .content a{ float:left; text-decoration:none; font-size:12px; color:#CCC; font-weight:normal; padding-left:10px;}
   .content a:hover{ color:#000;}
   .cell53{ font-size:12px; line-height:20px;}
   .submitButton{ float:left; background:url(<?php echo $this->getSkinUrl('images/xigjobsubmit.jpg') ?>) no-repeat; width:124px; height:30px; border:none;}
</style>


 <form action="" name="mailform" method="post" onSubmit="return checkform();" >
<div style="width:700px; background:#FAF2EE; border:1px solid #F9C; float:left;">
<table width="100%" cellspacing="0" cellpadding="3" border="0" class="content" bgcolor="#FCE4D8" style="padding-left:15px;">
        
        <tbody>
        <tr>
          <td width="50%" class="cell53">&nbsp;</td>
          <td width="50%" class="cell53"><font color="#595959"></font></td>
        </tr>
        

				            		<tr id="pfrowid136785926_1000000">
				            		<td width="50%" align="left" class="cell53">
							<font color="#595959">*</font>First Name</td>
							        <td width="50%" align="left" class="cell53">


							        	<font class="inputnn4fix">
							        		<input type="text" value="" name="fname" onChange="" onpaste=" " style="width:168px;" class="inputbox">
							            </font>
							        </td>

								</tr>			        

				            		<tr id="pfrowid136785926_1000001">
				            		<td width="50%" align="left" class="cell53">
							<font color="#595959">*</font>Surname</td>
							        <td width="50%" align="left" class="cell53">
							        	<font class="inputnn4fix">
							        		<input type="text" value="" name="sname" onChange="" onpaste="" style="width:168px;" class="inputbox">
							            </font>
							        </td>

								</tr>		        

				            		<tr id="pfrowid136785926_1000003">
				            		<td width="50%" align="left" class="cell53">
							<font color="#595959">*</font>Email</td>
							        <td width="50%" align="left" class="cell53">
							        	<font class="inputnn4fix">
							        		<input type="text" value="" name="email" onChange="" onpaste="" style="width:168px;" class="inputbox">
							            </font>
							        </td>

								</tr>

						        

				            		<tr id="pfrowid136785926_1000004">
				            		<td width="50%" align="left" class="cell53">
							<font color="#595959">*</font>Phone</td>
							        <td width="50%" align="left" class="cell53">
							        	<font class="inputnn4fix">
							        		<input type="text" value="" name="phone" onChange="validate(this,'5','0','255','2')" onpaste="" style="width:168px;" class="inputbox">
							            </font>
							        </td>

								</tr>

						        

				            		<tr id="pfrowid136785926_1000009">
				            		<td width="50%" align="left" class="cell53">
							<font color="#595959">*</font>Gender</td>
							        <td width="50%" align="left" class="cell53">
							        	
							<select name="gender" class="inputbox" style="font-size:11px;width:168px;"><option value="Male">Male</option><option value="Female">Female</option></select>
							           
							        </td>

								</tr>

						        


						        
							<tr id="pfrowid136785926_1000014">
							<td width="50%" align="left" class="cell53">
							<font color="#595959">*</font>Country</td><td width="50%" align="left" class="cell53">
			            	<select onChange="" name="country" class="inputbox" style="font-size:11px;width:168px;">

			            	<option value="">Please choose your country</option><option value="Afghanistan">Afghanistan</option>
	<option value="Afghanistan">Afghanistan</option>
	<option value="Albania">Albania</option>
	<option value="Algeria">Algeria</option>
	<option value="American Samoa">American Samoa</option>
	<option value="Andorra">Andorra</option>
	<option value="Angola">Angola</option>
	<option value="Anguilla">Anguilla</option>
	<option value="Antarctica">Antarctica</option>
	<option value="Antigua And Barbuda">Antigua And Barbuda</option>
	<option value="Argentina">Argentina</option>
	<option value="Armenia">Armenia</option>
	<option value="Aruba">Aruba</option>
	<option value="Australia">Australia</option>
	<option value="Austria">Austria</option>
	<option value="Azerbaijan">Azerbaijan</option>
	<option value="Bahamas">Bahamas</option>
	<option value="Bahrain">Bahrain</option>
	<option value="Bangladesh">Bangladesh</option>
	<option value="Barbados">Barbados</option>
	<option value="Belarus">Belarus</option>
	<option value="Belgium">Belgium</option>
	<option value="Belize">Belize</option>
	<option value="Benin">Benin</option>
	<option value="Bermuda">Bermuda</option>
	<option value="Bhutan">Bhutan</option>
	<option value="Bolivia">Bolivia</option>
	<option value="Bosnia And Herzegowina">Bosnia And Herzegowina</option>
	<option value="Botswana">Botswana</option>
	<option value="Bouvet Island">Bouvet Island</option>
	<option value="Brazil">Brazil</option>
	<option value="British Indian Ocean Territory">British Indian Ocean Territory</option>
	<option value="Brunei Darussalam">Brunei Darussalam</option>
	<option value="Bulgaria">Bulgaria</option>
	<option value="Burkina Faso">Burkina Faso</option>
	<option value="Burundi">Burundi</option>
	<option value="Cambodia">Cambodia</option>
	<option value="Cameroon">Cameroon</option>
	<option value="Canada">Canada</option>
	<option value="Cape Verde">Cape Verde</option>
	<option value="Cayman Islands">Cayman Islands</option>
	<option value="Central African Republic">Central African Republic</option>
	<option value="Chad">Chad</option>
	<option value="Chile">Chile</option>
	<option value="China">China</option>
	<option value="Christmas Island">Christmas Island</option>
	<option value="Cocos (Keeling) Islands">Cocos (Keeling) Islands</option>
	<option value="Colombia">Colombia</option>
	<option value="Comoros">Comoros</option>
	<option value="Congo">Congo</option>
	<option value="Cook Islands">Cook Islands</option>
	<option value="Costa Rica">Costa Rica</option>
	<option value="Cote D'Ivoire">Cote D'Ivoire</option>
	<option value="Croatia">Croatia</option>
	<option value="Cuba">Cuba</option>
	<option value="Cyprus">Cyprus</option>
	<option value="Czech Republic">Czech Republic</option>
	<option value="Denmark">Denmark</option>
	<option value="Djibouti">Djibouti</option>
	<option value="Dominica">Dominica</option>
	<option value="Dominican Republic">Dominican Republic</option>
	<option value="East Timor">East Timor</option>
	<option value="Ecuador">Ecuador</option>
	<option value="Egypt">Egypt</option>
	<option value="El Salvador">El Salvador</option>
	<option value="Equatorial Guinea">Equatorial Guinea</option>
	<option value="Eritrea">Eritrea</option>
	<option value="Estonia">Estonia</option>
	<option value="Ethiopia">Ethiopia</option>
	<option value="Falkland Islands">Falkland Islands</option>
	<option value="Faroe Islands">Faroe Islands</option>
	<option value="Fiji">Fiji</option>
	<option value="Finland">Finland</option>
	<option value="France">France</option>
	<option value="French Guiana">French Guiana</option>
	<option value="French Polynesia">French Polynesia</option>
	<option value="French Southern Territories">French Southern Territories</option>
	<option value="Gabon">Gabon</option>
	<option value="Gambia">Gambia</option>
	<option value="Georgia">Georgia</option>
	<option value="Germany">Germany</option>
	<option value="Ghana">Ghana</option>
	<option value="Gibraltar">Gibraltar</option>
	<option value="Greece">Greece</option>
	<option value="Greenland">Greenland</option>
	<option value="Grenada">Grenada</option>
	<option value="Guadeloupe">Guadeloupe</option>
	<option value="Guam">Guam</option>
	<option value="Guatemala">Guatemala</option>
	<option value="Guinea">Guinea</option>
	<option value="Guinea-Bissau">Guinea-Bissau</option>
	<option value="Guyana">Guyana</option>
	<option value="Haiti">Haiti</option>
	<option value="Heard And Mc Donald Islands">Heard And Mc Donald Islands</option>
	<option value="Honduras">Honduras</option>
	<option value="Hong Kong">Hong Kong</option>
	<option value="Hungary">Hungary</option>
	<option value="Iceland">Iceland</option>
	<option value="India">India</option>
	<option value="Indonesia">Indonesia</option>
	<option value="Iran">Iran</option>
	<option value="Iraq">Iraq</option>
	<option value="Ireland">Ireland</option>
	<option value="Israel">Israel</option>
	<option value="Italy">Italy</option>
	<option value="Jamaica">Jamaica</option>
	<option value="Japan">Japan</option>
	<option value="Jordan">Jordan</option>
	<option value="Kazakhstan">Kazakhstan</option>
	<option value="Kenya">Kenya</option>
	<option value="Kiribati">Kiribati</option>
	<option value="Kuwait">Kuwait</option>
	<option value="Kyrgyzstan">Kyrgyzstan</option>
	<option value="Lao People's Republic">Lao People's Republic</option>
	<option value="Latvia">Latvia</option>
	<option value="Lebanon">Lebanon</option>
	<option value="Lesotho">Lesotho</option>
	<option value="Liberia">Liberia</option>
	<option value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</option>
	<option value="Liechtenstein">Liechtenstein</option>
	<option value="Lithuania">Lithuania</option>
	<option value="Luxembourg">Luxembourg</option>
	<option value="Macau">Macau</option>
	<option value="Macedonia">Macedonia</option>
	<option value="Madagascar">Madagascar</option>
	<option value="Malawi">Malawi</option>
	<option value="Malaysia">Malaysia</option>
	<option value="Maldives">Maldives</option>
	<option value="Malta">Malta</option>
	<option value="Marshall Islands">Marshall Islands</option>
	<option value="Martinique">Martinique</option>
	<option value="Mauritania">Mauritania</option>
	<option value="Mauritius">Mauritius</option>
	<option value="Mayotte">Mayotte</option>
	<option value="Mexico">Mexico</option>
	<option value="Micronesia">Micronesia</option>
	<option value="Moldova">Moldova</option>
	<option value="Monaco">Monaco</option>
	<option value="Mongolia">Mongolia</option>
	<option value="Montserrat">Montserrat</option>
	<option value="Morocco">Morocco</option>
	<option value="Mozambique">Mozambique</option>
	<option value="Myanmar">Myanmar</option>
	<option value="Namibia">Namibia</option>
	<option value="Nauru">Nauru</option>
	<option value="Nepal">Nepal</option>
	<option value="Netherlands">Netherlands</option>
	<option value="Netherlands Antilles">Netherlands Antilles</option>
	<option value="New Caledonia">New Caledonia</option>
	<option value="New Zealand">New Zealand</option>
	<option value="Nicaragua">Nicaragua</option>
	<option value="Niger">Niger</option>
	<option value="Nigeria">Nigeria</option>
	<option value="Niue">Niue</option>
	<option value="Norfolk Island">Norfolk Island</option>
	<option value="North Korea (People's Republic Of Korea)">North Korea (People's Republic Of Korea)</option>
	<option value="Northern Mariana Islands">Northern Mariana Islands</option>
	<option value="Norway">Norway</option>
	<option value="Oman">Oman</option>
	<option value="Other Not Shown">Other Not Shown</option>
	<option value="Pakistan">Pakistan</option>
	<option value="Palau">Palau</option>
	<option value="Panama">Panama</option>
	<option value="Papua New Guinea">Papua New Guinea</option>
	<option value="Paraguay">Paraguay</option>
	<option value="Peru">Peru</option>
	<option value="Philippines">Philippines</option>
	<option value="Pitcairn">Pitcairn</option>
	<option value="Poland">Poland</option>
	<option value="Portugal">Portugal</option>
	<option value="Puerto Rico">Puerto Rico</option>
	<option value="Qatar">Qatar</option>
	<option value="Reunion">Reunion</option>
	<option value="Romania">Romania</option>
	<option value="Russian Federation">Russian Federation</option>
	<option value="Rwanda">Rwanda</option>
	<option value="Saint Kitts And Nevis">Saint Kitts And Nevis</option>
	<option value="Saint Lucia">Saint Lucia</option>
	<option value="Saint Vincent And The Grenadines">Saint Vincent And The Grenadines</option>
	<option value="Samoa">Samoa</option>
	<option value="San Marino">San Marino</option>
	<option value="Sao Tome And Principe">Sao Tome And Principe</option>
	<option value="Saudi Arabia">Saudi Arabia</option>
	<option value="Senegal">Senegal</option>
	<option value="Seychelles">Seychelles</option>
	<option value="Sierra Leone">Sierra Leone</option>
	<option value="Singapore">Singapore</option>
	<option value="Slovakia">Slovakia</option>
	<option value="Slovenia">Slovenia</option>
	<option value="Solomon Islands">Solomon Islands</option>
	<option value="Somalia">Somalia</option>
	<option value="South Africa">South Africa</option>
	<option value="South Korea (Republic Of Korea)">South Korea (Republic Of Korea)</option>
	<option value="Spain">Spain</option>
	<option value="Sri Lanka">Sri Lanka</option>
	<option value="St Helena">St Helena</option>
	<option value="St Pierre and Miquelon">St Pierre and Miquelon</option>
	<option value="Sudan">Sudan</option>
	<option value="Suriname">Suriname</option>
	<option value="Svalbard And Jan Mayen Islands">Svalbard And Jan Mayen Islands</option>
	<option value="Swaziland">Swaziland</option>
	<option value="Sweden">Sweden</option>
	<option value="Switzerland">Switzerland</option>
	<option value="Syrian Arab Republic">Syrian Arab Republic</option>
	<option value="Taiwan">Taiwan</option>
	<option value="Tajikistan">Tajikistan</option>
	<option value="Tanzania">Tanzania</option>
	<option value="Thailand">Thailand</option>
	<option value="Togo">Togo</option>
	<option value="Tokelau">Tokelau</option>
	<option value="Tonga">Tonga</option>
	<option value="Trinidad And Tobago">Trinidad And Tobago</option>
	<option value="Tunisia">Tunisia</option>
	<option value="Turkey">Turkey</option>
	<option value="Turkmenistan">Turkmenistan</option>
	<option value="Turks And Caicos Islands">Turks And Caicos Islands</option>
	<option value="Tuvalu">Tuvalu</option>
	<option value="Uganda">Uganda</option>
	<option value="Ukraine">Ukraine</option>
	<option value="United Arab Emirates">United Arab Emirates</option>
	<option value="United Kingdom">United Kingdom</option>
	<option value="United States">United States</option>
	<option value="Uruguay">Uruguay</option>
	<option value="Uzbekistan">Uzbekistan</option>
	<option value="Vanuatu">Vanuatu</option>
	<option value="Vatican City State">Vatican City State</option>
	<option value="Venezuela">Venezuela</option>
	<option value="Viet Nam">Viet Nam</option>
	<option value="Virgin Islands (British)">Virgin Islands (British)</option>
	<option value="Virgin Islands (U.S.)">Virgin Islands (U.S.)</option>
	<option value="Wallis And Futuna Islands">Wallis And Futuna Islands</option>
	<option value="Western Sahara">Western Sahara</option>
	<option value="Yemen">Yemen</option>
	<option value="Zaire">Zaire</option>
	<option value="Zambia">Zambia</option>
	<option value="Zimbabwe">Zimbabwe</option>
	</select>
			            			</td>
			            			</tr>
			            			

				            		<tr id="pfrowid136785926_1000011">
				            		<td width="50%" align="left" class="cell53">
							<font color="#595959">*</font>Location</td>
							        <td width="50%" align="left" class="cell53">
							        	<font class="inputnn4fix">
							        		<input type="text" value="" name="location" onChange="" onpaste="" style="width:168px;" class="inputbox">
							            </font>
							        </td>

								</tr>

						        <tr id="pfrowid136785926_1000006">

			            <td width="50%" valign="top" align="left" class="cell53">
			            <font color="#595959">*</font>Residency Status</td>
   				    <td width="50%" align="left" class="cell53">
					<select name="residency" class="inputbox" style="font-size:11px;width:168px;"><option value="Australian Citizen">Australian Citizen</option>
	<option value="Permanent Resident">Permanent Resident</option>
	<option value="Work Visa Holder">Work Visa Holder</option>
	<option value="Other">Other</option>
	</select>
							           
   				     </td>

   				     </tr> 
			            <tr id="pfrowid136785926_1000006">

			            <td width="50%" valign="top" align="left" class="cell53">
			            <font color="#595959">*</font>Job Title</td>
   				    <td width="50%" align="left" class="cell53">

   				    	<b>I am interested in the following areas:
					<br></b>
				<select name="interest" class="inputbox"  style="font-size:11px;width:168px;"><option value="test1">test1</option>
	<option value="test2">test2</option>
	</select>
   				     </td>

   				     </tr>
 <tr id="pfrowid136785926_1000006">

			            <td width="50%" valign="top" align="left" class="cell53">
			            <font color="#595959">*</font>Head Office / ManagementState Sales ManagerStore ManagerAssistant Store ManagerSales Associate</td>
   				    <td width="50%" align="left" class="cell53">

   				    	<b>The following types of jobs are suitable for me:
					<br></b>
					<select name="type" class="inputbox"  style="font-size:11px;width:168px;"><option value="Full time">Full time</option>
	<option value="Part time">Part time</option>
	<option value="Casual">Casual</option>
	<option value="Contract">Contract</option>
	</select>
				
   				     </td>

   				     </tr>

   				   
							   <tr>
							   <td width="100%" valign="top" class="cell53" colspan="2">
							   
							<?php /*
							<tr>
							   <td width="100%" colspan="2" class="cell53" valign="top">
							*/ ?></td>
		</tr>
		<tr>
			<td width="100%" class="cell53" colspan="2"><img width="1" height="4" src="http://www.witchery.com.au/admin/images/spacer.gif"></td>
			</tr>
	   
			<input type="hidden" value="1002809" name="cyclestepid">
	


          <input type="hidden" value="1000000" name="objecttypeid" class="inputbox">
          <input type="hidden" value="new" name="passobjectid" class="inputbox">
          
          <input type="hidden" value="false" name="approvenow" class="inputbox">
          

		<tr>
				    <td width="50%" nowrap="" class="cell53">&nbsp;</td>
		  			<td width="50%" nowrap="" class="cell53">

			<input type="submit" border="0" alt="" value=" " name="Send" class="submitButton">
			  &nbsp; &nbsp;
			
		</td>
		</tr>
		
    </tbody></table>
    </div></form>