<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart">

	<div class="page-title title-buttons">
		<h1><?php echo $this->__('Shopping Bag') ?></h1>
	</div>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>	
    <?php echo $this->getChildHtml('form_before') ?>	
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post" id="cartform">
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table table table-condensed">

            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                <thead>
                    <tr>
                        <th class="a-item" rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Item') ?></th>
                        <th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><!--<?php echo $this->__('Product Name') ?>--></span></th>
						<th rowspan="<?php echo $mergedCells; ?>"></th>
                        <?php /* 
                        <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php // echo $this->__('Move to Wishlist') ?></span></th>
                        <?php endif ?>						 
						 */ ?>
                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
                        <th class="a-center" rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Quantity') ?></th>
                        <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
                    </tr>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <tr>												
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>						
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    </tr>
                    <?php endif; ?>
                </thead>              
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="50">
                            <?php if($this->getContinueShoppingUrl()): ?>
                                <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="btn continueshopping" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                            <?php endif; ?>
                            <button type="submit" title="<?php echo $this->__('Update Shopping Cart') ?>" class="btn updatecart"><span><span><?php echo $this->__('Update Shopping Cart') ?></span></span></button>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </fieldset>
    </form>
    
	
	<div class="row">
		<div class="span12">
				<?php //echo $this->getChildHtml('crosssell') ?>
			<div id="shippingbox">
					<?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
			</div>

			<div id="couponbox">						
				<?php echo $this->getChildHtml('coupon') ?>
			</div>            

			<!--<?php echo $this->getChildHtml('crosssell') ?>-->	
		</div>
	</div>
	
	<div class="row">	
		<div class="span12" id="totalbox">
			<div id="totalset">
				<?php echo $this->getChildHtml('totals'); ?>		
			</div>

			<?php echo $this->getChildHtml('crosssell') ?>
		</div>	
	</div>
	
	<?php if(!$this->hasError()): ?>
	<?php foreach ($this->getMethods('methods') as $method): ?>
		<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
		<?php echo $methodHtml; ?>
		<?php endif; ?>
	<?php endforeach; ?>
	<?php endif; ?>		
	
</div>