<?php /* @var $this FactoryX_ShippedFrom_Block_Adminhtml_Auspost_Product_View */ ?>
<?php
$data = $this->getData();
//echo sprintf("<pre>%s</pre>", print_r($data, true));
?>
<table cellspacing="2" class="box" style='width:100%;'>
<tbody>
<?php foreach ($this->getRenderedInfo() as $row):?>
<?php
    $isAmount = false;
    // $isAmount = $this->getObjectData($row, 'is_amount');?>
    <tr>
        <td style='padding:0 10px; white-space: nowrap;'>
            <strong><?php echo $this->escapeHtml($this->getObjectData($row, 'label'))?></strong>
        </td>
        <td<?php echo $isAmount ? ' class="a-right"' : ''?> style='width:100%;'>
            <?php echo $this->renderRowValue($row) ?>
        </td>
    </tr>
<?php endforeach;?>
</tbody>
</table>

<a href="<?php echo $data['back_url']; ?>"><?php echo __('Back to Account') ?></a>
