<?php
/**
 * princesshighway Filters Set
 *
 * Dropdown Filter set Integration
 * Benjamin Nicoll - @BEN_NICOLL
 * 
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_items = Mage::getBlockSingleton('catalog/product_list')->getLoadedProductCollection();
?>


<!-- Page Title
================================================== -->				
<div class="span12" id="titleset">
    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name')?> <small>(<?php echo $_items->getSize()?>)</small></h1>
</div>

<!-- End: Page Title
================================================== -->				


<!-- Filter Draft
================================================== -->				
<div class="span12" id="filterset">

	<ul>
		<li><button type="button" class="btn" data-toggle="collapse" data-target="#filteroptions">Show Filter Options</button></li>
		<li>Sort By 
		

			
		</li>
		<li>View</li>
		<li>Grid Options</li>
	</ul>
	 
	<div id="filteroptions" class="collapse">
	
	
		Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
	</div>
</div>

<!-- End: Filter Draft
================================================== -->				
