<!-- Left Side Footer
================================================== -->
<div class="span6">

		<div class="row">
			<!-- Stay in touch email signup
			================================================== -->
			<div class="span6" id="signupform">		
		    	<h2>princesshighway News</h2>
		    	<form action="http://www.princesshighway.com/t/r/s/jujktit/" method="post">
				
					<input id="fieldEmail" name="cm-jujktit-jujktit" type="email"  placeholder="E-MAIL" value="" required />
					&nbsp;&nbsp;
					<button type="submit" class="btn princesshighwaysignup">SIGN UP</button>
					<p>Signup to get the latest on sales, new releases and more fun!</p>	
				</form>
				
			</div>	
					
			<!-- End: Stay in touch email signup
			================================================== -->
		
		</div>

		<div class="row">

			<!-- Contact princesshighway
			================================================== -->
			<div class="span3" >
				<h2>Contact princesshighway</h2>
				<ul>
				    <li><a href="/product-enquiries/">Product Enquiries</a>
				    <li><a href="/store-locator/">Find Your Nearest Store</a></li>
				    <li><span class="storephone"><a href="tel://(03) 8420 0336">(03) 8420 0336</a></span>
				    <li><a href="mailto:princesshighwayonline@princesshighway.ws">E: princesshighwayonline@princesshighway.ws</a>
				</ul>
			
			</div>
		
			<!-- End: Contact princesshighway
			================================================== -->
		
			<!-- Feedback
			================================================== -->
			<div class="span3">
				<h2>Feedback</h2>
				<ul>
				    <li><a href="/contact.html">Contact Us</a>
				    <li><a href="/customersurvey/index/view/id/1">Compliments & Suggestions</a></li>				    
				</ul>
			
			</div>
		
			<!-- End: Feedback
			================================================== -->

		</div>
	
</div>

<!-- End: Left Side Footer
================================================== -->


<!-- Column 01
================================================== -->
<div class="span2">
	<h2>Shopping</h2>
	<ul>
	    <li><a href="/shop-the-look.html">Shop The Look</a>
	    <li><a href="/new-arrivals.html">New Arrivals</a>
	    <li><a href="/clothing.html">Clothing</a>
	    <li><a href="/accessories.html">Accessories</a>
	    <li><a href="/last-of-the-best.html">Last Of The Best</a>
		<li><a href="/gift-cards.html">Gift Cards</a>
	    <li><a href="/best-sellers.html">Best Sellers</a>
	    <li><a href="/sale.html">Sale</a>
	</ul>

</div>

<!-- End: Column 01
================================================== -->


<!-- Column 02
================================================== -->
<div class="span2">
	<h2>The Company</h2>
	<ul>
	    <li><a href="/about-us.html">About Us</a>
	    <li><a href="/careers/">Careers</a></li>		
	    <li><a href="/press-media.html">Press</a>
		<li><a href="/sustainability.html">Sustainability</a>			
	</ul>

	<h2>What's On</h2>
	<ul>
	    <?php /* <li><a href="/top-rated-content.html/">Top rated content</a> */ ?>
	    <li><a href="/competition.html">Competition</a></li>
	    <li><a href="/customersurvey/index/view/id/1">Surveys</a>
	    <li><a href="/events.html">Events</a>
	</ul>

</div>

<!-- End: Column 02
================================================== -->


<!-- Column 03
================================================== -->
<div class="span2">
	<h2>Information</h2>
	<ul>
	    <li><a href="/frequently-asked-questions.html">FAQ's</a>
	    <li><a href="/glossary.html/">Glossary</a>			
	    <li><a href="/size-chart.html/">Size Guide</a></li>
		<li><a href="/product-care.html/">Product Care</a></li>
	    <li><a href="/terms-conditions.html">Terms &amp; Conditions</a>
	</ul>

	<h2>Delivery</h2>
	<ul>
	    <li><a href="/shipping-delivery.html">Shipping &amp; Delivery</a>
	    <li><a href="returns-exchanges.html">Returns Policy</a></li>
	</ul>

</div>

<!-- End: Column 03
================================================== -->
