<?php echo $this->getChildHtml('contestPopup'); ?>
<!-- Footer Section
================================================== -->
<footer class="hidden-phone">
	<div class="container">	
		<div class="row">
			

			<!-- Column 01
			================================================== -->
			<div class="span2">
				<h2>Your Order</h2>
				<ul>
					<li><a href="/shipping-delivery">Shipping and Delivery</a>
					<li><a href="/returns-exchanges">Returns and Exchanges</a>
					<li><a href="/payment">Payments</a>
					<li><a href="/an-fyi">An FYI</a>
				</ul>
			</div>

			<!-- End: Column 01
			================================================== -->

			<div class="span2">
				<h2>About Us</h2>
				<ul>
					<li><a href="/contact-us">Contact</a>
					<li><a href="/our-story">Our Story</a>
					<li><a href="/our-store">Our Stores</a>
					<li><a href="/need-help">Need Help?</a>
					<li><a href="/about-us-from-you">About us from you!</a>
				</ul>
			</div>

			<div class="span2">
				<h2>Good To Know</h2>
				<ul>
					<li><a href="/legal">Legal</a>			
				</ul>
				<h2>Useful Stuff</h2>
				<ul>
					<li><a href="/size-guide">Size Guide</a>
					<li><a href="/gift-certificate">Gift Certificates</a>
					<li><a href="/careers">Careers</a>	
				</ul>
			</div>

			<!-- Left Side Footer
			================================================== -->
			<div class="span6">
				<section id="footer-credits" class="hidden-phone">
					
						<div class="row align-right">
							<!-- Stay in touch email signup
							================================================== -->
							<?php echo $this->getChildHtml('newsletterMini'); ?>
							<!-- End: Stay in touch email signup
							================================================== -->
						
						</div>		

						<div class="row">
							<!-- Copyright and Credits
							================================================== -->
							<div class="span2">
								<p class="credits">&copy; Princess Highway 2014. All rights reserved.</p>
							</div>

							<!-- End: Copyright and Credits
							================================================== -->

							<!-- Payments Badges and Social
							================================================== -->	            
							<div class="span4">
								<ul class="align-right">
									<!--<li class="accepted-creditcards"><img width="125" src="<?php echo $this->getSkinUrl('images/payment_methods.png') ?>" alt="Payment Methods"></li>-->
									<li class="comodo"><a href="http://www.instantssl.com" id="comodoTL"><?php echo $this->__('Instant SSL Certificate')?></a><script type="text/javascript">TrustLogo("<?php echo $this->getSkinUrl('images/comodo/tl_transp.gif'); ?>", "SC4", "none");</script></li>
									<li class="pinteresticon"><a href="http://pinterest.com/princesshighwayclothing/" title="Pinterest">Pinterest</a></li>
									<li class="facebookicon"><a href="https://www.facebook.com/princesshighwayclothing" title="Facebook">Facebook</a></li>
									<li class="instagramicon"><a href="http://instagram.com/princesshighwayclothing" title="Instagram">Instagram</a></li>
									<li class="youtubeicon"><a href="http://www.youtube.com/princesshighwayclothing" title="Youtube">Youtube</a></li>
								</ul>
							</div>
							<!-- End: Payments Badges and Social
							================================================== -->	       
						
						</div>	
						
				</section>
			</div>

			<!-- End: Left Side Footer
			================================================== -->



			<?php echo $this->getChildHtml('global_notices') ?>
		</div>
	</div>
</footer>