<?php echo $this->getChildHtml('topLinks') ?>

<!--<div class="brand">-->
<!--    <?php if ($this->getIsHomePage()): ?>
    <?php /*?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
     <?php */?>
    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="brand span3 active"><strong><?php echo $this->getLogoAlt() ?></strong></a>
    <?php else: ?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="brand span3"><strong><?php echo $this->getLogoAlt() ?></strong></a>
    <?php endif ?>
    -->
<!--</div>-->

<?php /*?>
    <p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
<?php */?>
            
</div><!--/.nav-collapse -->
