<!-- Navbar
================================================== -->				
<div class="storedetails">
	<p>
		<a href="/store-locator.html" class="navbarstores" title="Find your nearest Princess Highway store">Stores</a> 
		| 
		<a href="/contact.html" class="navbarcontact" title="Contact Princess Highway">Contact</a> 
		| 
		<span class="storephone"><a href="tel:<?php echo str_replace(' ', '%20',Mage::getStoreConfig('general/store_information/phone')); ?>"><?php echo Mage::getStoreConfig('general/store_information/phone'); ?></a></span>
	</p>
</div>
<div class="mobi-nav visible-phone  visible-tablet" >
	<a href="#" class="mobi-nav-toggle"><img class="icon-menu" src="<?php echo $this->getSkinUrl('images/core/menu-icon.png') ?>" alt="main menu"></a>
</div>
<!-- End: Navbar
================================================== -->				

<!-- Toplinks
================================================== -->
<div class="toplinks">
	<?php echo $this->getChildHtml('topLinks') ?>
</div>
<!-- End: Toplinks
================================================== -->

<!--<div class="brand">-->
<!--    <?php if ($this->getIsHomePage()): ?>
    <?php /*?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
     <?php */?>
    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="brand span3 active"><strong><?php echo $this->getLogoAlt() ?></strong></a>
    <?php else: ?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="brand span3"><strong><?php echo $this->getLogoAlt() ?></strong></a>
    <?php endif ?>
    -->
<!--</div>-->

<?php /*?>
    <p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
<?php */?>