<!-- Logo Section -->
<div class="logo">
	<a href="/" title="Princess Highway" id="transbrand"><img src="<?php echo $this->getSkinUrl(Mage::getStoreConfig('design/header/logo_src')) ?>" alt="<?=Mage::getStoreConfig('design/header/logo_alt')?>"></a>
</div>
<!-- End: Logo Section -->

<!-- Search and Social -->
<div class="searchsocial ">
	<ul class="align-right">
		<li class="pinteresticon"><a href="http://pinterest.com/princesshighwayclothing/" title="Pinterest">Pinterest</a></li>
		<li class="facebookicon"><a href="https://www.facebook.com/princesshighway" title="Facebook">Facebook</a></li>
		<li class="instagramicon"><a href="http://instagram.com/iloveprincesshighway" title="Instagram">Instagram</a></li>
		<li class="youtubeicon"><a href="http://www.youtube.com/princesshighwayclothing" title="Youtube">Youtube</a></li>
	</ul>
	<?php echo $this->getChildHtml('phsearch') ?>
</div>			
<!-- End: Search and Social -->