<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <div class="input-box">
            <input type="text" id="po_number" name="payment[po_number]" title="<?php echo $this->__('Purchase Order Number') ?>" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getInfoData('po_number')) ?>" placeholder="*<?php echo $this->__('Purchase Order Number') ?>"/>
        </div>
</div>
