<div class="nav-container sidebar-nav">
		<h2>
			<?php echo $this->__('My Account'); ?>
        </h2>
        <ul class="nav nav-list visible-desktop visible-tablet">
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="active<?php echo ($_last ? ' last' : '') ?>"><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
        
         <select class="visible-phone">
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <option selected class="active<?php echo ($_last ? ' last' : '') ?>" value="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></option>
                <?php else: ?>
                    <option<?php echo ($_last ? ' class="last"' : '') ?> value="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>
    
</div>
