<?php
// Retrieve the image to display
$image = $this->getData('image');
if ($image->getType() == "image")
{
	// Get its URL
	$imageUrl = $image->getUrl();
	// Generate its real URL
	$relMediaPath = substr(Mage::getBaseDir('media'), strlen(Mage::getBaseDir()) );
	$imagePath = sprintf("%s/homepage%s", Mage::getBaseDir('media'), $imageUrl);
	$imageUrl = str_replace(DS,"/",sprintf("%s/homepage%s", $relMediaPath, $imageUrl));
	// Test if image exists
	if (file_exists($imagePath))
	{
		if ($overImage = $this->getData('over'))
		{
			$overImagePath = sprintf("%s/homepage%s", Mage::getBaseDir('media'), $overImage->getUrl());
			$overImageUrl = str_replace(DS,"/",sprintf("%s/homepage%s", $relMediaPath, $overImage->getUrl()));
		}
		// Retrieve attributes of the image
		list($width, $height, $type, $attr) = getimagesize($imagePath);

		// If a link is set, we display it
		?>
		<?php if ($link = $image->getLink()): ?>
			<a <?php if ($image->getPopup()): ?>target="_blank" <?php endif; ?>href="<?php echo $link ?>">
		<?php endif; ?>

		<?php // Display picture ?>
		<img <?php echo $attr; ?> src="<?php echo $imageUrl ?>" alt="<?php echo $image->getAlt(); ?>" />
		<?php if (isset($overImageUrl)): ?>
		<div><img <?php echo $attr; ?> src="<?php echo $overImageUrl ?>" alt="<?php echo $image->getAlt(); ?>"/></div>
	<?php endif; ?>

		<?php if ($link): ?>
		</a>
	<?php endif; ?>
	<?php } // endif ?>
<?php }else{ ?>
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($image->getBlockId())->toHtml(); ?>
<?php } // endif ; ?>