<?php
if ($this->getRequest()->getParam('unsub')) {
?>
    <div style="margin:0px 30px 0px 30px; padding:15px 0 0 0">
        <ul class="messages">
            <li class="success-msg">
                <ul>
                    <li><span>You have unsubscribed from Princess Highway <?=$this->getRequest()->getParam('unsub')?></span></li>
                </ul>
            </li>
        </ul>
    </div>
<?php	
}

$populateDays = false;
$url ="";
if ((array_key_exists("HTTP_REFERER", $_SERVER)) 
	&& (strpos($_SERVER["HTTP_REFERER"],"key=") === false) 
	&& $this->helper('customer')->isLoggedIn() 
	&& !(isset($_GET['key']))) {
	$customer = Mage::getSingleton('customer/session')->getCustomer();
    $email = $customer->getEmail();
    $apiKey = trim(Mage::getStoreConfig('newsletter/campaignmonitor/api_key'));
    $url .= Mage::helper('core/url')->getHomeUrl().'subscribe?email='.$email.'&key='.md5($email.$apiKey);
?>
<script type="text/javascript">
	window.location = "<?=$url?>";
</script>
<?php
	}
	else
	{
		$email_hidden = "";
        if ($this->helper('customer')->isLoggedIn()) {
        	$email_hidden = "display: none";
        }
?>

	<div id="main" class="main-div newsletter-subscribe-div">

		<div id="newsletter-subscribe">	
		
			<div class="page-title" >
				<h1>Newsletter Subscription</h1>
			</div>
			
			<table border="0" style="<?php echo $email_hidden;?>">
				<tr>
					<td colspan="3">
						<?php echo $this->__('Subscribe with %s and be the first to receive our newsletter with updates on current promotions and the Collection.', Mage::app()->getStore()->getName()) ?>
					</td>
				</tr>
				
				<tr>
					<td colspan="3" class="10-high-td"></td>
				</tr>
				
				<tr>
					<td>
						<label for="email_address" class="required"><?php echo $this->__('Enter your email address.') ?><em>*</em></label>
					</td>
					<td colspan="2">
						<div class="input-box">
							<?php /* <input type="text" name="email" id="email_address" value="<?php echo Mage::getSingleton('core/session')->getEmail(); ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" /> */ ?>
							<?php
								$pre_fill_email = '';
								if ($this->getRequest()->getParam('email')){
									$pre_fill_email = htmlspecialchars($this->getRequest()->getParam('email'), ENT_QUOTES, 'UTF-8');;
								}else{
									$pre_fill_email = Mage::getSingleton('core/session')->getEmail();
								}

							?>
							<input type="text" name="email" id="email_address" value="<?php echo $pre_fill_email; ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />						
						</div>
					</td>
				</tr>
				<tr>
					<td colspan="3" id="subscription-next-button">
						<?php if ($email_hidden == ""): ?>
							<img id="retrieve-img" src="<?php echo $this->getSkinUrl('images/ajax-loader.gif'); ?>" alt="Loading" />
						<?php endif; ?>
						<button type="button" onclick="retrieveDetails(
						<?php
						if ($this->getRequest()->getParam('key')){
							   echo "'".$this->getRequest()->getParam('key')."'";
							}
						?>)" title="<?php echo $this->__('Next') ?>" class="button btn subscribe"><span><span class="buttonSpan" ><?php echo $this->__('Next') ?></span></span></button>
					</td>
				</tr>
				
				<tr>
					<td id="retrieve-message" colspan="3">
					</td>
				</tr>
				
			</table>
			
			<?php if ($email_hidden != ""): ?>
				<div id="main-loading">
					<img id="retrieve-img" src="<?php echo $this->getSkinUrl('images/ajax-loader.gif'); ?>" alt="Loading" />
				</div>
			<?php endif ?>

			<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
				
				<table border="0" width="100%" class="tbl1" id="hidden-newsletter">
					<input type="hidden" id="hidden_email" name="email" value="" />
					<input type="hidden" id="hidden_hash" name="hidden_hash" value="<?php if(isset($_GET["key"])) { echo htmlentities($_GET["key"]); } ?>" />
					<?php if ($this->getRequest()->getParam('key') && !($this->helper('customer')->isLoggedIn())): ?>
						<tr>
							<td class="label1">
								<label for="new_email"><?php echo $this->__('Update Email') ?></label>
							</td>
							<td colspan="2">
								<div class="input-box">
									<input type="text" name="new_email" id="new_email" value="<?php echo $pre_fill_email; ?>" title="<?php echo $this->__('New Email') ?>" class="input-text validate-email" />
								</div>
							</td>
						</tr>
						
						<tr>
							<td colspan="3" class="delimiter"></td>
						</tr>
					<?php endif; ?>
					<tr>
						<td class="label1">
							<label for="firstname"><?php echo $this->__('First Name') ?></label>
						</td>
						<td colspan="2">
							<div class="input-box">
								<input type="text" id="firstname" name="firstname" value="<?php echo Mage::getSingleton('core/session')->getFirstname(); ?>" title="<?php echo $this->__('First Name') ?>" class="input-text" <?php echo $this->getFieldParams() ?> />
							</div>
						</td>
					</tr>
					
					<tr>
						<td colspan="3" class="delimiter"></td>
					</tr>
					
					<tr>
						<td class="label1">
							<label for="lastname"><?php echo $this->__('Last Name') ?></label>
						</td>
						<td colspan="2">
							<div class="input-box">
								<input type="text" id="lastname" name="lastname" value="<?php echo Mage::getSingleton('core/session')->getLastname(); ?>" title="<?php echo $this->__('Last Name') ?>" class="input-text" <?php echo $this->getFieldParams() ?> />
							</div>
						</td>
					</tr>
					
					<tr>
						<td colspan="3" class="delimiter"></td>
					</tr>
					
					<?php
					/*<tr>
						<td class="label1">
							<label for="email_address" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
						</td>
						<td colspan="2">
							<div class="input-box">
								<input type="text" name="email" id="email_address" value="<?php echo Mage::getSingleton('core/session')->getEmail(); ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
							</div>
						</td>
					</tr>
					
					<tr>
						<td colspan="3" class="delimiter"></td>
					</tr>
					*/ ?>
					
					<tr>
						<td class="label1">
							<label for="mobile"><?php echo $this->__('Mobile') ?></label>
						</td>
						<td colspan="2">
							<div class="input-box">
								<input type="text" name="mobile" id="mobile" value="<?php echo Mage::getSingleton('core/session')->getMobile(); ?>" title="<?php echo $this->__('Mobile') ?>" class="input-text validate-number" />
							</div>
						</td>
					</tr>
					
					<tr>
						<td colspan="3" class="delimiter"></td>
					</tr>
					
					<tr>
						<td class="label1">
							<label for="state" class="required"><?php echo $this->__('Region') ?><em>*</em></label>
						</td>
						<td colspan="2">
							<div class="input-box">
								<select id="state" name="state" class="required-entry">
									<option value="Unknown"><?php echo $this->__('Select-->') ?></option>
									<?php if ($states = Mage::helper('campaignmonitor')->getCampaignMonitorStates()): ?>
										<?php sort($states); ?>
										<?php foreach ($states as $state): ?>
											<?php if ($state != "Unknown"): ?>
												<option value="<?php echo $state; ?>"><?php echo $state; ?></option>
											<?php endif; ?>
										<?php endforeach; ?>
									<?php endif; ?>
								</select>
							</div>
						</td>
					</tr>
					
					<tr>
						<td colspan="3" class="delimiter"></td>
					</tr>
					
					<tr>
						<td class="label1">
							<label for="postcode"><?php echo $this->__('Postcode') ?></label>
						</td>
						<td colspan="2">
							<div class="input-box">
								<input type="text" name="postcode" id="postcode" value="<?php echo Mage::getSingleton('core/session')->getPostcode(); ?>" title="<?php echo $this->__('Postcode') ?>" class="input-text validate-number" />
							</div>
						</td>
					</tr>
					
					<tr>
						<td colspan="3" class="delimiter"></td>
					</tr>
					
					<?php /*
					<tr>
						<td class="label1">
							<label for="periodicity"><?php echo $this->__('How often would you like<br/> to hear from us?') ?></label>
						</td>
						<td colspan="2">
							<div class="input-box">
								<select id="periodicity" name="periodicity">
									<option value="-1"><?php echo $this->__('Select-->') ?></option>
									<option value="Weekly"><?php echo $this->__('Weekly') ?></option>
									<option value="Fortnightly"><?php echo $this->__('Fortnightly') ?></option>
									<option value="Monthly"><?php echo $this->__('Monthly') ?></option>
									<option value="Only now and then"><?php echo $this->__('Only now and then') ?></option>
								</select>
							</div>
						</td>
					</tr>
					
					<tr>
						<td colspan="3" class="delimiter"></td>
					</tr>
					
					<tr>
						<td class="label1" colspan="2">
							<label for="jobinterest"><?php echo $this->__('Interested in working for Gorman? Tick this box to be notified of any Gorman jobs which arise.') ?></label>
						</td>		
						<td>
							<div class="input-box">
								<input name="jobinterest" id="jobinterest" type="checkbox" value="1" />
							</div>
						</td>
					</tr>
					
					<tr>
						<td colspan="3" class="delimiter"></td>
					</tr>
					*/ ?>
					
					<?php
					$_dob = $this->getLayout()->createBlock('customer/widget_dob');
					if ($_dob->isEnabled()):?>
						<tr>
							<td class="label1">
								<label for="month"><?php echo $this->__('Birthday') ?></label>
							</td>
							<td>
								<div class="input-box customer-dob">
									<label><?php echo $this->__('Month:') ?></label>
									<select id="month" name="month" onchange="populateDays(this, 0);">
										<option value="-1"><?php echo $this->__('Select-->') ?></option>
										<?php
										$mon = Mage::getSingleton('core/session')->getDobMonth();
										for ($x = 1; $x <= 12; $x++) 
										{
											$month_name = date("M", mktime(0, 0, 0, $x, 1, 2002));
											if ($mon == $x) 
											{
												$populateDays = true;
												echo "  <option value=\"$x\" selected>$month_name</option>\n";
											}
											else 
											{
												echo "  <option value=\"$x\">$month_name</option>\n";
											}
										}
										?>
									</select>
									<label><?php echo $this->__('Day:') ?></label>
									<select id="day" name="day" onchange="setDob();">
										<option value="-1"><?php echo $this->__('Select-->') ?></option>
									</select>

									<label><?php echo $this->__('Year:') ?></label>
									<select id="year" name="year" onchange="setDob();">
										<option value="-1"><?php echo $this->__('Select-->') ?></option>
										<?php 
											$year = Mage::getSingleton('core/session')->getDobYear();
											for($x=date("Y"); $x > date("Y")-100; $x--){
												if($year == $x)
												{
													 echo "  <option value=\"$x\" selected>$x</option>\n";
												} 
												else 
												{
													echo "  <option value=\"$x\">$x</option>\n";
												}
												
											}
										?>
									</select>
														
									<div class="dob-full">
										<input type="hidden" id="dob" name="dob" />
									</div>
									<div class="validation-advice"></div>
								</div>
							</td>
						</tr>
					<?php endif; ?>
					
					<tr>
						<td colspan="3" class="delimiter"></td>
					</tr>
					
					<tr>
						<td class="label1">
							<label for="promocode"><?php echo $this->__('Promo Code') ?></label>
						</td>
						<td colspan="2">
							<div class="input-box">
								<input type="text" id="promocode" name="promocode" value="<?php echo Mage::getSingleton('core/session')->getPromocode(); ?>" title="<?php echo $this->__('Promo Code') ?>" class="input-text" />
							</div>
						</td>
					</tr>
					
					<tr>
						<td colspan="3" class="delimiter"></td>
					</tr>
					
					<tr>
						<td></td>
						<td colspan="2" class="buttons-td">
						   <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button btn subscribe"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
						</td>
					</tr>
				</table>                       
			</form>
		</div>
		<div id="newsletter-subscribe-right">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('subscription-right-img')->toHtml() ?>
			<?php //echo $this->getChildHtml('subscription-right-img') ?>
		</div>		
		<script type="text/javascript">
			//<![CDATA[
			var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');	
			
			// Auto populate the date of birth
			<?php if ($populateDays): ?>
				populateDays(document.getElementById('month'), '<?php echo Mage::getSingleton('core/session')->getDobDay(); ?>');
			<?php endif; ?>
			
			// Hide DOB Year
			if (document.getElementById("year")) { document.getElementById("year").selectedIndex = 44; jQuery('#year').prev().hide(); jQuery('#year').hide(); }
			
			var state = '<?php echo Mage::getSingleton('core/session')->getState(); ?>';
			//alert("state: " + state);
			var oState = document.getElementById("state");
			if (oState)
			{
				for(var i=0;i<oState.length;i++) {
					if (oState.options[i].value == state) {
						oState.selectedIndex=i;
					}
				}
			}
			
			var periodicity = '<?php echo Mage::getSingleton('core/session')->getPeriodicity(); ?>';
			//alert("state: " + state);
			var oPeriodicity = document.getElementById("periodicity");
			if (oPeriodicity)
			{
				for(var i=0;i<oPeriodicity.length;i++) {
					if (oPeriodicity.options[i].value == periodicity) {
						oPeriodicity.selectedIndex=i;
					}
				}
			}
			//]]>
		</script>		
	</div>
	<script type="text/javascript">
		//<![CDATA[
		function retrieveDetails(securehash, unsub) {
			// Strict mode
			"use strict";
			// Get the email
			var email = document.getElementById("email_address").value;
			// If no email is given
			if (email == "")
			{
				// We display an error without calling the AJAX system
				jQuery('#retrieve-message').removeClass();
				jQuery('#retrieve-message').html("Please enter your email address first");
				jQuery('#retrieve-message').addClass("error");
			}
			else
			{
				// We show the loading icon
				jQuery('#retrieve-img').css("display","inline");
				// We store the email in the form via an hidden input
				jQuery('#hidden_email').attr('value',email);
				// Base URL in case we're using a subfolder
				var base_url = '';
				if (location.protocol == 'https:'){
					base_url="<?php echo Mage::getUrl('',array('_secure'=>true));?>";
				}else{
					base_url='<?php echo Mage::getBaseUrl()?>';
				}
				// AJAX Call
				jQuery.ajax( {
					url : base_url+"campaignmonitor/subscriber/retrieve",
					dataType : 'json',
					type : 'get',
					data : {"email" :email, "securehash": securehash, "unsub": unsub},
					success : function(data) {
						// If the AJAX call has worked
						// We first empty everything in the form
						jQuery('#firstname').attr("value","");
						jQuery('#lastname').attr("value","");
						jQuery('#mobile').attr("value","");
						jQuery('#new_email').attr("value",email);
						if (document.getElementById("state")) document.getElementById("state").selectedIndex = 0;
						jQuery('#postcode').attr("value","");
						jQuery('#promocode').attr("value","");
						if (document.getElementById("periodicity")) document.getElementById("periodicity").selectedIndex = 0;
						if (document.getElementById("month")) document.getElementById("month").selectedIndex = 0;
						if (document.getElementById("day")) document.getElementById("day").selectedIndex = 0;
						if (document.getElementById("year")) { document.getElementById("year").selectedIndex = 44; jQuery('#year').prev().hide(); jQuery('#year').hide(); }
						if (document.getElementById("jobinterest")) document.getElementById("jobinterest").selectedIndex = 0;
						
						if (data.interests){
							for (var i=0;i<data.interests.length;i++){
								jQuery('#'+data.interests[i]).attr('checked','checked');
							}
						}else if(data.status != "EXISTING"){
							jQuery('#newslists > input').each(function(){
								jQuery(this).attr('checked','checked');
							})
						}
						
						if (data.status == "INVALID"){
							window.location.replace(data.message);
						}else{					
							// We display the message
							jQuery('#retrieve-message').removeClass();
							jQuery('#retrieve-message').html(data.message);
						}
						
						// If there was an error, we hide the form (in case it was displayed by a previous subscription)
						if (data.status == "ERROR")
						{
							jQuery('#retrieve-message').addClass('error');
							jQuery('#hidden-newsletter').slideUp();
							jQuery('#retrieve-img').css("display","none");
							return;
						}
						// If it's an existing subscriber we fill the form with the corresponding details
						if (data.status == "EXISTING")
						{
							jQuery('#retrieve-message').addClass('success');
							// Name
							if (data.Name) {
								var firstSpaceIndex = data.Name.indexOf(' ');
								jQuery('#firstname').attr("value",data.Name.substring(0,firstSpaceIndex));
								jQuery('#lastname').attr("value",data.Name.substring(firstSpaceIndex+1, data.Name.length));
							}
							// Mobile
							if (data.Mobile) jQuery('#mobile').attr("value",data.Mobile);
							// State
							if (data.State) 
							{
								var oState = document.getElementById("state");
								if (oState)
								{
									for(var i=0;i<oState.length;i++) {
										if (oState.options[i].value == data.State) {
											oState.selectedIndex=i;
										}
									}
								}
							}
							// Postcode
							if (data.Postcode) jQuery('#postcode').attr("value",data.Postcode);
							// Promocode
							if (data["Promo Code"]) jQuery('#promocode').attr("value",data["Promo Code"]);
							// Periodicity
							if (data.Periodicity) 
							{
								var oPeriodicity = document.getElementById("periodicity");
								if (oPeriodicity)
								{
									for(var i=0;i<oPeriodicity.length;i++) {
										if (oPeriodicity.options[i].value == data.Periodicity) {
											oPeriodicity.selectedIndex=i;
										}
									}
								}
							}
							// Date Of Birth
							if (data.DateOfBirth)
							{
								var splitDob = data.DateOfBirth.split('-');
								var monthDob = parseInt(splitDob[1],10);
								var oMonthDob = document.getElementById("month");
								for(var i=0;i<oMonthDob.length;i++) {
									if (monthDob==i) oMonthDob.selectedIndex=i;
								}
								var yearDob = parseInt(splitDob[0],10);
								var oYearDob = document.getElementById("year");
								for(i=0;i<oYearDob.length;i++) {
									if (oYearDob.options[i].value == yearDob) {
										oYearDob.selectedIndex=i;
									}
								}
								var dayDob = parseInt(splitDob[2],10);
								populateDays(document.getElementById('month'),dayDob);
							}
							// Job Interest
							if (data["Job Interest"]) 
							{
								var oJobInterest = document.getElementById("jobinterest");
								if (oJobInterest)
								{
									for(var i=0;i<oJobInterest.length;i++) {
										if (oJobInterest.options[i].value == data["Job Interest"]) {
											oJobInterest.selectedIndex=i;
										}
									}
								}
							}
							// Hide the loading img
							jQuery('#retrieve-img').css("display","none");
							// Change the title of the button
							jQuery('#subscription-button-td button').attr('title','Update');
							jQuery('#subscription-button-td button span span').html('Update');
							// Show the form
							jQuery('#hidden-newsletter').slideDown();
						}
						else if(data.status == "NEW")
						{
							// If it's a new subscriber
							jQuery('#retrieve-img').css("display","none");
							jQuery('#subscription-button-td button').attr('title','Subscribe');
							jQuery('#subscription-button-td button span span').html('Subscribe');
							jQuery('#hidden-newsletter').slideDown();
						}
					}
				});
			}
		}
		//]]>
	</script>

	<?php if ($this->getRequest()->getParam('key') && $this->getRequest()->getParam('unsub')): ?>
		   <script type="text/javascript">retrieveDetails("<?php echo $this->getRequest()->getParam('key') ?>","<?php echo $this->getRequest()->getParam('unsub') ?>")</script>
	<?php elseif ($this->getRequest()->getParam('key')): ?>
		   <script type="text/javascript">retrieveDetails("<?php echo $this->getRequest()->getParam('key') ?>")</script>
	<?php elseif (Mage::getSingleton('core/session')->getEmail()): ?>
		   <script type="text/javascript">retrieveDetails()</script>
	<?php endif; ?>    

	<?php // If a customer is logged in, we automatically fill the email and retrieve the details ?>
	<?php /*if (Mage::getSingleton('customer/session')->isLoggedIn()): ?>
	<script type="text/javascript">
		jQuery('#email_address').attr('value','<?php echo Mage::getSingleton('customer/session')->getCustomer()->getEmail() ?>');
		retrieveDetails();
	</script>
	<?php endif;*/ ?>
<?php } ?>