<?php
/** @var Mage_Catalog_Model_Resource_Setup $installer */
$installer = $this;
$installer->startSetup();

$envConfig = array(
    "default" => array(
        "currency/options/allow"                  => 'AUD,GBP,CNY,EUR,USD',
        "currency/import/enabled"        => '1',
        "currency/import/service"        => 'fixerio',
        "currency/import/error_email"        => 'ben.incani@factoryx.com.au',
        "contacts/email/recipient_email"        => 'contactus@princesshighway.com.au',
        "contacts/email/sender_email_identity"        => 'general',
        "general/country/default"        => 'AU',
        "general/country/allow"        => 'AX,AL,AS,AD,AI,AQ,AG,AR,AM,AU,AT,AZ,BS,BH,BD,BB,BY,BE,BZ,BJ,BM,BT,BO,BA,BV,BR,IO,VG,BN,BG,BG,BI,KH,CA,KY,CL,CN,CX,CC,CO,KM,CK,CR,HR,CU,CY,CZ,DK,DJ,DM,DO,EC,EG,SV,GQ,ER,EE,FK,FO,FJ,FI,FR,GF,PF,TF,GE,DE,GI,GR,GL,GD,GP,GT,GG,GN,GW,GY,HT,HM,HN,HK,HU,IS,IN,IE,IM,JM,JP,JE,JO,KZ,KI,KG,LA,LV,LB,LS,LI,LT,LU,MO,MK,MV,ML,MT,MH,MQ,MR,MU,YT,MX,FM,MD,MC,MN,ME,MS,MA,MM,NP,NL,AN,NC,NZ,NF,MP,KP,NO,OM,PW,PS,PA,PG,PY,PE,PH,PN,PL,PR,PR,QA,RE,RO,BL,SH,KN,LC,MF,PM,VC,WS,SM,ST,SA,RS,SC,SG,SK,SI,SB,GS,KR,ES,LK,SR,SJ,SE,CH,SY,TW,TJ,TH,TL,TK,TO,TR,TM,RC,TV,GB,UA,AE,UY,US,UM,VI,UZ,VA,VE,VN,WF',
        "general/region/state_required"        => 'AU,AT,CA,EE,FI,FR,DE,LV,LT,RO,ES,CH,US',
        "general/store_information/name"        => 'Princess Highway',
        "general/store_information/phone"        => '(03) 8420 0331',
        "general/store_information/merchant_country"        => 'AU',
        "general/store_information/head_phone"        => '(03) 9429 0000',
        "general/store_information/address"        => '65 Victoria Crescent Abbotsford 3067 Victoria, Australia',
        "web/url/redirect_to_base"        => '0',
        "web/seo/use_rewrites"        => '1',
        "web/secure/use_in_frontend"        => '1',
        "web/secure/use_in_adminhtml"        => '1',
        "web/cookie/cookie_lifetime"        => '86400',
        "web/cookie/cookie_path"        => '/',
        "web/cookie/cookie_domain"        => '.princesshighway.com.au',
        "web/cookie/cookie_httponly"        => '0',
        "web/session/use_frontend_sid"        => '0',
        "web/browser_capabilities/cookies"        => '0',
        "design/head/default_title"        => 'Princess Highway Online',
        "design/head/default_description"        => 'Princess Highway Online',
        "design/header/logo_alt"        => 'Princess Highway Online',
        "design/header/welcome"        => 'Welcome to Princess Highway Online.',
        "trans_email/ident_general/name"        => 'Princess Highway Online',
        "trans_email/ident_general/email"        => 'contactus@princesshighway.com.au',
        "trans_email/ident_sales/name"        => 'Princess Highway Online',
        "trans_email/ident_sales/email"        => 'contactus@princesshighway.com.au',
        "trans_email/ident_support/name"        => 'Princess Highway Online',
        "trans_email/ident_support/email"        => 'contactus@princesshighway.com.au',
        "trans_email/ident_custom1/name"        => 'Princess Highway Online',
        "trans_email/ident_custom1/email"        => 'contactus@princesshighway.com.au',
        "trans_email/ident_custom2/name"        => 'Princess Highway Online',
        "trans_email/ident_custom2/email"        => 'contactus@princesshighway.com.au',
        "trans_email/ident_recruitment/name"        => 'Tara Murphy',
        "trans_email/ident_recruitment/email"        => 'recruitment@princesshighway.com.au',
        "trans_email/ident_pr_and_media/name"        => 'Roy Christou',
        "trans_email/ident_pr_and_media/email"        => 'roy@factoryx.com.au',
        "trans_email/ident_marketing/name"        => 'Roy Christou',
        "trans_email/ident_marketing/email"        => 'roy@factoryx.com.au',
        "trans_email/ident_retail/name"        => 'Stephanie Cameron',
        "trans_email/ident_retail/email"        => 'stephanie@factoryx.com.au',
        "cms/wywiwyg/enabled"        => 'disabled',
        "gtspeed/cssjs/min_css"        => '1',
        "gtspeed/cssjs/merge_css"        => '1',
        "gtspeed/cssjs/min_js"        => '1',
        "gtspeed/cssjs/merge_js"        => '1',
        "mageworx_seo/seosuite/pager_url_format"        => '/p/[page_number]',
        "mageworx_seo/google_sitemap/enabled"        => '1',
        "mageworx_seo/google_sitemap/error_email"        => 'ben.incani@factoryx.com.au',
        "disablelog/options/enable"        => '1',
        "bdayconfig/options/enable"        => '1',
        "bdayconfig/options/name"        => 'Princess Highway Online',
        "bdayconfig/options/email"        => 'contactus@princesshighway.com.au',
        "bdayconfig/options/cron_expr"        => '0 3 * * *',
        "bdayconfig/coupon/value"        => '15',
        "careers_module/options/enable_jquery"        => '0',
        "careers_module/options/enable_bootstrap"        => '0',
        "fxcons/options/enable"        => '1',
        "contests/options/name"        => 'Princess Highway Online',
        "contests/options/email"        => 'contactus@princesshighway.com.au',
        "gua/general/enabled"        => '1',
        "gua/ecommerce/enableec"        => '1',
        "gua/ecommerce/funnel_enable"        => '1',
        "homepage/options/allowed_themes"        => 'factoryx/default,factoryx/princess',
        "factoryx_instagram/module_options/enabled"        => '1',
        "factoryx_instagram/product_options/enabled"        => '1',
        "factoryx_instagram/product_options/instruction"        => 'Share your #TAG',
        "factoryx_instagram/product_options/product"        => '1',
        "factoryx_instagram/product_options/product_limit"        => '4',
        "picklist/default_filter/show_cg_filter"        => '1',
        "picklist/email_settings/send_store_email"        => '1',
        "picklist/debug/log_debug"        => '1',
        "picklist/cron_job_daily_generation/enabled"        => '1',
        "picklist/cron_job_daily_generation/split_pdf"        => '1',
        "picklist/cron_job_daily_generation/additional_emails"        => 'ben.incani@factoryx.com.au',
        "picklist/cron_job_daily_delete/enabled"        => '1',
        "ustorelocator/general/page_title"        => 'Store Locations',
        "ustorelocator/general/page_url"        => 'storelocations',
        "ustorelocator/general/sl_layout"        => 'one_column',
        "catalog/frontend/list_mode"        => 'grid',
        "catalog/frontend/grid_per_page_values"        => '6,12,24,36',
        "catalog/frontend/grid_per_page"        => '6',
        "catalog/frontend/list_allow_all"        => '1',
        "catalog/frontend/flat_catalog_category"        => '1',
        "catalog/frontend/flat_catalog_product"        => '1',
        "catalog/review/allow_guest"        => '0',
        "cataloginventory/options/show_out_of_stock"        => '1',
        "cataloginventory/options/stock_threshold_qty"        => '3',
        "cataloginventory/item_options/max_sale_qty"        => '20',
        "sales_pdf/firegento_pdf/company_name"        => 'Factory X Pty Ltd',
        "sales_pdf/firegento_pdf/company_abn"        => '51 078 151 667',
        "sales_pdf/firegento_pdf/thankyou_message"        => 'Thank-you',
        "sales_pdf/firegento_pdf/show_lines_between_items"        => '1',
        "sales_pdf/firegento_pdf/show_page_nbr"        => '1',
        "sales_pdf/firegento_pdf/show_footer"        => '1',
        "sales_pdf/invoice/document_title"        => 'Tax Invoice',
        "sales_pdf/invoice/show_customer_number"        => '0',
        "sales_pdf/invoice/payment_method_position"        => 'note',
        "sales_pdf/invoice/shipping_method_position"        => 'note',
        "sales_pdf/invoice/show_comments"        => '1',
        "sales_pdf/shipment/document_title"        => 'Packing Slip',
        "sales_pdf/shipment/show_customer_number"        => '0',
        "sales_pdf/shipment/shipping_method_position"        => 'note',
        "sales_pdf/shipment/show_comments"        => '1',
        "sales_pdf/creditmemo/document_title"        => 'Refund',
        "sales_pdf/creditmemo/show_customer_number"        => '0',
        "sales_pdf/creditmemo/show_comments"        => '1',
        "checkout/payment_failed/copy_to"        => 'admin@princesshighway.com.au',
        "checkout/payment_failed/copy_method"        => 'copy',
        "shipping/origin/country_id"        => 'AU',
        "shipping/origin/region_id"        => '491',
        "shipping/origin/postcode"        => '3067',
        "shipping/origin/city"        => 'Abbotsford',
        "shipping/origin/street_line1"        => '61 Church St',
        "ampromo/general/message"        => 'Available free items',
        "ampromo/general/add_message"        => '<style>
#ampromo-items-add {
    border: 0 !important;
    padding: 0 !important;
}
</style>
<div style=\'width:100%; margin-bottom:10px;\'><div id=\'free-leggings\' style=\'background-color:#000; color:#fff; text-align:center; padding:10px;\'>
Select your FREE <a style="color:#fff;" href="">Knit Animal Slippers</a></div></div>',
        "ampromo/banners/enabled_top"        => '0',
        "ampromo/banners/enabled_above_cart"        => '0',
        "admin/url/use_custom_path"        => '1',
        "admin/url/custom_path"        => 'factoryx',
        "admin/security/use_case_sensitive_login"        => '1',
        "admin/security/domain_policy_frontend"        => '1',
        "admin/security/extensions_compatibility_mode"        => '0',
        "dev/index/enable"        => '1',
        "dev/index/disable"        => '1',
        "dev/index/notvisible"        => '1',
        "system/cron/history_success_lifetime"        => '2880',
        "system/cron/history_failure_lifetime"        => '2880',
        "system/log/clean_after_day"        => '7',
        "system/log/error_email"        => 'admin@princesshighway.com.au',
        "fontis_australia/postcode_autocomplete/enabled"        => '1',
        "currency/import/time"        => '02,00,00',
        "system/log/time"        => '06,00,00',
    )
);
/** @var Mage_Core_Model_Config $coreConfig */

$coreConfig = Mage::getModel('core/config');
// load default
foreach($envConfig["default"] as $path => $val) {
    $coreConfig->saveConfig($path, $val, 'default', 0);
}


$installer->endSetup();